### ISSUE TITLE
如何设置自己的文件目录

### ISSUE THREAD

**Issue by deepsea887** [kalcaddle/KODExplorer#1]
因为我看到的都是demo中的文件。

**Comment by CodeIgniter** [comment]
我实现了每个用户自定义根目录的功能， @kalcaddle 有兴趣我可以提交一个 pull request，但是 js 我都是用压缩过的代码修改的。

**Comment by kalcaddle** [comment]
这个功能很简单，但开放会带来安全问题。所以暂不提供。
如果不担心安全问题，直击使用管理员组即可。

**Comment by CodeIgniter** [comment]
这个可能和我的需求场景有关系吧，管理员组的用户，根目录没法限制住。
