### ISSUE TITLE
Cant find the option to disable recycle

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KODExplorer#103]
Hi my friend! How can I disable moving files to recycle when the user deletes something? This was the default behaviour in the last version and it caused me lots of problems cause every deleted file was moved to a bin and it would make my server full of junk files. Is there an option to disable this behaviour or even better, disable bin?

**Comment by kalcaddle** [comment]
change the config/confit.php 

"recycle_open"		=> "1",	
to
"recycle_open"		=> "0",

**Comment by batata004** [comment]
My friend, I cant find the config you said. My config.php file is like this:



```



<?php
/*
* @link http://www.kalcaddle.com/
* @author warlee | e-mail:kalcaddle@qq.com
* @copyright warlee 2014.(Shanghai)Co.,Ltd
* @license http://kalcaddle.com/tools/licenses/license.txt
*/

define('GLOBAL_DEBUG',0);//0 or 1
@date_default_timezone_set(@date_default_timezone_get());
@set_time_limit(1200);//10min pathInfoMuti,search,upload,download...
@ini_set("max_execution_time",1200);
@ini_set('session.cache_expire',1800);
ob_start();
if(GLOBAL_DEBUG){
	define('STATIC_JS','_dev');  //_dev||app
	define('STATIC_LESS','less');//less||css
	@ini_set("display_errors","on");
	@error_reporting(E_ERROR|E_WARNING|E_PARSE);//E_ALL or E_ERROR|E_WARNING|E_PARSE
}else{
	define('STATIC_JS','app');  //app
	define('STATIC_LESS','css');//css
	@ini_set("display_errors","on");//on off
	@error_reporting(E_ERROR|E_WARNING|E_PARSE); // 0
}

header("Content-type: text/html; charset=utf-8");
header('HTTP/1.1 200 Ok');//兼容部分lightHttp服务器环境
define('BASIC_PATH',str_replace('\\','/',dirname(dirname(__FILE__))).'/');
define('TEMPLATE',      BASIC_PATH .'template/');   //模版文件路径
define('CONTROLLER_DIR',BASIC_PATH .'controller/'); //控制器目录
define('MODEL_DIR',     BASIC_PATH .'model/');      //模型目录
define('LIB_DIR',       BASIC_PATH .'lib/');        //库目录
define('PLUGIN_DIR',    LIB_DIR .'plugins/');       //插件目录
define('FUNCTION_DIR',	LIB_DIR .'function/');		//函数库目录
define('CLASS_DIR',		LIB_DIR .'class/');			//内目录
define('CORER_DIR',		LIB_DIR .'core/');			//核心目录

/*
 * 可以数据目录;移到web目录之外，可以使程序更安全, 就不用限制用户的扩展名权限了;
 * 1. 需要先将data/的子目录移到别的地方 例如D:/ 则先将data下面的所有文件夹拷贝到D:/
 * 2. 修改配置 define('DATA_PATH','D:/');
 */
define('DATA_PATH',     BASIC_PATH .'data/');       //用户数据目录
define('USER_PATH',     DATA_PATH .'User/');        //用户目录
define('GROUP_PATH',    DATA_PATH .'Group/');       //群组目录
define('USER_SYSTEM',   DATA_PATH .'system/');      //用户数据存储目录
define('TEMP_PATH',     DATA_PATH .'temp/');        //临时目录
define('LOG_PATH',      TEMP_PATH .'log/');         //日志
define('DATA_THUMB',    TEMP_PATH .'thumb/');       //缩略图生成存放
define('LANGUAGE_PATH', BASIC_PATH .'config/i18n/');//多语言目录
define('SESSION_ID','KOD_SESSION_ID_'.substr(md5(BASIC_PATH),0,5));
define('KOD_SESSION',   DATA_PATH .'session/');     //session目录

define('OFFICE_SERVER',"https://owa-box.vips100.com/op/view.aspx?src=");
// https://owa-box.vips100.com/op/view.aspx?src=
// http://preview.tita.com/op/view.aspx?src=
// https://docview.mingdao.com/op/view.aspx?src=
// https://view.officeapps.live.com/op/view.aspx?src=

include_once(FUNCTION_DIR.'web.function.php');
include_once(FUNCTION_DIR.'file.function.php');
include_once(FUNCTION_DIR.'common.function.php');
include_once(CORER_DIR.'Application.class.php');
include_once(CORER_DIR.'Controller.class.php');
include_once(CORER_DIR.'Model.class.php');
include_once(CLASS_DIR.'fileCache.class.php');
include_once(CLASS_DIR.'mcrypt.class.php');
include_once(CONTROLLER_DIR.'system_member.class.php');
include_once(CONTROLLER_DIR.'system_group.class.php');
include_once(CONTROLLER_DIR.'system_role.class.php');
include_once(CONTROLLER_DIR.'util.php');
include_once(BASIC_PATH.'config/setting.php');
include_once(BASIC_PATH.'config/version.php');

define('WEB_ROOT',get_webroot(BASIC_PATH));
define('HOST',get_host().'/');
define('APPHOST',HOST.str_replace(WEB_ROOT,'',BASIC_PATH));//程序根目录

//数据地址定义。
$config['pic_thumb']	= BASIC_PATH.'data/thumb/';		// 缩略图生成存放地址
$config['cache_dir']	= BASIC_PATH.'data/cache/';		// 缓存文件地址
$config['app_startTime'] = mtime();         			//起始时间
$config['app_charset']	 = 'utf-8';			            //该程序整体统一编码
$config['settings']['static_path'] = "./static/";     //静态文件目录
$config['check_charset'] = 'ISO-8859-1,ASCII,UTF-8,GBK,GB2312,BIG5,EUC-KR,EUC-JP,shift-jis,eucjp-win,sjis-win,JIS'; //文件打开自动检测编码

//when edit a file ;check charset and auto converto utf-8;
if (strtoupper(substr(PHP_OS, 0,3)) === 'WIN') {
	$config['system_os']='windows';
	$config['system_charset']='gbk';// EUC-JP/Shift-JIS/BIG5  //user set your server system charset
} else {
	$config['system_os']='linux';
	$config['system_charset']='utf-8';
}  

init_common();
if(isset($in[SESSION_ID])){//office edit post
	session_id($in[SESSION_ID]);
}
if(isset($in['access_token'])){//office edit post
	session_id($in['access_token']);
}
@session_name(SESSION_ID);
@session_save_path(KOD_SESSION);//session path
@session_start();
@session_write_close();//避免session锁定问题;之后要修改$_SESSION 需要先调用session_start()
$config['autorun'] = array(
	array('controller'=>'user','function'=>'loginCheck'),
	array('controller'=>'user','function'=>'authCheck')
);

```

**Comment by batata004** [comment]
Actually I found the recycle_open at setting.php but after changing it to 0 when I remove a file it still goes to recycle. Could you please investigate this?

**Comment by liaoke** [comment]
Actually you should change system_role.php at ../data/system/.   Found  **"name": "guest"**, and change  settings below:  **"explorer:pathDeleteRecycle": 1, to 0**

**Comment by batata004** [comment]
My friend, the file system_role.php you said does not contain the line you said, it does not even contain the word "guest". Also the setting "explorer:pathDeleteRecycle" is already with 0 and when I delete a file it is already being moved to trash.

Check the content of this file below:


`<?php exit;?>{"1":{"name":"Administrator","ext_not_allow":"","explorer:mkdir":0,"explorer:mkfile":0,"explorer:pathRname":0,"explorer:pathDelete":0,"explorer:zip":0,"explorer:unzip":0,"explorer:pathCopy":0,"explorer:pathChmod":0,"explorer:pathCute":0,"explorer:pathCuteDrag":0,"explorer:pathCopyDrag":0,"explorer:clipboard":0,"explorer:pathPast":0,"explorer:pathInfo":0,"explorer:serverDownload":0,"explorer:fileUpload":0,"explorer:search":0,"explorer:pathDeleteRecycle":0,"explorer:fileDownload":0,"explorer:zipDownload":0,"explorer:fileDownloadRemove":0,"explorer:fileProxy":0,"explorer:officeView":0,"explorer:officeSave":0,"app:user_app":0,"app:init_app":0,"app:add":0,"app:edit":0,"app:del":0,"user:changePassword":0,"editor:fileGet":0,"editor:fileSave":0,"userShare:set":0,"userShare:del":0,"setting:set":0,"setting:system_setting":0,"setting:php_info":0,"fav:add":0,"fav:del":0,"fav:edit":0,"system_member:get":0,"system_member:add":0,"system_member:do_action":0,"system_member:edit":0,"system_group:get":0,"system_group:add":0,"system_group:del":0,"system_group:edit":0,"system_role:add":0,"system_role:del":0,"system_role:edit":0},"2":{"name":"default","ext_not_allow":"php|jsp|html","explorer:mkdir":1,"explorer:mkfile":1,"explorer:pathRname":1,"explorer:pathDelete":1,"explorer:zip":1,"explorer:unzip":1,"explorer:pathCopy":1,"explorer:pathChmod":0,"explorer:pathCute":1,"explorer:pathCuteDrag":1,"explorer:pathCopyDrag":0,"explorer:clipboard":1,"explorer:pathPast":1,"explorer:pathInfo":1,"explorer:serverDownload":1,"explorer:fileUpload":1,"explorer:search":1,"explorer:pathDeleteRecycle":0,"explorer:fileDownload":1,"explorer:zipDownload":0,"explorer:fileDownloadRemove":0,"explorer:fileProxy":0,"explorer:officeView":0,"explorer:officeSave":0,"app:user_app":1,"app:init_app":0,"app:add":0,"app:edit":0,"app:del":0,"user:changePassword":1,"editor:fileGet":0,"editor:fileSave":1,"userShare:set":1,"userShare:del":1,"setting:set":1,"setting:system_setting":0,"setting:php_info":0,"fav:add":1,"fav:del":1,"fav:edit":1,"system_member:get":0,"system_member:add":0,"system_member:do_action":0,"system_member:edit":0,"system_group:get":0,"system_group:add":0,"system_group:del":0,"system_group:edit":0,"system_role:add":0,"system_role:del":0,"system_role:edit":0}}`

**Comment by batata004** [comment]
any answer at this? is this problem fixed?
