### ISSUE TITLE
Auto login guest is working

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KODExplorer#104]
Hi,

I am using the auto login feature with the user guest and password guest. It works, but right after I log in, the file explorer shows a random directory (probably a user directory). Can I make the file explorer open a specific directory of some bookmark right after login?

**Comment by kalcaddle** [comment]
You can do it like this:

index.php?user/loginSubmit&name=guest&password=guest&link=[your url]

url goto path like this : index.php?explorer/index&path=/
