### ISSUE TITLE
problem in the Arabic-language file names

### ISSUE THREAD

**Issue by eArabic** [kalcaddle/KODExplorer#105]
Thank you very much for the update ...
There is a problem in the Arabic-language file names, it does not appear correctly, but written in Chinese.
File name does not appear in his name right, but strange symbols.

![q](https://cloud.githubusercontent.com/assets/24383546/21468364/909e71a2-ca1e-11e6-9cce-5298d25170d9.png)

**Comment by kalcaddle** [comment]
It is because of your system charset.

you can change it at config.php 
$config['system_charset']='utf-8';


set your system charset.

**Comment by eArabic** [comment]
Thank you very much, you make changes texts appeared correctly, but the other problem has occurred.
Desktop icons disappeared became not appear.
```
if (strtoupper(substr(PHP_OS, 0,3)) === 'WIN') {
	$config['system_os']='windows';
 	$config['system_charset']='utf-8';// EUC-JP/Shift-JIS/BIG5  //user set your server system charset
```

![0000](https://cloud.githubusercontent.com/assets/24383546/21470406/a426edd8-ca98-11e6-8c40-512a12be31b9.png)



![sss](https://cloud.githubusercontent.com/assets/24383546/21470408/aadcd250-ca98-11e6-8810-01ae6fb3ccc9.png)

**Comment by kalcaddle** [comment]
you can email to me:kalcaddle@qq.com（link username and password）
Let me have a try.

**Comment by eArabic** [comment]
Thank you very much, the problem was resolved, it was the reason that the local hosting Xampp on a personal computer, when you raise files to Website Hosting  the reality of the problems disappeared.
Once again thank you very much to communicate

**Comment by kalcaddle** [comment]
Good !
