### ISSUE TITLE
更新了3.35后新建用户名是字符串形式

### ISSUE THREAD

**Issue by jainoo** [kalcaddle/KODExplorer#106]
![16 12 25 1812_3](https://cloud.githubusercontent.com/assets/14904239/21470663/b96ad13e-cacd-11e6-8723-e0533aedb638.jpg)

**Comment by kalcaddle** [comment]
为安全考虑，
新版本对非管理员用户路径做了彻底隐藏。

管理员可以在：
用户管理——编辑用户——查看用户对应的真实路径。(可以添加到收藏夹)
