### ISSUE TITLE
回收站中存在同名文件导致无法删除

### ISSUE THREAD

**Issue by liaoke** [kalcaddle/KODExplorer#107]
举例：
当回收站启用时，如果回收站中已经存在A.txt，在任意文件夹中删除同名文件A.txt（无论文件md5是否相同）时将无法删除（提示error）。

另外希望可以在系统设置中手动设置文件上传分割大小，用来适应复杂条件下的上传(在我的路由器环境php.ini上传限制为100M，但实际有其他未知原因上传限制实际为1024K，导致上传大文件时失败，通过修改get_max_upload函数强制分割800K得以解决)

**Comment by kalcaddle** [comment]
新版本已经优化，敬请期待。
