### ISSUE TITLE
system_{member, group, role}.class.php encoding error?

### ISSUE THREAD

**Issue by D0zingcat** [kalcaddle/KODExplorer#109]
Stated as title, could you please check up the three files under ./controller folder?
No matter what kind of encoding I choosed with notepad++, it still shows up as chaos.

**Comment by kalcaddle** [comment]
The last version has fix it;

**Comment by D0zingcat** [comment]
Still, in the latest version, under "Controller" folder, the 'util.php ' appears the same way like the former three files. :-)

**Comment by kalcaddle** [comment]
Util.php is some compressed data file, there is no need to modify.

**Comment by D0zingcat** [comment]
Fine. I'll check it later😊 Thanks for your intelligent works!
