### ISSUE TITLE
自动更新后，所有文件都显示0B

### ISSUE THREAD

**Issue by magickzl** [kalcaddle/KODExplorer#110]
自动更新后，所有文件都显示0B，无法读取、无法下载、无法创建（显示创建成功，但是winscp查看，没有文件）。

将整个/var/www/kodexplorer目录设置777权限，依然不行。

**Comment by kalcaddle** [comment]
邮件我，发个链接和账户我看看。
kalcaddle#qq.com

**Comment by wdongcom** [comment]
可以升级一下PHP的版本了.
工作环境的php版本慢慢的变高了.kodexeplorer不能用了.

**Comment by kalcaddle** [comment]
测试5.0 到7.1都没任何问题。
所有问题基本上都是环境兼容性造成的，可以邮箱联系我们协助来解决。
