### ISSUE TITLE
Upload not working

### ISSUE THREAD

**Issue by P2T** [kalcaddle/KODExplorer#111]
Upload is returning a 404 error

webuploader-min.js?ver=3.37:2
POST index.php?explorer/fileUpload 404 (Not Found)

**Comment by P2T** [comment]
In fact multiple URL are not working if kodexplorer is not installed at the root.

**Comment by kalcaddle** [comment]
![image](https://cloud.githubusercontent.com/assets/3761968/21715027/168fec1e-d43d-11e6-8b97-428c5c5058b1.png)

We tested a variety of servers and browsers, and did not find what you said.
You can provided Server environment and browser information.
Or contact us with email  kalcaddle@qq.com

**Comment by P2T** [comment]
OK, my explaination is confusing.

I have installed kodexplorer in www/kod
BUT I access it with www.myserver.com/~myaccount/kod/

And when I click on preview or upload
URL are www.myserver.com/kod/ so 404 errors

**Comment by kalcaddle** [comment]
Can you provide a link, and a user, Let me have a try.
contact me with email kalcaddle@qq.com

**Comment by P2T** [comment]
Sorry this server is IP protected by my university.

I reexplain:
I have installed kodexplorer in www/kod BUT I access it with www.myserver.com/~myaccount/kod/

This configuration leads to problem because some of the links in kodexplorer are not relative.

When I select a file and lick on "browser open", then I am redirected on www.myserver.com/kod/ (the ~myaccount is missing)

Same when I use the upload form, it keeps searching in www.myserver.com/kod/index.php?explorer/fileUpload (the ~myaccount is missing)

**Comment by kalcaddle** [comment]
The latest version on github has been adapted for this situation。
You can have a try.


You also can change the file config/config.php
[config/config.php](https://github.com/kalcaddle/KODExplorer/blob/master/config/config.php#L79-L81)
Manually set a more directory, kod access address,and more.
