### ISSUE TITLE
Upload doesn't work with HTTPS

### ISSUE THREAD

**Issue by skygate2012** [kalcaddle/KODExplorer#112]
![1](https://cloud.githubusercontent.com/assets/7148976/21718834/e79e9e4c-d454-11e6-8450-b7e2b754ddbe.png)

**Comment by kalcaddle** [comment]
I did not find what you said.
![image](https://cloud.githubusercontent.com/assets/3761968/21738785/ee9e0c4c-d4c6-11e6-9665-c1f860dc4de1.png)


You can see the source code: [get_host](https://github.com/kalcaddle/KODExplorer/blob/master/lib/function/web.function.php#L37-L50)

Maybe your server has some problem that php did not get the right protocol

**Comment by kalcaddle** [comment]
You can change the host at kod/config/config.php
Line 80~81

define('HOST','https://yourserver.com/');
define('APPHOST','https://yourserver.com/kodpath/'); //kod path

**Comment by skygate2012** [comment]
Thanks, it worked now!
