### ISSUE TITLE
Is this solved

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KODExplorer#113]
Hi, my friend, is the issue at "Cant find the option to disable recycle" solved? Cause it still does not work for me.

**Comment by kalcaddle** [comment]
The option on current user:
setting-->Basic-->Open the Recycle


Default setting all:
kod/config/setting.php: 
"recycle_open"		=> "1",  change to "0"

**Comment by batata004** [comment]
@kalcaddle I already did a clean install of your code, changed recycle_open to 0 and when I delete the file with the "guest" user the file is still being moved to recycle. Could this be a bug?

I am running your code in a CENTOS 7.1 server with APACHE 2.4 and latest version of PHP.

**Comment by kalcaddle** [comment]
The option on current user:
setting-->Basic-->Open the Recycle


kod/config/setting.php: 
"recycle_open"	=> "1", change to "0"
used on create user.

**Comment by batata004** [comment]
WORKED, YOU ARE AWESOME!!!
