### ISSUE TITLE
关于重命名/移动/删除分享文件的问题

### ISSUE THREAD

**Issue by xpader** [kalcaddle/KODExplorer#115]
打个比方：
创建了 a.md 文件
分享 a.md 文件产生分享链接 example.com/share/111
修改/移动/删除 a.md 文件
改名后或移动后的文件分享链接失效了（逻辑上应该还有效）
再在原来的位置创建一个 a.md
通过 example.com/share/111 居然可以访问后来创建的 a.md，但并不是同一个文件

**Comment by kalcaddle** [comment]
是这样设计的，保证了分享链接在文件移除后还可以还原。
