### ISSUE TITLE
共享Markdown文件内部图片取消共享后仍可访问

### ISSUE THREAD

**Issue by xpader** [kalcaddle/KODExplorer#116]
创建一个 markdown 文档并往里面插入一个图片文件后，再取消 markdown 的共享。这时这个图片的URL仍然可以在未登录的情况下访问。

共享 markdown 中的图片或文件的 URL 是否应该有和相应分享的关联，如果对应分享都取消了，相关本身应该也不给予公开访问了。

**Comment by kalcaddle** [comment]
图片获取，都是自动生成的外链。
