### ISSUE TITLE
Warning: fopen

### ISSUE THREAD

**Issue by eArabic** [kalcaddle/KODExplorer#117]
Hello
Thank you very much for this wonderful script
Install it on a particular server, but unfortunately does not work.
Some errors appears, even though I've been giving him full permissions.

![3333](https://cloud.githubusercontent.com/assets/24383546/21955498/6f6da380-da7d-11e6-9f6c-f0ca1dadc9c4.png)

![eee](https://cloud.githubusercontent.com/assets/24383546/21955500/80fdb342-da7d-11e6-9ecb-d8d28172917e.png)

`Warning: fopen(/var/www/html/test/data/system/system_member.php): failed to open stream: Permission denied in /var/www/html/test/lib/class/fileCache.class.php on line 200

Warning: fopen(/var/www/html/test/data/system/system_group.php): failed to open stream: Permission denied in /var/www/html/test/lib/class/fileCache.class.php on line 200

Warning: file_get_contents(/var/www/html/test/data/system/system_setting.php): failed to open stream: No such file or directory in /var/www/html/test/lib/class/fileCache.class.php on line 171
Warning!
"data/" can not write!`

**Comment by kalcaddle** [comment]
chmod -Rf 777 /[kodpath]/*

**Comment by eArabic** [comment]
Thank you very much, the problem is not solved.
Operating system	Fedora Linux 25

![333](https://cloud.githubusercontent.com/assets/24383546/21962050/df353738-db2b-11e6-9358-e95ffaeb909f.png)

![www](https://cloud.githubusercontent.com/assets/24383546/21962051/e47da400-db2b-11e6-8b11-cd43e6edb630.png)


I tried more than one way and did not solve the problem, please help.
