### ISSUE TITLE
centos+Apache2.2+php5.3 中出现多次重定向，最后指向注销操作

### ISSUE THREAD

**Issue by liufind** [kalcaddle/KODExplorer#119]
部署的文件夹和子文件夹，文件权限都是777，访问页面出现重定向次数太多，最后指向注销操作

**Comment by pipilusky** [comment]
我也是相同的问题，求解

**Comment by kalcaddle** [comment]
没遇到过该这个问题，加QQ群：492435993；私聊我看看。

**Comment by kalcaddle** [comment]
将kod目录设置权限为777或755；
chmod -Rf 755 kod目录
