### ISSUE TITLE
zip压缩包解压异常，出现空文件夹

### ISSUE THREAD

**Issue by Sparkinzy** [kalcaddle/KODExplorer#12]
zip压缩包为在windows环境下打包，KODExplorer放置在linux服务器中，字符集的不同导致解压结果仅为一个空压缩包，而不是正常的文件，

**Comment by kalcaddle** [comment]
系统编码和压缩编码不一致导致
这个问题在跨系统之间普遍存在，客户端软件都很难搞定。

**Comment by kalcaddle** [comment]
新版本已经做了自动优化，欢迎体验。
