### ISSUE TITLE
更新后用户不见了

### ISSUE THREAD

**Issue by somehome** [kalcaddle/KODExplorer#121]
本来有70多个用户的，更新后就只剩下10个了。然后我看到所有用户的数据文件都还在，但是system_member.php里面就只有10个用户的信息了。其次有一个member_old.php这样的文件，里面有我之前所有的用户信息。

请问这是更新出的BUG还是程序被黑了？然后我该如何恢复我之前的用户呢？

**Comment by kalcaddle** [comment]
免费版只限10用户，有需要可以购买授权版。
详情见：http://kalcaddle.com/buy.html
