### ISSUE TITLE
搜索文件内容无效

### ISSUE THREAD

**Issue by tianlian0** [kalcaddle/KODExplorer#123]
搜索功能中，勾选“搜索文件内容”以后，什么都搜不到。是我使用方法有问题吗？另：这个搜索文件内容的功能支持哪些文件？

**Comment by kalcaddle** [comment]
只支持文本文件搜索。

支持的格式查看这里  [lib/function/web.function.php#L596-L613](https://github.com/kalcaddle/KODExplorer/blob/master/lib/function/web.function.php#L596-L613)
