### ISSUE TITLE
Serious bug editing files

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KODExplorer#124]
Hi,

I installed kodexplorer in the latest version in my server and now when I try to edit some files (using the builtin code editor) it shows chinese/japanese characters which is nothing related to the file, it's just ASCII chars.

This version is really good but unfortunately this bug prevents me from editing files which is a very importatn feature that I use most of the time.

See image attached.
![bug](https://cloud.githubusercontent.com/assets/8988923/23185503/66d0f0f8-f862-11e6-9499-014ad2f8ac84.jpg)

**Comment by batata004** [comment]
I attached a file so you can downoad it, extract to your computer (file name entrar_contato.php) and upload it to youser server. I had to zip it cause github didnt allow me to upload it.  After that try to edit it with your editor and you will see the problem. Try to edit with notepad/dreamweaver and you will see everything works fine.

Can you tell me if you verify this bug?
[entrar_contato.zip](https://github.com/kalcaddle/KODExplorer/files/791541/entrar_contato.zip)

**Comment by kalcaddle** [comment]
![image](https://cloud.githubusercontent.com/assets/3761968/23198909/99a5136c-f905-11e6-8bdf-4cc6fe5b5c47.png)
maybe the chars needs to mb_detect_encoding have a wrong result;

we will fix it on next version!

**Comment by batata004** [comment]
Thnks man, do you know when the next version will be available? Cause the .34 version was workin fine and in this last version this bug appeared.

**Comment by kalcaddle** [comment]
version 3.38 has fixed this bug.

**Comment by batata004** [comment]
I installed your entire library again in my server, applied all configurations and this bug still happens. Have you tried it? Just install your latest library version 3.38 and try to edit the file I posted you, you will see clearly this bug still happens.
