### ISSUE TITLE
七牛CDN加速配置

### ISSUE THREAD

**Issue by zzvv** [kalcaddle/KODExplorer#127]
RT，在配置七牛CDN加速时需要配置一个静态资源文件测试访问。应用部署在SAE，不知如何操作。

**Comment by zzvv** [comment]
运行环境：php5.3  kod v3.37

**Comment by zzvv** [comment]
找到了，static目录下可以直接打开

**Comment by wdongcom** [comment]
可不可以分享一下你的详细步骤？能将静态文件部署到七牛的话，对于KODexolprer部署在国外服务器上，速度可以提升不少。
哪些文件放到七牛？在kodexplorer怎么修改？

**Comment by kalcaddle** [comment]
将kod/static/ 文件夹迁移到cdn；然后配置 config/config.php

修改配置
```
$config['settings']['static_path'] = "./static/"; 

容改为你的url即可，例如参考demo官网配置：
$GLOBALS['config']['settings']['static_path'] = "//static.kalcaddle.com/kod/static/3.39/";
```
