### ISSUE TITLE
Bug still happens

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KODExplorer#129]
My Friend,

The bug related to https://github.com/kalcaddle/KODExplorer/issues/124 still happens but now at least it looks like the bug happens differently.

Install the latest bersion (.39) and upload the attached file (the one that is inside the zip file or cours). If you open this file now in the editor it will display all the chars correctly! Then try this, after you open the file:

in the second line (or anywhere) type "ááááááá" without quotes. Save. Close the file. Try to open it again. When you open it again, lots of garbage characters will appear.

I really hope I made this clear cause despite the fact that it appears the bug is solved, it's not, it still happens later when you try to add more data to the file.

[entrar_contato (2).zip](https://github.com/kalcaddle/KODExplorer/files/813892/entrar_contato.2.zip)

**Comment by kalcaddle** [comment]
now the version 3.41  has fixed!

**Comment by batata004** [comment]
Great job man, it worked! \o/ You are keeping a really good project here in github, you should share it more so more people would know it... there are TONS of terrible file explorer online and yours is the best one BY FAR.
