### ISSUE TITLE
建议让Adminer记住数据库信息

### ISSUE THREAD

**Issue by wdongcom** [kalcaddle/KODExplorer#131]
Adminer管理数据库很方便，但是每次点开以后都要输入数据库的主机、用户、密码等信息。而这些信息都是空间服务商生产的，不是自定义的，很难记的住。

如果可以让Adminer记住这些信息，或者可以生产一个数据库的登录快捷方式。
这样就很方便了。

**Comment by kalcaddle** [comment]
有这个功能啊！！

勾选记住密码就好了。
