### ISSUE TITLE
https+cdn会导致无法登录

### ISSUE THREAD

**Issue by Dk2048** [kalcaddle/KODExplorer#132]
使用https后修改static路径为cdn地址，这时候引用的官方main.js文件会变成http地址，无法加载
使用本地static目录则不会出现这种情况

**Comment by kalcaddle** [comment]
是支持的，kod升级到最新版

**Comment by Dk2048** [comment]
使用的是3.4.1版本，只要修改static_path为cdn地址就会这样
![ScreenShot_20170308_160127.png](https://ooo.0o0.ooo/2017/03/08/58bfba76d7e7c.png)

**Comment by kalcaddle** [comment]
没遇到你说的情况，参考我们的配置
https://kalcaddle.com/kod/index.php?user/login

**Comment by Dk2048** [comment]
确实很神奇，我把静态文件目录改成 `//static.kalcaddle.com/kod/static/3.41/` 就会调用https的main.js
改成upyun的地址就会调用http的main.js

**Comment by kalcaddle** [comment]
浏览器同源策略
