### ISSUE TITLE
[suggestion]界面翻译的问题

### ISSUE THREAD

**Issue by minimax4233** [kalcaddle/KodExplorer#133]
就是界面的多语言,目测除了只有简中沒有翻译错误之外,其他的翻译都有问题,比如繁体中文.....建议修正一下,比如繁中:"用護名"应该是"用戶名"等等...

**Comment by kalcaddle** [comment]
建议针对你熟悉的语言在config/118n中修正，修复后提pr。
其他大部分语言都是google翻译的，目的就是让大家来修正。我们会第一时间合并。

**Comment by LNDDYL** [comment]
Username繁體譯「使用者名稱」，不譯作「用戶名」。

**Comment by minimax4233** [comment]
用戶名不可以嗎?反正不會是"用護名"

**Comment by LNDDYL** [comment]
@minimax4233 「用戶名」是陸譯，台譯作「使用者名稱」。
