### ISSUE TITLE
BUG still happening

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KODExplorer#134]
Hi my friend,

Unfortunatelly the bug with characters are still happening. I installed your system for the fifth time and it still happens (version x.41). Take for example the file attached. Open the zip file and extract the file bbb.php to your server and try to edit it, lots of garbage characters will appear.

See the image below, the characters are all strange.

![aaa](https://cloud.githubusercontent.com/assets/8988923/23709864/8def9994-03f9-11e7-984d-54d576ba8c05.jpg)

[bbb.zip](https://github.com/kalcaddle/KODExplorer/files/828053/bbb.zip)

**Comment by batata004** [comment]
Just a side note, this bug never happened in older versions, it started happening in the versions after december.

**Comment by kalcaddle** [comment]
It is a php bug.
https://bugs.php.net/bug.php?id=64667

we will fix it on next version.

**Comment by kalcaddle** [comment]
Don't use the 'iso-8859-1', 
Encoding recognition will confuse Unicode and iso-8859-1.

I suggest you use utf-8 charset!

**Comment by kalcaddle** [comment]
see this:
![](https://i.stack.imgur.com/ShQbE.png)
May cause code recognition errors

**Comment by batata004** [comment]
My friend I appreciate your help into this, you are a great man and your explanation was very good!

But at the bottom of https://bugs.php.net/bug.php?id=64667 they say "**_As requinix has explained, this is not a bug._**".

I also understand that ISO is not a good enconding, but I manage a server that has lots of encodings of many users accross the world, so I cant tell everybody to use UTF-8.

I think you should try to solve this problem checking the KODEXPLORER versions of the last year. This problem never never never happened! Never. Sometimes I should just go to config/config.php file and change:

`$config['check_charset'] = 'ASCII,UTF-8,GBK,GB2312,UTF-16,UCS-2,EUC-KR,EUC-JP,SHIFT-JIS,EUCJP-WIN,SJIS-WIN,JIS,LATIN1';`

to

`$config['check_charset'] = 'ISO-8859-1,ASCII,UTF-8,GBK,GB2312,UTF-16,UCS-2,EUC-KR,EUC-JP,SHIFT-JIS,EUCJP-WIN,SJIS-WIN,JIS,LATIN1';`

And everything worked fine, really fine. BUT THIS DOES NOT work anymore!

IMHO you should check what went different from the older versions to the newest and try to fix from there. If you cant do this I would recommend you to check the encoding of the file BEFORE editing and use it to save the file later so you make sure the encoding will be kept the same!
