### ISSUE TITLE
跨磁盘拷贝大文件失败

### ISSUE THREAD

**Issue by unprince** [kalcaddle/KODExplorer#136]
当前CommitID 30fd7db7926d8b32262c77ae77e65c78e8e4a639
将一个磁盘的文件拷贝到另一个磁盘的时候,当文件超过1.4G时一定会出错.暂不能确定是文件超长引起还是超时引起的

**Comment by kalcaddle** [comment]
看一下服务器错误日志吧，一般是由超时引起的。
