### ISSUE TITLE
Open issue

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KODExplorer#137]
My friend,

Could you please open the thread https://github.com/kalcaddle/KODExplorer/issues/134#event-998580828 ?

I think you should check what changed from the early versions of the last year and compare with the newset versions cause this bug that I reported never happened before. I use your editor for long long time and really appreciate your effort into this, this is an amazing library! 

I doubt there is any other good alternative around with so many features as KODEXPLORER! But this bug that I am facing I am really sure many others will face and maybe give up at the first install of your library if they try to edit a file and it gets corrupted!

**Comment by kalcaddle** [comment]
I will fix it on next version.

**Comment by batata004** [comment]
THANKS MAN! I really appreciate your help!
