### ISSUE TITLE
用DaoCloud 免费部署一个

### ISSUE THREAD

**Issue by zhuzhengguang** [kalcaddle/KodExplorer#14]
把该项目fork到你的项目下
在DaoCloud上注册个账号 https://www.daocloud.io/
1.在'代码构建"中新建项目，设置名称，代码源选择你fork的本项目，然后构建，等待成功即可。
2.构建成功后，点击”查看构建好的镜像“，点击部署最新版，等待部署成功
3.部署成功后，你就可以根据提供好的url访问啦。（DaoCloud文档，客服很给力的，不懂的可以随便问，哈哈）
一毛钱不花，弄一个。哈哈哈

**Comment by zzzz438** [comment]
daocloud里面只支持开放1个端口。。。

**Comment by zzzz438** [comment]
离线下载用不了

**Comment by BugByBug** [comment]
但是不支持Volume啊，应用重启东西就会丢失。
But not support the volume, if the app restart the setting and your files are lost.

**Comment by ncitycode** [comment]
@BugByBug  找到支持Volume的办法了吗

**Comment by BugByBug** [comment]
貌似用docker的-v参数就可以
