### ISSUE TITLE
guest无法自动登录问题

### ISSUE THREAD

**Issue by xsjqqq123** [kalcaddle/KODExplorer#141]
下载的是最新3.41版本的，修改config/settings.php里的auto_login为1后，还是会要求登录，哪里还需要改？

**Comment by xsjqqq123** [comment]
好吧，被我发现了，改了data/system/system_settings.php下的的autologin就行了

**Comment by xsjqqq123** [comment]
另一个问题，视频预览，似乎需要下载完全才开始播放，有没有边下边播的方案？特别是mp4，浏览器都支持硬解了，可以直接在线播放的。

**Comment by kalcaddle** [comment]
![image](https://cloud.githubusercontent.com/assets/3761968/24087146/416eed48-0d56-11e7-9c12-74b5e63980cc.png)
视频支持的格式。可以测试官网demo，是支持拖拽播放的。
