### ISSUE TITLE
Windows下目录访问权限控制

### ISSUE THREAD

**Issue by Luluno01** [kalcaddle/KodExplorer#142]
我是小白，没怎么搞过服务器，在自己的笔记本上用WAMP部署了这个repo，运行之后发现可以访问到整个卷的根目录。。。在用户管理里找不到相关选项呢
![image](https://cloud.githubusercontent.com/assets/13421613/24735406/5e8d61d6-1ab5-11e7-9030-f6413b204307.png)

**Comment by kalcaddle** [comment]
设置php防跨站就好了，自行搜索 open_basedir
