### ISSUE TITLE
Wnmp下报fatal error

### ISSUE THREAD

**Issue by Luluno01** [kalcaddle/KodExplorer#143]
今天更新到3.43就报fatal error了，重新下载旧版本运行正常，删除旧版本文件保留data目录，重新解压新版文件，依然报fatal error；尝试移除旧版data目录，重新解压新版文件，还是报fatal error；朋友的服务器上的新版是没问题的，原因不明:(
![01](https://cloud.githubusercontent.com/assets/13421613/24958016/68abec2c-1fc0-11e7-84d2-716dd03875ca.png)

**Comment by Luluno01** [comment]
我是辣鸡，问题太过愚蠢的话还请大佬不要生气 :)

**Comment by kalcaddle** [comment]
再试试最新版呢，不行的话我看一下
发邮件给出以下服务器相关环境。留个qq号
kalcaddle#qq.com

**Comment by kalcaddle** [comment]
3.44已修复，php7兼容性问题造成的.
