### ISSUE TITLE
New error when i am upload 3.44 to 3.45

### ISSUE THREAD

**Issue by simonlkch** [kalcaddle/KodExplorer#145]
i delete the old 3.44 and download the 3.45 in github, reupload to my wdmycloud server
then, here is the error message.

`警告 (Warning!)
您服务器开启了php缓存,文件更新尚未生效;
请关闭缓存，或稍后1分钟刷新页面再试！
了解详情`

anyone meet that issue?

**Comment by Luluno01** [comment]
Just wait for a few minutes. It says that your server has enabled php cache, file update haven't become effective yet.

**Comment by simonlkch** [comment]
after 8 hours, the problem still here, how can i fix this ?

**Comment by Luluno01** [comment]
Then try disabling cache?

**Comment by kalcaddle** [comment]
disabling php cache.

**Comment by simonlkch** [comment]
I don't change and set anything,after 2 days, the application can be used, i think that is my server problem.

**Comment by kalcaddle** [comment]
maybe
