### ISSUE TITLE
共享允许上传的文件夹，设置密码后上传出错

### ISSUE THREAD

**Issue by kmdgeek** [kalcaddle/KodExplorer#147]
目前使用的版本3.46，共享一个文件夹并设置为允许上传，同时设置密码。退出当前用户后，打开共享链接尝试上传，出现如下情况：
在PC端，本地上传正常，但远程下载出错，提示“系统错误”并弹回输入密码界面。
在移动端，本地上传和远程下载都出错，同样提示“系统错误”并弹回输入密码界面。
在Demo站点 http://demo.kalcaddle.com/ 也试了一下，可以稳定复现。

**Comment by kalcaddle** [comment]
ok 下个版本优化一下。
