### ISSUE TITLE
Nginx 无法分发

### ISSUE THREAD

**Issue by a740122** [kalcaddle/KODExplorer#15]
其他PHP 分发都正常，只有芒果云不能用，
Apache 分发正常，但期望的是可以由Nginx 分发，效率也比较高

**Comment by kalcaddle** [comment]
其他php能用？kod不能用，不太明白是什么情况，最好说详细一点。

**Comment by a740122** [comment]
按照这样的设定其他平台的PHP可以正常分发，
以下是nginx 的设定

server {
    listen 8000;
    #server_name ${URL};
    error_log /var/log/nginx/error.log;
    access_log off;
    root /var/www/KODE;

    client_max_body_size 0;
    client_body_buffer_size 128k;

    location / {
        index index.php;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        fastcgi_buffering off;
        fastcgi_read_timeout 600;
        fastcgi_send_timeout 600;
        include fastcgi_params;
         fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}

**Comment by kalcaddle** [comment]
没遇到该情况，明显是服务器配置问题，你访问一个测试php文件看看就知道了
