### ISSUE TITLE
Chunk Upload Error!! 

### ISSUE THREAD

**Issue by Krypt-0** [kalcaddle/KodExplorer#151]
Can't upload anything with the local uploader. 
Remote Uploader is working fine!! 

![ccc](https://cloud.githubusercontent.com/assets/21357601/25766956/8a5cb6da-3217-11e7-8653-51cfdf87b54f.png)

**Comment by Luluno01** [comment]
![image](https://cloud.githubusercontent.com/assets/13421613/26110234/5376c118-3a84-11e7-927d-5721d3907501.png)
Mine is working fine.

**Comment by batata004** [comment]
Mine is working fine too. Any idea of when an update should be expected?
