### ISSUE TITLE
文件编辑后复制到其他地方出现空行

### ISSUE THREAD

**Issue by wbchn** [kalcaddle/KodExplorer#154]
在Linux下使用KodExplorer编辑功能，非常方便，谢谢提供。

最近发现复制到其他地方时（已知的有vi，终端等），每行后面会多出一个空行，需要一行行的删除空行，非常不方便。

举例：
- 在编辑器中
```
        - temperature
        - humidity
        - windDirection
        - windSpeed
        - precipitation
```

- 在vi中粘贴时
```
        - temperature

        - humidity

        - windDirection

        - windSpeed

        - precipitation
```

在用版本3.46，请问是怎么回事？非常感谢。

**Comment by kalcaddle** [comment]
CR, LF, CR/LF 回车 换行的问题
http://blog.csdn.net/wiwipetter/article/details/4970093

**Comment by wbchn** [comment]
@kalcaddle 

这么快关掉，是不是可以理解 kodexplorer 只支持 CRLF，不支持Linux的CR和MAC的LF？

有没有配置可以支持，或是方便说下通过修改哪个源文件做到在Linux／MAC下的友好支持。

**Comment by kalcaddle** [comment]
目前是ace插件默认配置；后面版本我们加一个手动选择。

**Comment by wbchn** [comment]
谢谢，希望KodExplorer做的更好
