### ISSUE TITLE
部署在局域网，视频以及视频里的音频会被压缩

### ISSUE THREAD

**Issue by solidChen** [kalcaddle/KodExplorer#155]
部署在局域网，用作局域网的多媒体管理系统，如何可以使播放的视频不压缩，高清播放，声音也基本无损？

**Comment by kalcaddle** [comment]
上传后默认就是原文件啊。
mp4,webm等html5格式即可在线高清播放。

**Comment by solidChen** [comment]
上传后的文件确实是原文件，可惜双击播放时的图像、声音都是被压缩过的了

**Comment by kalcaddle** [comment]
这不大可能，要做估计是浏览器做了什么处理，
文件是原封不动输出到浏览器的。
