### ISSUE TITLE
每选择一次文件，就出现（复制---覆盖剪贴板成功） 提示。

### ISSUE THREAD

**Issue by Jeffery4000** [kalcaddle/KodExplorer#156]
如题，请问这是什么问题？
只在Chrome上发生，Firefox和IE都完好。

**Comment by Jeffery4000** [comment]
突然没有问题，可现在问题又出现了。

**Comment by kalcaddle** [comment]
键盘事件异常，按下ctrl+c才会调用复制
 (一般远程控制键盘事件会有失常情况)

**Comment by Jeffery4000** [comment]
可是只有在chrome上有这个问题。从开发者工具观察，每一个click都执行了一次pathCopy。
chrome版本 59.0.3071.86（正式版本） （64 位）

**Comment by Jeffery4000** [comment]
感觉是我电脑问题啊，朋友的都没事。谢啦。
