### ISSUE TITLE
编辑器中按钮错位

### ISSUE THREAD

**Issue by xmu714** [kalcaddle/KodExplorer#157]
![image](https://user-images.githubusercontent.com/25820665/26960069-13e9f84a-4d07-11e7-98a8-d898c01c13ed.png)

如图，按钮的位置发生了偏移，并且点击也没有反应。

**Comment by kalcaddle** [comment]
我们没发现这个问题;
提供下所在操作系统，浏览器，浏览器版本；

**Comment by xmu714** [comment]
Windows10 64位
Edge浏览器

**Comment by kalcaddle** [comment]
请先用chrome ；下个版本优化下这个问题。
