### ISSUE TITLE
Environment check:

### ISSUE THREAD

**Issue by kn9** [kalcaddle/KODExplorer#16]
I assigned the right permissions to the folder but I'm still getting the error below
error:
kodexplorer/data/system	can't write
kodexplorer/data/User	can't write
kodexplorer/data/thumb	can't write

Please how  can i resolve the error
Thank you

**Comment by kalcaddle** [comment]
try change   the kodexplorer  to 777;

cd ..../kod
chmod -Rf 777 ./&

**Comment by kn9** [comment]
Thanks.. Working now.  You are the best
