### ISSUE TITLE
树莓派3B下已安装并启用GD库，但仍提示开启GD库

### ISSUE THREAD

**Issue by Luluno01** [kalcaddle/KodExplorer#161]
已经用phpize另外编译了gd库了，在php.ini里也加了extension=gd.so了，仍然提示要开启GD库。Windows下解决此问题是启用gd2扩展，在php7.1.6/ext下只有gd，没有gd2，弱弱地问一下gd目录里是否就是“GD 库”，或者需要另外下载其它的GD库？

**Comment by kalcaddle** [comment]
![image](https://user-images.githubusercontent.com/3761968/27464881-64ee2238-5802-11e7-984c-e0c15bc9ed71.png)
应该没装好，自己看判断吧

**Comment by Luluno01** [comment]
好的，感谢回复！
