### ISSUE TITLE
号称是GPL3开源，可js代码还要压缩混淆过。

### ISSUE THREAD

**Issue by hyhyxu** [kalcaddle/KodExplorer#162]
呵呵

**Comment by kalcaddle** [comment]
首先请仔细阅读什么叫做GPL v3开原协议！！！(是可以商业化运作的)
github上是dist release版本；源码是不能直接运行的，webpack打包。

后端对一两个文件做了加密处理；
都是被逼无奈，已经好多次各种无耻之人改个名字去掉版权就拿去卖。
![111](https://cloud.githubusercontent.com/assets/3761968/26282283/345a7868-3e41-11e7-9dfe-68abc91d1df4.png)

**Comment by hyhyxu** [comment]
1、GPL需要开源代码
无论软件以何种形式发布，都必须同时附上源代码。例如在 Web 上提供下载，就必须在二进制版本（如果有的话）下载的同一个页面，清楚地提供源代码下载的链接。如果以光盘形式发布，就必须同时附上源文件的光盘。开发或维护遵循 GPL 协议开发的软件的公司或个人，可以对使用者收取一定的服务费用。但还是一句老话——必须无偿提供软件的完整源代码，不得将源代码与服务做捆绑或任何变相捆绑销售。https://www.oschina.net/question/12_2826
但在作者的github上没有看到有地方让人下载webpack打包前的代码。
2、我明白作者的苦衷。如果为了赚钱，就不如不开源。如果要开源，不如把可执行的dist版本放在release里。

不是挑刺，与作者共勉。

**Comment by kalcaddle** [comment]
建议去看官方英文定义吧；你贴的是指对继续发行的限制；

产品提供免费使用，并尝试增值功能商业化，和开源基础通用模块代码并不冲突。
处于学习的目的，可以参考之前未压缩的源码（以前的版本；）更多的可以自己去找
https://github.com/kalcaddle/KodExplorer/tree/15fc659d3c7f5be788d8a93a98e7fbcffd32a310/static/js/_dev

**Comment by Jayin** [comment]
人家爱放出来，开源就开源，你不爱用就别用。逼逼什么？

**Comment by hyhyxu** [comment]
@kalcaddle 多谢作者
@Jayin 你又是什么情况
