### ISSUE TITLE
https问题

### ISSUE THREAD

**Issue by Tongzzzzz** [kalcaddle/KodExplorer#169]
https支持的不好，office在https连接中打开失败

![qq 20170703154226](https://user-images.githubusercontent.com/26567782/27782795-84c1270c-6006-11e7-81de-55e0b8acda3e.jpg)

**Comment by kalcaddle** [comment]
这是iframe调用其他应用，第三方API的url问题。
自己去配置config/config.php 对应的OFFICE_SERVER 值

**Comment by Tongzzzzz** [comment]
![qq 20170703161804](https://user-images.githubusercontent.com/26567782/27784085-698d777e-600b-11e7-83ca-6c4cdefe1ad5.jpg)
这样吗？
![qq 20170703161904](https://user-images.githubusercontent.com/26567782/27784091-704d1fce-600b-11e7-9241-5c6ad90b1164.jpg)

**Comment by kalcaddle** [comment]
第三方服务可能不稳定，具体可以参考

**Comment by kalcaddle** [comment]
是的，第三方服务可能不稳定，
具体可以参考：http://kalcaddle.com/office.html

**Comment by Tongzzzzz** [comment]
好的
