### ISSUE TITLE
扩展名限制无法设置不限制任何扩展名

### ISSUE THREAD

**Issue by CodeIgniter** [kalcaddle/KODExplorer#17]
checkExt() 函数加一个判断就可以解决问题。

**Comment by kalcaddle** [comment]
扩展名是跟随用户组权限的，可以进行自定义

系统设置——用户管理——用户组管理——编辑指定组——扩展名限制

**Comment by CodeIgniter** [comment]
这个功能我知道，但是这里有个BUG，如果把“扩展名限制”设置为空字符串就会导致非管理员无法上传任何文件。
代码如下，稍后我提个 pull request 吧。
    $ext_arr = explode('|',$not_allow);
    foreach ($ext_arr as $current) {
        if (stristr($file,'.'.$current)){//含有扩展名
            return 0;
        }
    }

如果 $not_allow 为空字符串的话，$ext_arr 就会为1个元素的数组，所以下面的 foreach 就会导致所有扩展名都返回 0。
