### ISSUE TITLE
下载的问题

### ISSUE THREAD

**Issue by asdf1230** [kalcaddle/KodExplorer#174]
在下载的时候文件名乱码，且获取不到大小信息而下载到一半中断还说下载完成。

**Comment by kalcaddle** [comment]
请把问题描述清楚；给出截图等更详细信息。

通过kod下载一般不会出现什么问题，只要php设置了超时时间不是太短。

远程下载取决于别人的服务器；
大小信息等都在header请求头中，是否下载完也是别人服务器决定的。

**Comment by asdf1230** [comment]
在这里
![screenshot_2017-07-29-20-43-15-856_com android browser](https://user-images.githubusercontent.com/24812116/28744925-c696340e-749e-11e7-9b60-45e1eade4479.png)

**Comment by kalcaddle** [comment]
服务器配置或代理转发问题，header信息有丢失；
管理员登陆kod，系统设置中，关闭csrf保护即可
