### ISSUE TITLE
Deleting a Bookmark will delete the folder and subfolders

### ISSUE THREAD

**Issue by borative** [kalcaddle/KodExplorer#176]
I wanted to remove a bookmark and when I right clicked on the Bookmarks the dropdown showed 'Cancel' and 'Delete'.  Intuition told me Cancel was to disregard the action, and Delete was to remove the bookmark.

Wrong.  I accidentally deleted an entire folder and subfolders with >28,000 files (65GB).  More bad news: they are not in the recycle bin.  I have to spend 2 hours to restore from external backup.  

Aren't bookmarks supposed to be like shortcuts or links? 

I strongly suggest to change the label "Cancel"  to "Remove Bookmark".   "Delete" should check the folder size and number of affected files and give sufficient WARNING that both the bookmark AND folders will be deleted.  

Would be even better if "Delete" is not in included in the Bookmarks menu.  Thanks.

**Comment by kalcaddle** [comment]
Sorry, some translation problems are confusing to you and we will do some optimization.
Shortcuts = Bookmarks


![img](https://user-images.githubusercontent.com/3761968/28750979-66207b08-752e-11e7-9a1f-7a324547d709.png)
