### ISSUE TITLE
font issue

### ISSUE THREAD

**Issue by codeprof2** [kalcaddle/KodExplorer#177]
i am able to use kodexplorer until today. (by the way thnx for that.) 

today when i enter my kodexplorer panel. its look weird.  font size too small to read. first i changed themes. and it didnt solve. then i complete delete and re install. still same. fonts are not readable if you 30dm away from your screeen. do you have any idea ?

editors contents are ok. there is problem with main menus fonts.

**Comment by codeprof2** [comment]
yesterday i installed Helvetica Neue font family to my computer (Windows 10 X64). i guess its caused for that.

**Comment by kalcaddle** [comment]
Miss the fonts
