### ISSUE TITLE
问一下 JS 文件为什么都是压缩过的？可否提供JS源文件？

### ISSUE THREAD

**Issue by CodeIgniter** [kalcaddle/KODExplorer#18]
谢谢

**Comment by kalcaddle** [comment]
鉴于前一段时间，有人直接拿kod改个名字就说是自己的产品，然后还无耻的去卖钱
后续考虑js不提供开发版代码。

**Comment by CodeIgniter** [comment]
这样啊。。。。好吧。。。我直接改的压缩过的代码，美化下也凑合改改，哈哈。
感谢你做了这么好的软件。
