### ISSUE TITLE
使用jade模板引擎报错

### ISSUE THREAD

**Issue by glkhg** [kalcaddle/KodExplorer#181]
在使用jade模板引擎的时候报错，Invalid indentation, you can use tabs or spaces but not both,
我想问一下，KodExplorer是如何处理tab跟space问题的，谢谢。

**Comment by kalcaddle** [comment]
默认不处理的；和源文件一致；
默认采用空格方案；不过可以在右下角选择空格还是tab；也支持一键转换。
