### ISSUE TITLE
Demo user vulnerability

### ISSUE THREAD

**Issue by evezers** [kalcaddle/KodExplorer#187]
By default, on first run KodExplorer creating users, among them user demo/demo with permissions for write on his user folder. I founded many sites with KodExplorer, where it haven't disabled. If in user folder will be uploaded script, it can be loaded by direct link(for example domain.com/kodexplorer/data/User/demo/home/document/script.js). Can you delete this user by default?

**Comment by kalcaddle** [comment]
you  can hide the user realPath

data/User/demo/home/   will be==>data/User/[xxxxxxxxxxx]/home/
