### ISSUE TITLE
Requires to restrict admin user to DATA_PATH folder

### ISSUE THREAD

**Issue by ajazsiddiqui** [kalcaddle/KodExplorer#188]
hii,

software is good, but we need to restrict admin to DATA_PATH folder, because we are not giving root access to any user, we need to give only DATA_PATH as root dir for admin.

please let me know

**Comment by kalcaddle** [comment]
Design is to allow administrators to have all permissions, including modifying the creation of PHP files
Of course, only administrators have this permission, and ordinary users do not have this permission
You can set it by PHP; search for open_basedir
