### ISSUE TITLE
Are you alive my friend? Is an update coming?

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KodExplorer#189]
Are you alive my friend? Is an update coming to solve the charset problem when editing files?

**Comment by dagnelies** [comment]
The problem is in your system/settings, not in this software. There is no such bug. Please refrain from constantly opening new tickets, it's rude and not helpful.

**Comment by batata004** [comment]
This bug never happened in older version of kodexplorer. Only i new version it happens! I didnt change anything in my system, it's exactly the same just the version of kodexplorer. You can clearly reprodue this bug using one of the 5 threads I already explained it.

**Comment by dagnelies** [comment]
Then: 

1. re open the initial thread instead of opening new ones.
2. Specify the exact version where the change occurred
3. Provide full information on your system and settings

Otherwise it's not even possible to "fix" whatever your problem is. For my part, i did not encounter encoding problems, neither on linux, nor on windows.

**Comment by batata004** [comment]
You can see this bug in action here -> https://github.com/kalcaddle/KodExplorer/issues/149

I present many ways you can trigger this bug. No server misconfituration, it's a problem with the library itself

All the 4 times I opened a ticket about this bug the developer confirmed and told me it would fix it in next verion... then in the next version the bug was fixed but in some cases it would still trigger... so this bug was never entirely fixed...

**Comment by kalcaddle** [comment]
try update to 4.05

**Comment by batata004** [comment]
@dagnelies you asked for a complete test, here it comes in the most recent version of kodexplorer -> https://github.com/kalcaddle/KodExplorer/issues/194
