### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by ThejeswarReddy** [kalcaddle/KodExplorer#190]
two hours ago i updated the version and got this error, 

Fatal error: Call to undefined function mtime() in /home/u493366840/public_html/Tj-Pc/config/config.php on line 62

**Comment by kalcaddle** [comment]
Maybe miss some files.
mtime is defined in 'common.function.php'    config/config.php line 57 ==> line 89

**Comment by ThejeswarReddy** [comment]
Okay, can you tell me what am i supposed to do now?

**Comment by kalcaddle** [comment]
Download the update archive 
http://static.kalcaddle.com/update/update/2.0-4.03.zip

unzip to your kod path.
