### ISSUE TITLE
升级了v4.03，发现了几个小问题……

### ISSUE THREAD

**Issue by mengkunsoft** [kalcaddle/KodExplorer#191]
1、打开 adminer 报错
(见截图 https://ws1.sinaimg.cn/large/a15b4afegy1fiuiqfxozgj20v603yjrd.jpg )

2、无法启用插件
点击启用插件，程序提示启用成功，但是实际上未成功。

3、桌面上的时钟插件点击最大化后无法还原、点击最小化无反应。

4、因为多说关闭了，点击软件关于界面的“问题反馈”无法进行反馈了……

5、建议给个  开启\关闭  图片略缩图功能（或者是在列表模式下不显示略缩图。。）因为打开含有很多图片的文件夹时会搞得服务器撑不住……

6、其它的都非常棒！感谢作者开发这么好用的工具 :smile: 

服务器环境：
Windows Server 2012 R2 Datacenter x86 + IIS + php 5.4

补充：
7、程序系统设置里的“使用帮助”和“关于作品”内容显示排版错乱

**Comment by kalcaddle** [comment]
感谢反馈
最新版4.05修复了相关问题
