### ISSUE TITLE
升级4版本后出现了几个问题

### ISSUE THREAD

**Issue by NciYuan-Net** [kalcaddle/KodExplorer#192]
服务器环境Debian8 with Apache2.4.10 and php5.6.30
安装就提示kodexplorer/data/session/不可写，于是将整个文件夹用chown变为www-data（执行用户），并且把权限由chmod整体777，创建session文件夹后仍有提示， 并且原来的没有，接着忽略，注册后变成了可道云.资源管理器，很ex有木有。接着登录提示
/var/www/（kodexplorer安装目录）/data/目录不可写,请将该目录及所有子目录设置为可读写后再试！，
可是这时整个文件夹都是777且为www-data的，无法进入，同样的问题在3.x就没有

**Comment by kalcaddle** [comment]
最新版4.05修复了相关问题

**Comment by NciYuan-Net** [comment]
@kalcaddle  没有解决问题，包括GitHub和OSChina的两个版本，地址https://explorer.nciyuan.net 也是4.05版本，仍旧提示session问题，同时GitHub的latest release 3.4.6可以使用

**Comment by NciYuan-Net** [comment]
说缺失的session文件夹仍不存在，官网的版本也没有，创建后还是不行

**Comment by kalcaddle** [comment]
服务器的一个兼容性问题。
一个测试没遇到过的服务器环境；下个版本修复这个问题，这两天会针对近期的问题做修复优化后再发一个稳定版

**Comment by NciYuan-Net** [comment]
@kalcaddle 问题还是没有解决，详情还是我那个网站
首先我用的环境不是宝塔面板，AMH面板，OneInStack，军哥LNMP那种一键软件包，系统是腾讯云提供的Debian 8.2 x64的镜像，不用问具体反正都是一个镜像啊，我用的是apt源直接安装Apache2.4.10+PHP5.6.30的，3.46版本一直用，看到4.1版本出来了，想看看有没有修复bug，接着删除原来的3.46，从官方网站下载的4.1版本包，首先检测是通过的，输入密码，登录界面也没有提示session不可写，而是提示整个data不可写，此时该目录和下属及所有文件均是www-data以及0777的，网址相同

**Comment by NciYuan-Net** [comment]
补充一下，在输入admin用户密码的阶段，是检测通过的，然后到了登录界面是提示data不可写，但是data存在，同时session也存在，还有如果输入错误的用户名密码，仍然会提示用户名或密码错误(不是数据目录不能写吗？)，最后是进不去的。同时默认的test/test和demo/demo也进不去

**Comment by kalcaddle** [comment]
你该不会直接用用更新包当程序吧。

提示data不可写，确定就是 对应php的  is_writeable 函数，说明确实就不可写，自己检查一下吧。
还有问题加qq群5，私聊群主给一个网址和账号测试一下。

**Comment by kalcaddle** [comment]
可能你服务器不支持指定session目录，具体的加群私聊我看一下吧。
