### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by ThejeswarReddy** [kalcaddle/KodExplorer#193]
please bring the tabbed file explorer  like clover explorer for the desktop or like chrome tabs instead of opening a new tab each time we open my computer

**Comment by ThejeswarReddy** [comment]
i don't see my computer shortcut on the desktop, removed it in updated versions ? why? please bring it back..

**Comment by kalcaddle** [comment]
It might have been deleted by mistake, you can restore it manually

https://github.com/kalcaddle/KodExplorer/blob/master/data/system/desktop_app.php
make file to data/system/desktop_app.php
