### ISSUE TITLE
Bug with text encoding inside editor

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KodExplorer#194]
My dear friend,

Again this bug is happening and now I will provide you the full descriptive way so you can reproduce it on your end and check it.

1) Download the ziped file attached. Inside this file there is a file named "criacao-site.php". I am hosting this file in my webserver at https://www.quemfazsite.com.br/temp/criacao-site.php but you dont need to open it cause it's a PHP file BUT I am trying to edit exactly this file in this exactly server where all libraries are updated.
[criacao-site.zip](https://github.com/kalcaddle/KodExplorer/files/1253841/criacao-site.zip)

2) Extract the .php file in your server. Install KODEXPLORER in the latest version and try to edit the file using the really nice file editor that you provide with your library;

3) When you open the file you will see this:

![image](https://user-images.githubusercontent.com/8988923/29743470-5664ccd2-8a69-11e7-97a6-f19ec950663f.png)

4) If you open the file in your local machine (using Dreamweaver or ANY text editor) you will see this:

![image](https://user-images.githubusercontent.com/8988923/29743476-750c0ba0-8a69-11e7-84f4-aa72aa236a2c.png)

5) If you compare both screenshots you will realize that some characters at the beginning (close to the red arrow) are lost in the kodexplorer file editor.

Ok, this is how you can reproduce this bug. BUT I will go further. Inside the file editor click in the COG item (in the menu bar) -> TOOLS -> FILE ENCODING ->ISO-8859-1. This is exactly the encoding being used in this file (it's the very common WESTERN EUROPEAN used A LOT here in ocident).

If you do this the characters will STILL be corrupted. So clearly there is a problem here, even setting the exactly right encoding, the file editor still messes with the character map.

If I was not clear enough I can certainly allow you access to my server so you can test this use case. But I think it's very easy to reproduce on your end.

**Comment by kalcaddle** [comment]
You need to know is that the encoding identification is not entirely possible. 
Because the precise identification such as iso8859 windows-1252 and GBK encoding region are overlapping, this kind of recognition, others will inevitably lead to the error code, so you can not distinguish between the encoding of the file;

I find your file is windows-1252, but the system identification is iso8859-1;
Why???   the content of your file overlaps in the two coding regions, meaning that the computer doesn't know what the encoding is.

This time you need to manually select what the file is encoded.

### It is recommended that you unify the UTF-8 encoding!!

![5b199699-17d2-4313-9a23-5fd468805067](https://user-images.githubusercontent.com/3761968/29774766-51e2a652-8c35-11e7-8b28-2ac6aea02f26.png)

**Comment by batata004** [comment]
@kalcaddle I had no idea windows was using CP1252 cause dreamweaver and notepad++ told me I was using iso8859-1.

INDEED, when I selected CP1252 encoding in your encoding menu EVERYTHING WORKED JUST FINE!!!! Thanks my dear friend!!!

So my question is this: how do I make kodexplorer always open/save by default using this CP1252 encoding instead of trying to (badly) guess which encoding it's?

I use UTF8 for most of my projects but I use kodexplorer in some systems where there are very ancient files and I cant touch their encoding.

**Comment by batata004** [comment]
One more consideration: is it possible for you to add a WARNING at the top of the file the user is editing if SOME/ANY character was not found in the charset map? I mean, probably PHP has a function to tell you if a file is displaying all characters ok so if one single char is not ok you display the WARNING telling the user to try another different encoding!

**Comment by kalcaddle** [comment]
[charset.zip](https://github.com/kalcaddle/KodExplorer/files/1256934/charset.zip)


You can test these files, and almost no editor, even local software, can identify all of these problems correctly.
So the best solution is to use UTF-8 encoding

**Comment by kalcaddle** [comment]
please convert the file to utf-8

**Comment by batata004** [comment]
Yeap, I will my friend. But I edited my last post. Why

`$config['checkCharset'] = 'ASCII,UTF-8,GB2312,GB`

Is not working?

**Comment by batata004** [comment]
I tried adding CP1252 to the checkCharset but it does not work, it still uses western european as default ;(

**Comment by kalcaddle** [comment]
The system does not know that the encoding of the detection is wrong, so there is no warning.

please convert the file to utf-8
1.  Tools=>File encoding=> windows-1252(or others)
2.  Tools=>Save the file encoding as => utf8 

Then you open the file, everything is  ok.

**Comment by batata004** [comment]
If I do what you say the file is ok BUT when I try to access my system using it's URL it gets all corrupted cause the system gets the file and expect it charset to be ISO, but it's UTF8 instead (which is a multibyte charset and makes things a lot more complicated).

So it's not just simple as changing the charset of my file, ok, I can change the charset BUT I have hundreds of other files that INCLUDE (using include("file.php")) in their projects and they expect this file to be in ISO.

Anyway, why does your config file has a checkCharset variable and it gets no use? I mean, I tried changing that variable inserting CP1252 in front of it but nothing changes.
