### ISSUE TITLE
static.kalcaddle.com证书错误

### ISSUE THREAD

**Issue by Luluno01** [kalcaddle/KodExplorer#197]
使用Chrome访问[https://static.kalcaddle.com](https://static.kalcaddle.com)发生证书错误，证书来自`*.oss.aliyuncs.com`而不是`*.kalcaddle.com`，导致请求[https://static.kalcaddle.com/update...](https://static.kalcaddle.com/update/main4.js?tid=uuid_1504076236_5356?ver=4.05)的时候发生`net::ERR_INSECURE_RESPONSE`错误

**Comment by kalcaddle** [comment]
更新域名了，证书还没生效，这两天生效。
