### ISSUE TITLE
Bug when loading text encoding

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KodExplorer#200]
Hi,

I tried changing the config.php file to set a default encoding that kodexplorer should use when it opens a file in the file editor but it does not look to work.

You can reproduce this bug easily: set your desired encoding at the very beginning of the string in the config.php file. Even setting your default encoding there kodexplorer will not honor that.

**Comment by batata004** [comment]
I am debugging some files and I think I should change something in editor.class.php probably in this line:

	```
	if ($charset !='' &&
			$charset !='utf-8' &&
			function_exists("mb_convert_encoding")
			){
			$fileContents = @mb_convert_encoding($fileContents,'utf-8',$charset);
		}
```

But I have no idea how to add my chart set there cp 1252

**Comment by batata004** [comment]
I just tried the code below, it looks kodexplorer is reading the file differently but still some characters are missing:

	```
	if ($charset !='' &&
			$charset !='utf-8' &&
			function_exists("mb_convert_encoding")
			){
			$fileContents = @mb_convert_encoding($fileContents,'cp1252',$charset);
		}
```

**Comment by batata004** [comment]
I dont know it this helps you to convert CP1252 -> https://stackoverflow.com/questions/22683132/php-cp1252-windows-1252-conversion-to-utf-8

**Comment by kalcaddle** [comment]
Repeat:  this not kodexplorer's bug,

There are some coding areas that are basically overlapping, 
and the system can't tell what charset it is

### Please use utf-8!!!!

charset get at:
https://github.com/kalcaddle/KodExplorer/blob/master/app/function/helper.function.php#L119-L172
