### ISSUE TITLE
Bug when loading a text encoding

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KodExplorer#202]
My friend I understand whawt you said!

I REALLY DO!

I DONT WANT KODXPORER TO GUESS WHAT CHARSET IS BEING USED!!!

**I DONT WANT kodexplorer to guess!!!!**

I want it to simply load a file assuming a default charset that I can set!!!

WHEN I select TOOLS -> TEXT ENCODING and select CP1252 IT WORKS PERFECTLY! 

PERFECTLY!!!

I JUST WANT KODEXPLORER to stop guessing what charset the file has, I want it to load all the files with a default charset that I specify inside config.php!!!

THAT'S ALL MY FRIEND!!!

I think this is a good feature, why cant the user set a default charset if he believes kodxplorer is doing a poor job choosing the right one?

**Comment by kalcaddle** [comment]
charset get at:
https://github.com/kalcaddle/KodExplorer/blob/master/app/function/helper.function.php#L119-L172

you can change it  by yourself
```
function get_charset(&$str) {
return 'CP1252';//or others.
}
```

**Comment by batata004** [comment]
WOW!!! IT WORKED PERFETCTLY!!!!! REALLY NICE!!!!

Anyway, I see there is this line:

`$charset=strtolower(@mb_detect_encoding($str,$GLOBALS['config']['checkCharset']));`

It should be using the charsets I said in the config.php file right? Why even setting the correct charset at config.php file it does not work?
