### ISSUE TITLE
Enhancement: how to fix mb_detect_encoding

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KodExplorer#203]
Hi,

I finally came up with a "solution" to the bug related to CP1252 charset. I discovered this charset is wider than iso-8859-1 so instead of applying your fix of:

`return 'CP1252';`

I decided to go to the line 

`$charset=strtolower(@mb_detect_encoding($str,$GLOBALS['config']['checkCharset']));`

and change it to:

`
	$charset=strtolower(@mb_detect_encoding($str,$GLOBALS['config']['checkCharset']));
	
	if ($charset == "iso-8859-1") {
	 
	 $charset = "Windows-1252";
	    
	}
`

This allows me to keep editing UTF-8 files being automatically detected by mb_detect_encoding AND allow me to edit CP1252 files when their charset is wider than iso88591.

I think this problem relates to a bug inside mb_detect_encoding cause if CP1252 is used FIRST in the array of encoding it should first match this encoding but it does not!

I also discovered that if you override mb_detect_string with the function below it WORKS PERFECTLY!!! So maybe you should override the mb_detect_encoding with the code below which does not produce the bug that the original function makes happen!

```
function mb_detect_encoding ($string, $enc=null, $ret=null) {
    
    static $enclist = array( 
        'Windows-1251', 'Windows-1252', 'Windows-1254', 
        'UTF-8', 'ASCII', 
        'ISO-8859-1', 'ISO-8859-2', 'ISO-8859-3', 'ISO-8859-4', 'ISO-8859-5', 
        'ISO-8859-6', 'ISO-8859-7', 'ISO-8859-8', 'ISO-8859-9', 'ISO-8859-10', 
        'ISO-8859-13', 'ISO-8859-14', 'ISO-8859-15', 'ISO-8859-16', 
        );
    
    $result = false; 
    
    foreach ($enclist as $item) { 
        $sample = iconv($item, $item, $string); 
        if (md5($sample) == md5($string)) { 
            if ($ret === NULL) { $result = $item; } else { $result = true; } 
            break; 
        }
    }

	return $result;
    
} 
```

Anyway, at least now I know how to solve this prolbem and still use kodexplorer!

**Comment by kalcaddle** [comment]
Good job.

You can modify the code by yourself and make sure that it works properly in your environment.
But you judge this way in China, Japan, South Korea and other circumstances will be very bad, and lead to a variety of garbled.This one ensures that most of the cases are normal, and the remaining ones are not recognized. You need to manually select the encoding.



**Of course, it is recommended to use utf8, global general, bid farewell to all garbled questions**

**Comment by batata004** [comment]
Thanks my friend!
