### ISSUE TITLE
是否有考虑接入外部存储网站

### ISSUE THREAD

**Issue by ferocknew** [kalcaddle/KodExplorer#204]
是否可以考虑接入：
- 七牛存储
- 又拍存储
- 阿里云 oos 存储
- 或者支持 webDAV

**Comment by kalcaddle** [comment]
这些都在开发计划中，第三方存储开放会集成多家。
计划在年底这些功能都会加入

**Comment by emresaracoglu** [comment]
These features will be added at the end of the year?

**Comment by emresaracoglu** [comment]
@kalcaddle  These features will be added at the end of the year?
