### ISSUE TITLE
官网里非常有情怀的一段话

### ISSUE THREAD

**Issue by jdz321** [kalcaddle/KodExplorer#207]
https://kodcloud.com/about.html
我记得这个页面上，以前以一段关于一个技术的历史使命的话，情怀满满，现在找不到了，能分享下吗

**Comment by U2FsdGVkX1** [comment]
不是官方，只不过找到了

“这是一个互联网的时代，信息化正侵袭各行各业，接下来人类开始真正步入大繁荣的时代，如同《黑客帝国》那般，世界创造了我们，我们又创造了另一个世界，换一种介质让信息更高度的流通，智慧本身朝着一个完美的方向演化，然后我们退出游戏。如若 失控，也算是自己的命运吧。
这个世界，没有永恒的东西，没有什么东西是一成不变的，唯一永恒的就是这种变化。
如果技术，或者某个作品也有生命有情感的话。那么，我们会更好的理解他们存在的意义与价值。产品，总是伴随着需求的诞生而诞生，随着科技进步需求不再而消亡。
而技术，是随着产品的细节，或优化，或使之易用性，开发成本等等的提高而一代代的变革。如果产品算是一个完整的个体的话，那么技术就是一个个可以复用的思维零件。正因为各种技术、设计思想、算法的存在，而使得产品的个体一个个茁壮成长，在他有限的生命周期里，发挥最大的价值。

每个作品都会有自己的命运。或经久不衰，或英年早逝。
不管他陪伴过你多少个孤独的日日夜夜。时代的变迁，科技的进步。当人们已经用不到他的时候，那么我们要做的只能是最后的留念。作为产品或者技术本身，要做的或许就是“放下吧”……把下一代，交给正在成长的那些‘人’吧！敬畏这种豁达。献一句悼词：它轻轻地走了，真如其轻轻地走了，不带走一滴眼泪。但是，它改变了世界，人类进程中，因为有了它而才有现在这个阶段的美好……
永远朝前看，接受新的事物，相信这一点，总是没错的。”

**Comment by alice-00** [comment]
你好，有前端负责人的岗位想推荐给你，方便加个微信吗？微信号：15889628159
