### ISSUE TITLE
Remote Downloads issue

### ISSUE THREAD

**Issue by ThejeswarReddy** [kalcaddle/KodExplorer#208]
I can't download files from google drive remotely but when i paste the URL in browser address bar file gets downloaded automatically 

example link: - https://drive.google.com/uc?export=download&id=0B6CfIQYe5o2oQmFXLXhXRjI1VU0

**Comment by kalcaddle** [comment]
Our test is good, but the file name is the parameter after URL
There may be some problems with your server accessing the Google network

filename:uc?export=download&id=0B6CfIQYe5o2oQmFXLXhXRjI1VU0

17.2M (18005473 Byte)
MD5:6a8ae3cfa7668cd6d2876858f797f6b9
