### ISSUE TITLE
网站的静态资源，如果想走 cdn ，是否有可以配置的位置，暂时看了源码没有找到

### ISSUE THREAD

**Issue by ferocknew** [kalcaddle/KodExplorer#209]
如题

**Comment by kalcaddle** [comment]
config/setting.php
$config['settings'] 等配置都是可以自行修改的
cdn配置：staticPath 可以修改为态资源的cdn地址(路径对应到kod一致的static_path)；


可在setting_user.php中添加变量覆盖,升级后不会被替换
例如，参考官网demo的cdn配置
$GLOBALS['config']['settings']['staticPath'] = "//static.kodcloud.com/kod/static/4.1/";
