### ISSUE TITLE
#208 Remote downloads issue

### ISSUE THREAD

**Issue by ThejeswarReddy** [kalcaddle/KodExplorer#211]
I know but the original file is not 

filename:uc?export=download&id=0B6CfIQYe5o2oQmFXLXhXRjI1VU0
17.2M (18005473 Byte)

but is a Zip file Containing Mp3 Tracks, even i'm able to download same above to server but i can't unzip or use it as i would do to computer downloads

but if i download with the browser with google drive link, file is getting download to computer as zip file and i'm able to play tracks after unzip.

**Comment by ThejeswarReddy** [comment]
Okay i figured out what's wrong you may please close the issue

Solution :- file is getting download but our extractor can't unzip because it is failing to identify the file type , so to solve this we must **Rename** the file to yourdesiredfilename.zip and then extract it

So,
filename: uc?export=download&id=0B6CfIQYe5o2oQmFXLXhXRjI1VU0  

rename this to

yourdesiredfilename.zip and then extract it

normally github files are getting downloaded as zip files directly, but google drive zip files are downloading with link name to make them work we must rename it to **yourdesiredname.zip**  


Thanks

**Comment by kalcaddle** [comment]
The download link header does not provide the download file name, so the default is obtained from the URL
