### ISSUE TITLE
联网更新就明明白白清清楚楚地写出来，这样干算什么

### ISSUE THREAD

**Issue by africamonkey** [kalcaddle/KodExplorer#213]
在KodExplorer/static/js/app/src/app/main.js （还有其他名为main.js的文件，此处不一一列举）中：
第2行
update:function(){setTimeout(function(){var e=base64Decode("Ly9zdGF0aWMua2FsY2FkZGxlLmNvbS91cGRhdGUvbWFpbi5qcw==")+"?a="+UUID();require.async(e,function(e){try{e.todo("check")}catch(t){}})},200)}

我们把该字符串进行base64解码，可以得到字符串
//static.kalcaddle.com/update/main.js
显然这是调用了外部Javascript，意在控制整个更新服务。但是为什么不能把URL显式地写出来呢，非要用base64加密一下？

**Comment by mengkunsoft** [comment]
66666，“藏”这么深的“秘密”居然也能被发现 😄 
其实只要按 F12 打开浏览器的网络监听就能找到这个 js 的加载了

**Comment by africamonkey** [comment]
@mengkunsoft 事实上，我就是发现了它加载了这个js才反过来查它的代码的。

**Comment by kalcaddle** [comment]
主要是防盗版。
之前有几家盗版厂商改个名字，然后把自动更新删掉，就说是自己的产品，还挂在淘宝上售卖。

**Comment by africamonkey** [comment]
我理解了你们的用意，谢谢你的解释！
