### ISSUE TITLE
linux 访问所有目录

### ISSUE THREAD

**Issue by puregardenia** [kalcaddle/KodExplorer#214]
有什么办法可以让管理员访问 linux下的所有目录吗？

现在管理员只能访问到 kodExplorer 程序目录，其他的目录都无法访问，请问在不更改所有目录的权限情况下，有什么办法可以访问到所有目录吗？ @kalcaddle

**Comment by kalcaddle** [comment]
首先设置关闭防跨站  open_basedir;
然后需要读写权限的对应在系统中修改文件夹权限就好了

**Comment by puregardenia** [comment]
Thinks！问题解决了，由于我用的是 linux 一键安装的集成开发环境，为了安全，默认在 `fastcgi.conf` 加了限制 `fastcgi_param PHP_ADMIN_VALUE "open_basedir=$document_root/:/tmp/:/proc/";`。
解决办法： 在里面加上`:/` 重启 nginx 服务就行了
