### ISSUE TITLE
Please add feature: Online HTML Editor

### ISSUE THREAD

**Issue by eArabic** [kalcaddle/KodExplorer#215]
Hello
Thank you very much for the very excellent script
Please add feature: Online HTML Editor
Such a site: https://html-online.com/
https://htmlg.com/html-editor/
http://htmleditor.tools/
 HTML WYSIWYG editor program allows you edit your source code online
It is very useful in editing the page directly without codes.

This site is another idea: https://htmleditor.io/

![default](https://user-images.githubusercontent.com/24383546/30772019-ba9a19b0-a05c-11e7-87d7-ae2572f2cb58.png)

![1](https://user-images.githubusercontent.com/24383546/30772206-90c008fe-a05f-11e7-839a-f79191c795b2.png)

**Comment by kalcaddle** [comment]
We will add a plugin to do this.

**Comment by jorrit** [comment]
Has this plugin been added?

**Comment by kalcaddle** [comment]
We will provide this plugin around June, 
and you can also develop your own plug-in based on ckeditor or tinymce.

**Comment by kalcaddle** [comment]
Our friend did an html editing plugin and you can use it,
Download and unzip it to plugins/.

Download address: http://simon511000.fr/KodExplorer-master/index.php?share/file&user=1&sid=pMg72h3T

**Comment by maplewang** [comment]
where to download it, can not reach the page.

**Comment by simon511000** [comment]
Yea, I changed web host and I no longer have the plugin.

**Comment by flappysquirrel** [comment]
Is this the one?

 https://www.youtube.com/watch?v=ojDlzmTujuQ

[TinyMCEditor.zip](https://github.com/kalcaddle/KodExplorer/files/2517147/TinyMCEditor.zip)

**Comment by simon511000** [comment]
lol, you managed to find my own plugin that I thought I had lost

**Comment by simon511000** [comment]
wait, I'll update it to put a better editor than tinymce.

**Comment by simon511000** [comment]
Hey! Delete the old plugin and put my new plugin: https://github.com/simon511000/wysiwyg-plugin-for-kod/ @flappysquirrel @maplewang @eArabic @jorrit
