### ISSUE TITLE
下载速度为什么不能达到满速？

### ISSUE THREAD

**Issue by xy9860** [kalcaddle/KodExplorer#216]
我通过域名+绝对路径下载有1.22M/s左右的下载速度，但是通过下载功能下载只有400KB，这是什么原因呢？有办法减弱或者避免这种问题吗？而且下载的时候无法看到文件大小（chrome浏览器）

**Comment by kalcaddle** [comment]
http://bbs.kodcloud.com/thread-81-1-1.html
论坛里已经做了说明；

**Comment by kalcaddle** [comment]
具体加官方QQ群5，私聊群主。
提供一下服务器环境；
我们测试了linux windows下  php+linux，php+nginx 下载速度都是相差不大的。
