### ISSUE TITLE
KodExplorer的用户文件安全问题

### ISSUE THREAD

**Issue by Coolkids** [kalcaddle/KodExplorer#218]
重现方法 admin账户举例
1.在home目录中上传一个test.html的文件
2.然后退出登录
3.在浏览器中输入 你的网址/data/User/admin/home/test.html 可以直接访问到文件直接绕过登录
PS:url规则(你的网址/data/User/你的用户名/文件夹名/文件名.html)

也就是说文件存储的data文件夹对任何人开放,而且没有任何登录验证,所以说任何人都可以通过这个规则过来抓取你的文件.
如果你对/data 路径禁止访问,那么文件预览功能就彻底没用了.

将data 移动到非web目录解决

**Comment by NciYuan-Net** [comment]
怎么说你好呢，您理解并明白chmod -R 777 KodExplorer的意思吗？

**Comment by NciYuan-Net** [comment]
还有guest和test用户

**Comment by Coolkids** [comment]
你是开发者么? 你懂我说的意思么?
您理解并明白chmod -R 777 KodExplorer的意思吗？

**Comment by NciYuan-Net** [comment]
如果你觉得很不爽可以设置0700啊，我不是开发者

**Comment by Coolkids** [comment]
那我跟说这个没意义  
你理解文件所属用户么? 你700有什么用 这跟你系统的文件权限有什么关系
你的kod登录用户又不是系统用户 你无论用什么用户登录都是你php运行的用户 so 你700跟777没任何区别
其他任何人 知道你部署了kod都可以过来绕过登录抓你的文件

**Comment by NciYuan-Net** [comment]
你是说kod的Data目录下的东西？

**Comment by Coolkids** [comment]
对啊 我不说他说什么

**Comment by NciYuan-Net** [comment]
比如Apache的DirectoryMatch之类的不行吗

**Comment by Coolkids** [comment]
没用 文件预览直接用不了了 他文件预览就是直接调用URL来实现的  这个项目作为企业使用会有严重安全问题

**Comment by NciYuan-Net** [comment]
那您觉得allow from localhost
allow from 127.0.0.1 
allow from 172.*.*.*
allow from xxxxx
这种规则不能设置一下吗

**Comment by Coolkids** [comment]
首先 你请求的话. 你的IP不是固定的. 限制来源,不如在代码上对data路径里面的静态资源加过滤器来的方便.

**Comment by kalcaddle** [comment]
1. 安装时时强制提醒关闭列目录的，比如说demo用户放了一个私密文件，想下载？除了瞎猜遍历还有什么办法.匿名的路径、文件名基本保障了文件的一定安全性
2. 配置文件明确说明了，担心安全可以将data目录迁移到web目录之外。
3.可以通过服务器配置，防止直接http请求data目录之下的文件.

**Comment by andyhuai** [comment]
@kalcaddle 
你好，我用的群晖，请问一下，如何将data目录迁移到www目录之外呢？
主要是因为我要同步功能来同步data的文件，而在www目录下是无法使用群晖的同步进行同步的
非常感谢

**Comment by andyhuai** [comment]
@kalcaddle 
我将 DATA_PATH设置为`/volume2/KodExplorer/data/`这个目录，提示找不到
在admin账户下，已经可以对该目录进行读写了
![7673aaec09f830fc9b53940fa3937533](https://user-images.githubusercontent.com/16273717/44778466-9ad3d300-abaf-11e8-837b-dd47272ba2ae.jpg)

**Comment by andyhuai** [comment]
`<?php define('DATA_PATH','/volume2/KodData/data/');`
我刚刚重新试了一下，居然可以了，下午改了一堆的权限，估计权限对上了

**Comment by andyhuai** [comment]
另外问一下，群晖的版本为什么使用的是php5而不是php7？
