### ISSUE TITLE
上传大文件上传一段时间失败

### ISSUE THREAD

**Issue by huangguanwen** [kalcaddle/KODExplorer#22]
我上传一个10+m的视频，上传到一部分后就直接提示上传失败了！！

**Comment by kalcaddle** [comment]
设置php.ini  上传大小限制

**Comment by huangguanwen** [comment]
已经设置了100M的限制了。
情况是这样的,文件上传时有反应，但上传到大概70%后，进度条又归0，然后进度又重新走了，但之后就直接提示上传失败了！

**Comment by kalcaddle** [comment]
环境问题，懂代码的话，可以看看浏览器错误日志。
nginx  也会对post做长度限制。

**Comment by huangguanwen** [comment]
已经解决了，的确是nginx的问题！非常感谢！
