### ISSUE TITLE
FTP and WebDAV Connection

### ISSUE THREAD

**Issue by emresaracoglu** [kalcaddle/KodExplorer#223]
Hello

KodExplorer is great project! I want to ask a question.
Can I connect to remote FTP and WebDAV with KodExploerer ?

**Comment by kalcaddle** [comment]
https://github.com/kalcaddle/KodExplorer/issues/204


comming soon.

**Comment by emresaracoglu** [comment]
@kalcaddle These features will be added at the end of the year?

**Comment by kalcaddle** [comment]
Yes.
