### ISSUE TITLE
It does not open compressed files

### ISSUE THREAD

**Issue by eArabic** [kalcaddle/KodExplorer#224]
Hello
After the update, there was a problem
It does not open compressed files.
It does not preview the php page

![44](https://user-images.githubusercontent.com/24383546/31347314-9d3a0414-ad24-11e7-88a0-52707aebec03.png)
![222](https://user-images.githubusercontent.com/24383546/31347313-9d35d7a4-ad24-11e7-8637-8cf190fd61e4.png)

**Comment by kalcaddle** [comment]
Areadly fixd on 4.24. 
You can update online.
