### ISSUE TITLE
支持浏览器“前进／后退”

### ISSUE THREAD

**Issue by 4Oranges** [kalcaddle/KodExplorer#227]
目前在文件管理界面上的“前进／后退”与浏览器行为不一致。
KodExplorer绑定了常见的前进、后退快捷键，在直接触发“前进／后退”操作的场景会引发问题。比如：
- 使用带有前进、后退按键的鼠标
- 使用触摸板手势

另外，绑定backspace作为返回快捷键，并非平台通用。在macOS上，backspace的行为应为delete，而不是返回。

建议修改

**Comment by NciYuan-Net** [comment]
那么ajax还有什么意义吗

**Comment by 4Oranges** [comment]
@NciYuan-Net 这可以是纯前端实现的功能，跟是不是ajax没有关系

**Comment by kalcaddle** [comment]
大部分快捷键是按全键盘设定的。后面优化一下笔记本对应的功能映射

**Comment by 4Oranges** [comment]
@kalcaddle 我认为这个功能交给浏览器实现比较好。一次修改处处OK。自己造这么大一个轮子怎么做都会有没适配的场景。
