### ISSUE TITLE
提供一个官方的Docker镜像吧

### ISSUE THREAD

**Issue by xaljer** [kalcaddle/KodExplorer#228]
Docker hub 上的镜像似乎不太更新

**Comment by kalcaddle** [comment]
老的也可以的，安装后可以在线升级即可。很方便的

**Comment by dhso** [comment]
`docker run -d \
--name kodexplorer \
--restart=always \
-p 10800:80 \
-v <kodexplorer dir>:/var/www/html \
dhso/kodexplorer:latest`

目前是4.40版本
