### ISSUE TITLE
Getting POPUP's

### ISSUE THREAD

**Issue by ThejeswarReddy** [kalcaddle/KodExplorer#229]
Hello,

from yesterday i'm getting these POPUP's. are these from you or my app is hacked?

![kalcod](https://user-images.githubusercontent.com/29545146/32643228-f4b7a856-c5ff-11e7-83e2-1174057762f0.JPG)

and taking me to the below link after clicking.

https://h5.weidian.com/m/groupon/detail/index.html?spider=wv6a7i.sxrbnzah.product.ddetail&spiderv=unknown&itemId=2195673919

**Comment by kalcaddle** [comment]
Sorry, this is a discount purchase reminder from our official.
2017.11.11 Celebrate the Double XI promotion (like Black friday). you can closed it.
