### ISSUE TITLE
Open With MPV

### ISSUE THREAD

**Issue by Answer-Man** [kalcaddle/KodExplorer#232]
I've seen that you've implemented opening files with VLC, I would like to see the same feature for MPV and other players that could be called locally. 
Instead of directly downloading the file just make it launch a locally installed player by pushing to it the URL of the video/audio.

**Comment by kalcaddle** [comment]
This requires other software to support object, such as flash

```
<object classid= "clsid:F08DF954-8592-11D1-B16A-00C0F0283628""
Width= "100" height= "50" >...</object>
```

Of course, you can also refer to VLC plugin, to achieve their own local software quick call.
/plugins/plugin/VLCPlayer
