### ISSUE TITLE
Identically named images are not displayed/cached properly

### ISSUE THREAD

**Issue by davidleejy** [kalcaddle/KodExplorer#233]
Create 2 different images with identical name.
/path_1/to/image/cat.png
/path_2/to/image/cat.png
Open path_1 image in Explorer.
Navigate to path_2's image. Opening it shows path_1's image.

**Comment by kalcaddle** [comment]
Thanks to feedback, 
the next version (3.45) will solve this problem

**Comment by davidleejy** [comment]
Thanks for fast reply @kalcaddle . But 3.45 is old version that was released 13 April.

**Comment by kalcaddle** [comment]
sorry,next version is 4.25
