### ISSUE TITLE
406 Error on a shared server

### ISSUE THREAD

**Issue by TricksfortheWeb** [kalcaddle/KodExplorer#234]
I am running KodExplorer on a shared Linux server hosted by Godaddy. I can open files just fine, but whenever I try to save them, I get a 406 file:

> Not Acceptable
> An appropriate representation of the requested resource /files/index.php could not be found on this server.
> 
> Additionally, a 406 Not Acceptable error was encountered while trying to use an ErrorDocument to handle the request.

Why is this happening?

**Update**: I think the problem is caused by large files.
**Update 2**: This doesn't happen on a localhost.

**Comment by kalcaddle** [comment]
Your web server configuration problems, check mime related configuration

https://msdn.microsoft.com/en-us/library/bb742440.aspx?f=255&MSPPError=-2147217396

**Comment by TricksfortheWeb** [comment]
I'm not using IIS, it's a Linux server.

**Comment by kalcaddle** [comment]
google the http code: 406.

**Comment by TricksfortheWeb** [comment]
Like I haven't tried that ten times already. I found nothing that will help me. Since you (presumably) are familiar with this program, I thought you might be able to at least figure out why it isn't working.

**Comment by kalcaddle** [comment]
We have never encountered this situation, 
but we can determine the problem lies in the web server.

**Comment by TricksfortheWeb** [comment]
This isn't the only program the problem occurs on, I've also had the same issue with FileRun. Clearly there problem is with the server, but how do I fix it?
