### ISSUE TITLE
Failed to select Multiple items in mobile browser 

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [kalcaddle/KodExplorer#236]
You can get ideas from here. 
https://github.com/Studio-42/elFinder/issues/1373

**Comment by kalcaddle** [comment]
We will add this feature in the follow-up, of course, you can also develop plug-in to achieve.

**Comment by nagulan51** [comment]
I have also the same problem , in my case I have deactivate an plugin from google chrome , all work fine (plugin : POSTMAN) . I think this plugin same JavaScript variable , that why the reason !

**Comment by kalcaddle** [comment]
we areadly support the App;  both iOS and Andrioid.
you can have a try.  search  可道云  or  kodcloud
