### ISSUE TITLE
出现网络连接错误 (net::ERR_CONNECTION_RESET)

### ISSUE THREAD

**Issue by laolai** [kalcaddle/KodExplorer#237]
刚安装好的时候能好好的用，过了两天就出现网络连接错误 (net::ERR_CONNECTION_RESET)这个错误，进入某些目录的时候

**Comment by kalcaddle** [comment]
出现这个是网络中断导致的，就是说请求后服务器返回数据到客户端过程中，网络某个地方进行了拦截。
和kod、web服务器都没有关系。

很大可能是防火墙做了误判拦截(可能是针对什么关键词)
