### ISSUE TITLE
Feature: Program expiry dates for download links

### ISSUE THREAD

**Issue by Answer-Man** [kalcaddle/KodExplorer#238]
Can you add an configurable expiry date for download links ? Or set a limited number of downloads for that specific link.

**Comment by kalcaddle** [comment]
![image](https://user-images.githubusercontent.com/3761968/33812526-047c52b6-de59-11e7-8a88-d0785800cb8c.png)

**Comment by Answer-Man** [comment]
Using the latest version of KodExplorer v4.25. Same thing happens using your demo.
![pop](https://puu.sh/yE27D/800c85d6b8.png)

**Comment by kalcaddle** [comment]
![image](https://user-images.githubusercontent.com/3761968/33866108-c69a99da-df2f-11e7-9ea2-36beee3faad5.png)

We test are normal, you may have to modify the css style, or shield some adBlocks interface elements.

**Comment by Answer-Man** [comment]
uBlock was blocking it. 
Thank you it works now, but is not possible to implement it for public paths as well ?
