### ISSUE TITLE
file permission for non-suphp server

### ISSUE THREAD

**Issue by GaneshKandu** [kalcaddle/KodExplorer#239]
Hi,

i am getting file permission issue in installation of KodExplorer

* **app**
* **app/update.php**
* **data/\***

currently i am using this is it fine ?

**Comment by GaneshKandu** [comment]
License url is giving 404 error
[http://kodcloud.com/tools/licenses/license.txt](http://kodcloud.com/tools/licenses/license.txt)

**Comment by kalcaddle** [comment]
chmod -Rf 777 your_kod

**Comment by GaneshKandu** [comment]
i don't want to give recursive permission
because i on shared hosting
setting the permissions for that directory to 777 is insanely insecure

**Comment by kalcaddle** [comment]
or 755;  the permission used on application update.

**Comment by GaneshKandu** [comment]
i will update manual by overriding files
