### ISSUE TITLE
Unreadable shared text file on certain themes

### ISSUE THREAD

**Issue by Answer-Man** [kalcaddle/KodExplorer#240]
Is it possible de make the color of the text change with the chosen theme, or at least make color changes apply on .txt files ?
![img](https://puu.sh/yFtRX/74f843619d.png)

**Comment by kalcaddle** [comment]
we will change it on next version.

**Comment by kalcaddle** [comment]
now you can add css on 
setting=>System=>others=>Customize global css:


```
.share-page-main .show-code{border:1px solid rgba(100,100,100,0.2);background: rgba(255,255,255,0.9);border-radius: 2px;}
.share-page-main .show-code pre{color:#fff;}
```
