### ISSUE TITLE
Need Terminal

### ISSUE THREAD

**Issue by sobujbd** [kalcaddle/KodExplorer#243]

**Comment by kalcaddle** [comment]
you can install such as  
gotty https://github.com/yudai/gotty
wetty https://github.com/krishnasrinivas/wetty

...
based on https://github.com/xtermjs/xterm.js

**Comment by sobujbd** [comment]
How do add any of these on Context Menu?

**Comment by kalcaddle** [comment]
http://doc.kodcloud.com/#/plugins-main

**Comment by sobujbd** [comment]
Which `type` of `configItem` I need for put terminal window link in Context Menu?
