### ISSUE TITLE
Hide hidden file/folder on Linux

### ISSUE THREAD

**Issue by jinyu121** [kalcaddle/KodExplorer#245]
How to hide hidden file/folder on Linux server?

I noticed that there is "Directory exclusion" in control panel, and I add ".*" in it, nothing help.

So, can you add something like "show/hide hidden file/folder" both for Linux and Windows?

THX

**Comment by kalcaddle** [comment]
Temporarily does not support the wild way to hide files, currently only supports full file name hiding; for example:   .git

**Comment by gorkijatt** [comment]
please add this feature

![Screen Shot 2020-08-10 at 1 01 35 AM](https://user-images.githubusercontent.com/19510688/89740343-62301a00-daa5-11ea-896c-d263562db072.png)
