### ISSUE TITLE
建议在编辑器点关闭窗口时提示是否保存框

### ISSUE THREAD

**Issue by HanadaLee** [kalcaddle/KodExplorer#248]
一般情况下绝大部分编辑器都会在你关闭时提醒你是否要保存（实时保存的那些除外），但是KoDexplorer似乎时直接关闭的，对于一些习惯以关闭作为保存的用户来说有时候是灭顶之灾（用词有点过，不过确实自己辛辛苦苦打了吗么多字/代码）结果自己一个关闭就什么都没了心情肯定非常差）

**Comment by kalcaddle** [comment]
关闭浏览器标签，我们是做过相关处理的；
关闭对话框由于没有系统事件支持，暂时没做处理。后面版本考虑优化。
