### ISSUE TITLE
文件内搜索工具时在数据量大时崩溃

### ISSUE THREAD

**Issue by NciYuan-Net** [kalcaddle/KodExplorer#249]
数据有多大呢？大概就是Discuz X3.2的sources文件夹那么大吧
希望可以改进搜索方式，或者分步，或者直接提示不行
PHP和Apache并没有duang
并且键盘绑定的Kod框架下的刷新没用，浏览器地址栏的东西来刷新才有效
顺便说仍在走搜索动画，但是搜索已经停止
see [![2018-01-12 (1).png](https://i.loli.net/2018/01/12/5a58bd02b196f.png)](https://i.loli.net/2018/01/12/5a58bd02b196f.png)

**Comment by NciYuan-Net** [comment]
作者是忙于考试吗。。。

**Comment by NciYuan-Net** [comment]
好像要多等很长一段时间了

**Comment by kalcaddle** [comment]
json数据格式编码问题引起的。建议修改系统编码为utf8

**Comment by NciYuan-Net** [comment]
就是UTF8，php.ini定义的，还有这个问题在数据量小的时候没问题，同一个目录也是偶尔出现，执行时间不是很长，没有超出PHP最大执行时间

**Comment by kalcaddle** [comment]
原因是搜索结果中含有乱码字符。导致前端json解析时出错。
程序对中文支持是比较完善的，linux、win下都做过自动识别并转换。我们这边没遇到过这种情况。

加QQ群或右键发个访问地址和账号，我们测试调试看一下。
