### ISSUE TITLE
打开个别PDF文件的时候崩溃

### ISSUE THREAD

**Issue by xaljer** [kalcaddle/KodExplorer#250]
![image](https://user-images.githubusercontent.com/8309631/34970139-949a50c6-faad-11e7-92b9-f2f8929c23fb.png)
直接在线预览个别PDF文件的时候会崩溃，如上图。
选择在浏览器中打开正常。

**Comment by xaljer** [comment]
浏览器是Vivaldi，使用pdf.js插件。在Edge中正常。

**Comment by kalcaddle** [comment]
提交文件看看，反馈到pdf.js的issue.
https://github.com/mozilla/pdf.js
