### ISSUE TITLE
Files Sorting Problem

### ISSUE THREAD

**Issue by HanadaLee** [kalcaddle/KodExplorer#251]
在选定排序方式为名称的情况下，一个文件夹里有52个命名为01-52的文件夹，但是31接下来却是50，51，52，然后才继续32。希望能修正这个问题 | 在选定排序方式为名称的情况下，一个文件夹里有52个命名为01-52的文件夹，但是31往后却是50-52，然后才继续接着32。
该问题仅在桌面端出现，移动端排序正常，已在你们的demo中测试复现。
给50、51、52文件夹更名为50[排序]、51[排序]、52[排序]后，排序恢复正常。

**Comment by kalcaddle** [comment]
ok，文件名自然排序算法需要优化，下个版本会优化。

**Comment by kalcaddle** [comment]
感谢反馈，是一个排序bug.
github上已修复;下个版本会加入
https://github.com/kalcaddle/KodExplorer/blob/master/static/js/lib/util.js#L655-L658
