### ISSUE TITLE
某著名违法公司的统计代码可能会影响内置文本编辑器的启动

### ISSUE THREAD

**Issue by NciYuan-Net** [kalcaddle/KodExplorer#254]
当然是Google Analytics啦，亲测不加一切正常，加了之后，由文件打开编辑器时，编辑器加载条无限滚动，然后状态一直是peding www.google-analytics.com 中，所以建议编辑器就不用统计了或者异步加载
这时文件的内容已经加载出来，代码已经着色，旁边的函数列表也加载出来了，一般解决是关掉框架重开，并且一般即使正常的情况下这是内容都有了，等1-3秒才会让加载条消失 还有加载条存在时数据不能编辑

**Comment by kalcaddle** [comment]
我们没测试出来，给个网址和账号测试一下。
邮箱发到 kodcloud@qq.com

**Comment by NciYuan-Net** [comment]
已发

**Comment by kalcaddle** [comment]
测试出来了，部分页面请求时，会直接发送阻塞页面的统计代码，导致页面加载一直在等待中。
简单解决方法是将统计代码延迟执行一下即可：

```
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-111723103-1');

改为:

setTimeout(function(){
	window.dataLayer = window.dataLayer || [];
	function gtag(){dataLayer.push(arguments);}
	gtag('js', new Date());
	gtag('config', 'UA-111723103-1');
},500);

```

**Comment by kalcaddle** [comment]
具体的新版优化一下加载中的loading蒙层
