### ISSUE TITLE
Issue in updating files and can't start the music player

### ISSUE THREAD

**Issue by hdp2101** [kalcaddle/KodExplorer#255]
Hello

      This is to kindly inform you that i can't update .txt , .docx , .xlsx files to my document folder, and while updating those files i received the message "Network or firewall" and rest other file like .pdf , .exe , .php files i can update without errors.
  
      Also when i update mp3 files, my mp3 files update successfully, but while playing this mp3 files when i double click on the file, it start the player, but can't play the file.  

Thank you
Hemal Parikh

**Comment by kalcaddle** [comment]
You can install it on your computer for testing.
The problem is not caused by Kodexplorer.
Maybe your server firewall or anti-virus software made a related interception.
