### ISSUE TITLE
[Error Code:1010] FileCache load error!/var/www/html/data/system/system_setting.php

### ISSUE THREAD

**Issue by ptflp** [kalcaddle/KodExplorer#257]
every time when try to install, or it says js文件不完整,请查看浏览器控制台和服务器配置是否正常。或检查文件是否被修改(或咨询主机商压缩js导致文件损坏);[js load error!] running localy

**Comment by carukc** [comment]
I am also seeing this problem.  Were you able to solve?

I am running from a Synology.  Perhaps it is a problem with the web server settings?

Thanks
Chris

**Comment by kalcaddle** [comment]
Your web server maybe have some problem. you can see the browser console find the reason.
you can try to install on your local computer!


----

403 (Forbidden) .
maybe you should setting the kodexplorer permission to 777.
