### ISSUE TITLE
Cannot access http://demo.kodcloud.com/

### ISSUE THREAD

**Issue by lostinroom** [kalcaddle/KodExplorer#260]
警告 (Warning!)
服务器session写入失败! (session write error)
请检查php.ini相关配置,查看磁盘是否已满,或咨询服务商。

session.save_path=
session.save_handler=files

**Comment by kalcaddle** [comment]
服务器磁盘满了，已处理。

**Comment by lostinroom** [comment]
cool. now can access it. Thanks for quick action and response.
