### ISSUE TITLE
rar无法解压

### ISSUE THREAD

**Issue by zouyujia** [kalcaddle/KodExplorer#265]
你好，我的机器是centos6使用lnmp一键安装包，php版本7.2.4，好像rar无法解压，zip解压是正常的，http错误日志：sh: /home/wwwroot/yun.zyj8.cn/app/kod/archiveLib/bin/rar: cannot execute binary file

**Comment by kalcaddle** [comment]
rar调用的是一个可执行文件。


报错cannot execute binary file，检查如下：
1、查看当前用户是否有可执行权限
2、ls -l 查看文件是否具有可执行权限
3、要使用对应的64位/32位安装包。
