### ISSUE TITLE
Problem with the music player

### ISSUE THREAD

**Issue by simon511000** [kalcaddle/KodExplorer#268]
Hello,
It's normal that when I click on a music, others musics are not in the queue ?
![capture du 2018-04-20 07-50-37](https://user-images.githubusercontent.com/31013205/39033309-b4ff2ad6-4471-11e8-95f7-c74d93129704.png)

**Comment by simon511000** [comment]
Ok,
On windows, when I click on a music, the music that is on the same folder is automatically played after. Like this :
![5d1c7a30-103b-4430-b2e5-d04c0f2517f1](https://user-images.githubusercontent.com/31013205/39036656-7612baba-447e-11e8-83c9-a2b34b1792b2.jpeg)

**Comment by simon511000** [comment]
like the readme.md
![4b46fc9c-1b58-47af-926d-bd79f8ae2c00](https://user-images.githubusercontent.com/31013205/39037124-d29a196c-447f-11e8-853b-9c5119200e02.png)

**Comment by kalcaddle** [comment]
If it is convenient, please provide a kodaddress and test account,
send to kalcaddle@qq.com; we test it.

**Comment by simon511000** [comment]
> you can try the demo: http://demo.kodcloud.com/
we can't find this problem.

the problem is that even on your demo the problem persists.

**Comment by simon511000** [comment]
On Mozilla Firefox, ubuntu : 
![image](https://user-images.githubusercontent.com/31013205/39046660-3d21504a-4497-11e8-83bf-c9a6f87429da.jpg)

**Comment by simon511000** [comment]
Thank you very much for your patience 😀
I'll do tests to see what's wrong

**Comment by simon511000** [comment]
I do not understand...
To make it work, double-click it?

**Comment by kalcaddle** [comment]
double-click a file, it will be append to the player list auto.
you can try it on chrome.
