### ISSUE TITLE
publish my plugin

### ISSUE THREAD

**Issue by simon511000** [kalcaddle/KodExplorer#271]
Hello, I created a plugin and I want to publish it so that the community can install it. How to do ?
![043142e6-538b-4dcb-8ef9-c5f6a4a7e9b4](https://user-images.githubusercontent.com/31013205/40013276-679548c6-57ad-11e8-9361-62dd4eb6a8e6.jpeg)

_The answer may be on the doc but I can not read Chinese._

**Comment by kalcaddle** [comment]
Great job. you can submit it to our email: kalcaddle@qq.com

**Comment by simon511000** [comment]
Sent !
