### ISSUE TITLE
Reseting current state upon switching "Explorer" to "Desktop"

### ISSUE THREAD

**Issue by mkilicar** [kalcaddle/KodExplorer#276]
I'm not sure whether this is designed by that or a bug.
When I was listening to music, or a document is opened, I switched to Explorer-> Desktop, everything is reseting (music stops)

Is there anyway to keep the current apps open? and login from a different computer continue where it left from?

Thanks,

**Comment by kalcaddle** [comment]
This is normal because the page is refreshed when you switch to the desktop.
