### ISSUE TITLE
Bug in editor

### ISSUE THREAD

**Issue by simon511000** [kalcaddle/KodExplorer#279]
Hello, I have a bug with the editor : 
When I click on the preview button, it's the function list that open 
https://youtu.be/zbZ6rUKw3Lg

**Comment by kalcaddle** [comment]
version ?

**Comment by simon511000** [comment]
last (4.31). This bug only work here : index.php?editor

**Comment by kalcaddle** [comment]
version 4.32  fixed !

**Comment by simon511000** [comment]
Yes, Tank you very much !!
