### ISSUE TITLE
1GB file upload error

### ISSUE THREAD

**Issue by excitedcat** [kalcaddle/KodExplorer#285]
Error Tip: There is not enough space left

Disk space usage:

```
/dev/sda1        10G  4.8G  5.3G  48% /
/dev/sdb1       9.8G  481M  8.8G   6% /srv/web
/dev/sdb2       9.8G  590M  8.7G   7% /srv/data
```

/srv/data has enough space left

nginx config:

```
client_max_body_size 2048m;
```

php config:

```
upload_max_filesize = 2048M
```

**Comment by kalcaddle** [comment]
There is not enough space left.

check it.

**Comment by kalcaddle** [comment]
![image](https://user-images.githubusercontent.com/3761968/42980677-01b82f36-8c0b-11e8-8aa5-8fbd125fa954.png)

**Comment by excitedcat** [comment]
I'm a free edition user, there is no "Space Size" option in this panel. 
Does this feature not support free users? @kalcaddle
