### ISSUE TITLE
[feature] Hidden file

### ISSUE THREAD

**Issue by excitedcat** [kalcaddle/KodExplorer#286]
KodExplorer can add a switch to hide the hidden files.

![image](https://user-images.githubusercontent.com/8253512/42981731-3e9fc102-8c10-11e8-995a-1f2d71e47a85.png)

**Comment by kalcaddle** [comment]
![image](https://user-images.githubusercontent.com/3761968/42985578-a993448e-8c24-11e8-83e9-3853fb06fe7a.png)
