### ISSUE TITLE
windows环境目录排除问题

### ISSUE THREAD

**Issue by mushroom1113** [kalcaddle/KODExplorer#29]
windows环境目录排除不了，或者是我的设置方式不对，文件管理中怎么不显示工程以外目录（如C:\windows等）。不知道需要KODExplorer设置还是Apache服务器设置，以前没用过Apache服务器。希望给个windows环境下详细点的目录排除方法，谢谢！

**Comment by kalcaddle** [comment]
目录排除是指  排除指定目录名或文件名的显示。
比如说排除thumb.db的显示；并不是指排除某个目录

**Comment by mushroom1113** [comment]
我再详细看看，3Q
