### ISSUE TITLE
Extremely Insecure

### ISSUE THREAD

**Issue by therealngaforce** [kalcaddle/KodExplorer#298]
This is a great web IDE and file manager. I would use it much more if it was secure. The problem with everything is literally all I have to do is type in the home directory of the user in my browser and the directories list. You can also do this if you are not logged in.

My poor solution to at least secure it, but it includes sacrifices:
I configured the .htaccess to 403 all requests in the directory where the data is stored. Although whenever I am trying to view a file in the explorer itself it gets 403ed. The only thing it allows me to do is edit the file in one of the included text editors.

**Comment by kalcaddle** [comment]
You can change the data path out of the web root;

![image](https://user-images.githubusercontent.com/3761968/45608896-e29b9b00-ba87-11e8-988a-b04119d7ae83.png)


/*
  * Can be a data directory; moving outside the web directory can make the program more secure, without limiting the user's extension permissions;
  * 1. You need to move the data folder to somewhere else. For example, copy the data folder to D:/
  * 2. Add a new line <?php define('DATA_PATH','D:/data/') in the new define.php in the config folder.
  * Note: The path cannot be written incorrectly; secondly, php needs to have permission to access the moved directory (the anti-cross-site needs to be closed)
  */
