### ISSUE TITLE
什么时候支持FTP用户登录啊

### ISSUE THREAD

**Issue by wineynet** [kalcaddle/KODExplorer#30]
什么时候支持FTP用户登录啊，就像net2ftp一样的那种。linux服务器不好弄

**Comment by kalcaddle** [comment]
暂不支持，需要的话可以试试  eXtplorer

**Comment by wineynet** [comment]
真心希望以后能添加ftp登陆的功能。

**Comment by kalcaddle** [comment]
精力有限，有兴趣可以加入一起开发这部分。提交代码即可，我们合并到主分支。
