### ISSUE TITLE
My plugin did not appear in the list of plugins

### ISSUE THREAD

**Issue by simon511000** [kalcaddle/KodExplorer#304]
I have a php script ([this](https://gist.github.com/simon511000/201661ab553d715b364d91a78a02f191)) that returns this:
`{"data":[{"id":"WysiwygEditor","name":"WysiwygEditor","title":"Editeur WYSIWYG","version":"1","category":"file","source":{"screenshoot":["https:\/\/autre.simon511000.fr\/kod\/data\/User\/admin\/home\/desktop\/kodapi\/v2\/plugins\/unzip\/WysiwygEditor\/static\/images\/screenshoot1.png","https:\/\/autre.simon511000.fr\/kod\/data\/User\/admin\/home\/desktop\/kodapi\/v2\/plugins\/unzip\/WysiwygEditor\/static\/images\/screenshoot2.png"],"className":"x-item-file x-dwg","icon":"https:\/\/autre.simon511000.fr\/kod\/data\/User\/admin\/home\/desktop\/kodapi\/v2\/plugins\/unzip\/WysiwygEditor\/static\/images\/icon.png"},"description":"Ce plugin ajoute un \u00e9diteur WYSIWYG.","keywords":"wysiwyg,editor","auther":{"copyright":"simon511000","homePage":"https:\/\/simon511000.fr"},"configItem":{"plugins":{"type":"tags","display":"Plugins","value":"picture,link,video,table,undo,redo,help","desc":"Plugins de l'\u00e9diteur Plus d'info<\/a>."},"fileExt":{"type":"tags","display":"{{LNG.Plugin.Config.fileExt}}","desc":"{{LNG.Plugin.Config.fileExtDesc}}","value":"wysiwyg"},"fileSort":{"type":"number","display":"{{LNG.Plugin.Config.fileSort}}","desc":"{{LNG.Plugin.Config.fileSortDesc}}","value":"500"}},"formStyle":{"loadFile":["https:\/\/autre.simon511000.fr\/kod\/data\/User\/admin\/home\/desktop\/kodapi\/v2\/plugins\/unzip\/WysiwygEditor\/static\/main.js"]},"server":{"version":"1.0","versionTime":"2018\/10\/9","network":1,"downloadCount":0,"commentCount":0,"userScore":0,"sort":0,"size":4352}}],"code":true,"use_time":0.0013480186462402344}`

And I have set the "pluginServer" in the file config/setting.php.
However, the plugin did not appear in the list of plugins. Why ?

**Comment by kalcaddle** [comment]
You must put the WysiwygEditor plugin into /plugins.
and has a class WysiwygEditorPlugin

**Comment by simon511000** [comment]
Thank you @kalcaddle but It's not a package.json, it's a api : 
```
{
   "data":[
      {
         "id":"WysiwygEditor",
         "name":"WysiwygEditor",
         "title":"Editeur WYSIWYG",
         "version":"1",
         "category":"file",
         "source":{
            "screenshoot":[
               "https:\/\/autre.simon511000.fr\/kod\/data\/User\/admin\/home\/desktop\/kodapi\/v2\/plugins\/unzip\/WysiwygEditor\/static\/images\/screenshoot1.png",
               "https:\/\/autre.simon511000.fr\/kod\/data\/User\/admin\/home\/desktop\/kodapi\/v2\/plugins\/unzip\/WysiwygEditor\/static\/images\/screenshoot2.png"
            ],
            "className":"x-item-file x-dwg",
            "icon":"https:\/\/autre.simon511000.fr\/kod\/data\/User\/admin\/home\/desktop\/kodapi\/v2\/plugins\/unzip\/WysiwygEditor\/static\/images\/icon.png"
         },
         "description":"Ce plugin ajoute un \u00e9diteur WYSIWYG.",
         "keywords":"wysiwyg,editor",
         "auther":{
            "copyright":"simon511000",
            "homePage":"https:\/\/simon511000.fr"
         },
         "configItem":{
            "plugins":{
               "type":"tags",
               "display":"Plugins",
               "value":"picture,link,video,table,undo,redo,help",
               "desc":"Plugins de l'\u00e9diteur Plus d'info<\/a>."
            },
            "fileExt":{
               "type":"tags",
               "display":"{{LNG.Plugin.Config.fileExt}}",
               "desc":"{{LNG.Plugin.Config.fileExtDesc}}",
               "value":"wysiwyg"
            },
            "fileSort":{
               "type":"number",
               "display":"{{LNG.Plugin.Config.fileSort}}",
               "desc":"{{LNG.Plugin.Config.fileSortDesc}}",
               "value":"500"
            }
         },
         "formStyle":{
            "loadFile":[
               "https:\/\/autre.simon511000.fr\/kod\/data\/User\/admin\/home\/desktop\/kodapi\/v2\/plugins\/unzip\/WysiwygEditor\/static\/main.js"
            ]
         },
         "server":{
            "version":"1.0",
            "versionTime":"2018\/10\/9",
            "network":1,
            "downloadCount":0,
            "commentCount":0,
            "userScore":0,
            "sort":0,
            "size":4352
         }
      }
   ],
   "code":true,
   "use_time":0.0013480186462402344
}
```
