### ISSUE TITLE
Security breach that allows anyone to download anything

### ISSUE THREAD

**Issue by Ayrler** [kalcaddle/KodExplorer#306]
It appears that by using this link `https://example.com/data/User/` anyone can access all the available resources hosted on KodExplorer.

**How to reproduce:**
_KodExplorer version: 4.36_
Place a file anywhere in KodExplorer and access it using the directory path. 
E.g: `https://example.com/data/User/admin/home/desktop/file.txt`.
This bypasses the necessity to login to download files (works on both shared and non-shared files).

**Comment by kalcaddle** [comment]
https://github.com/kalcaddle/KodExplorer/issues/218
