### ISSUE TITLE
403 error on save

### ISSUE THREAD

**Issue by Simon666R** [kalcaddle/KodExplorer#309]
KodExplorer is the best software for editing a site online. But I have a problem with some PHP files giving me a 403 error when I save.

It is only a few PHP files that give errors when I save but they seem the same as the ones with no errors.

Any ideas?

![403](https://user-images.githubusercontent.com/45098745/48622706-b48cf580-e9fb-11e8-8ba3-7b7d96dddd84.png)

**Comment by kalcaddle** [comment]
please check your server.
(chrome -> console)
