### ISSUE TITLE
上传文件的临时文件如何删除？

### ISSUE THREAD

**Issue by oDaShuTz** [kalcaddle/KodExplorer#311]
我的vps有25G的 SSD，但是上传大概19G就已经写满了，可能是因为上传文件的临时文件造成的吗？e.g:我的vps除了XAMPP和KodExplorer没有安装任何东西.
如果是，请告诉我如何删除这些临时文件。

**Comment by kalcaddle** [comment]
![image](https://user-images.githubusercontent.com/3761968/49434321-e6b99800-f7ee-11e8-8816-bcb6a5a00d75.png)
或者手动删除data/temp 文件夹
