### ISSUE TITLE
Dplay无法加载字幕

### ISSUE THREAD

**Issue by hvnhv** [kalcaddle/KodExplorer#312]
播放MP4文件无法加载vtt字幕文件。已经改为视频文件同名且设置自动加载字幕。本地Potplay播放正常。kodexplorer版本4.37

**Comment by kalcaddle** [comment]
注意字母文件名
![image](https://user-images.githubusercontent.com/3761968/49434195-993d2b00-f7ee-11e8-831b-142760c6715b.png)

**Comment by kalcaddle** [comment]
详情可以在官网demo进行测试；
https://demo.kodcloud.com/?share/folder&user=1&sid=D8kPXrAE
