### ISSUE TITLE
enable chrome web browser

### ISSUE THREAD

**Issue by 0xjohn** [kalcaddle/KodExplorer#315]
How can I enable web browser in KodExplorer?
as I see in your screenshots you have chrome icon on your desktop but I don't have it and didn't find anyway to enable web browser in KodExplorer, please advice.

Thanks

**Comment by simon511000** [comment]
Hey @0xjohn !
There is no web browser in KodExplorer, but, there is a .html file reader with the chrome icon :
![explorer-simonikod-powered-by-kodexplorer- -chromium-17_12_2018-13_01_31](https://user-images.githubusercontent.com/31013205/50086032-22dff600-01fc-11e9-88d1-8a019e8b6cba.gif)
