### ISSUE TITLE
Is there an official docker support?

### ISSUE THREAD

**Issue by fengwang** [kalcaddle/KodExplorer#317]
It is not mentioned in the [readme file](https://github.com/kalcaddle/KodExplorer/blob/master/README.md).

Will there be an official docker image?

**Comment by Windelight** [comment]
Well, its no official support for docker
But here is a dockerfile worthy of reference.
`https://github.com/xaljer/docker-kodexplorer/blob/master/Dockerfile`
It seems to have not been updated for a long time, but if you want to use it, you can simply modify a few fields.

**Comment by dhso** [comment]
```
docker run -d \
--name kodexplorer \
--restart=always \
-p 10800:80 \
-v <kodexplorer dir>:/var/www/html \
dhso/kodexplorer:latest
```
current version:4.40
