### ISSUE TITLE
How to change default directory permissions ?

### ISSUE THREAD

**Issue by Cafe31** [kalcaddle/KodExplorer#319]
Hello,

I notice that the folders created with KodExplorer are in 0755 by default.

I would like to change this for 0766, how can I proceed? What changes do I need to make in the configuration?

Kind regards,

**Comment by Windelight** [comment]
Halou Cafe31!
you can found it easily in
`https://github.com/kalcaddle/KodExplorer/search?q=0777&unscoped_q=0777`
`https://github.com/kalcaddle/KodExplorer/search?q=0755&unscoped_q=0755`
Yes, it’s that simple
and download it, change it, use it

**Comment by kalcaddle** [comment]
https://github.com/kalcaddle/KodExplorer/blob/master/config/config.php#L41
