### ISSUE TITLE
无法生成视频的缩略图

### ISSUE THREAD

**Issue by r-y-z** [kalcaddle/KodExplorer#320]
官方demo可以生成视频缩略图，本地搭建的不行，需要怎么做。
有人也有这个问题https://www.hostloc.com/thread-442556-1-1.html

**Comment by kalcaddle** [comment]
很抱歉，目前该功能属于授权版插件功能；
PSD预览插件：支持psd、ai文件预览、缩略图查看；视频文件、pdf文件缩略图生成。

**Comment by hineH** [comment]
希望能下放这个功能给个人用户，需求挺大的，或者你们出个针对个人和家庭用户的授权版也行。
