### ISSUE TITLE
Demo is dead

### ISSUE THREAD

**Issue by psycholyzern** [kalcaddle/KodExplorer#321]
Can we have demo fixed?
even the main website (http://kodcloud.com/) is not accesible.

**Comment by Windelight** [comment]
Hi psycholyzern,
Where is your ISP?
I'm using China Unicom hebei boardband service
This website and its demo are completely normal.
main site `https://www.kodcloud.com`
demo site `http://demo.kodcloud.com/index.php?user/login`
the website's ip address in my network is `118.178.126.92`
Maybe you can try to access it directly with ip (at least it is normal for me), haha

**Comment by PintsizedSix40** [comment]
Hmm, I'm using 1.1.1.1 for my DNS. I'll try switching it to 8.8.8.8 and see if it changes anything.

**Comment by PintsizedSix40** [comment]
Ok, it seems to be cloudflare's problem. I'll see about reporting it.

**Comment by psycholyzern** [comment]
@Windelight I am currently in Malaysia. 


 Seems that the website loaded fine on my phone. I am using cloudflare dns on my phone, but not quite sure what dns I am using on my PC. I'll check it later.

Thanks

**Comment by psycholyzern** [comment]
thanks @PintsizedSix40 ! DNS was the cause. My DNS was set to "obtain automatically" and `nslookup` gave me 
```
Default Server:  UnKnown
Address:  ::10.10.0.1
```

I set DNS manually to Cloudflare's and now the website loaded fine.
