### ISSUE TITLE
Share Public folders with password

### ISSUE THREAD

**Issue by kaypohl** [kalcaddle/KodExplorer#322]
Hi,

can I set passwords also in public folders and files? If I try to share a public folder with password, I get a message that only own documents can be shared.

I have 4 Users. All of them should be able to upload files in a public folder and share them with password.

Is that possible?

Thanks in advance 
Kay

**Comment by kalcaddle** [comment]
![image](https://user-images.githubusercontent.com/3761968/53237392-8c372600-36d1-11e9-8419-375d01e1d840.png)
goto real path, then share it;

**Comment by kaypohl** [comment]
Thank you.
