### ISSUE TITLE
How to force pdf download?

### ISSUE THREAD

**Issue by kaypohl** [kalcaddle/KodExplorer#323]
Hi,

how can I force a pdf download instead of inline viewing?

Thanks in advance.
Kay

**Comment by kalcaddle** [comment]
disable the plugin of pdfView  and pdfjs

**Comment by kaypohl** [comment]
Hi. Thanks for your answer. But it doesn't work. I disabled all plugins and get still the message with inline pdf. I have to click on "download". That happens only for the share option. If I open the info menu for the file and open the link directly, it works.

**Comment by kalcaddle** [comment]
or you can write a plugin do this.
