### ISSUE TITLE
离线下载无法下载文件名为download.php的文件

### ISSUE THREAD

**Issue by Windelight** [kalcaddle/KodExplorer#325]
复现: 文件管理 > 上传 > 离线下载，当下载链接为 http(s)://abc.defghi.jklm/nopqr/stuvwxyz/download.php?bilibilibalabala 的格式时，下载可以提交，可以走进度条，提示完成之后未报错倒寻找该文件不存在，系统 find 也没有。经过检查确认服务器没有问题，Apache 2.4.37 PHP 7.2.3，Bug地址是 `http://kaiyuan.hudong.com/download.php?n=HDWiki-v6.0UTF8-20181112.zip`

**Comment by Windelight** [comment]
？？？？？

**Comment by kalcaddle** [comment]
http://kaiyuan.hudong.com/download.php?n=HDWiki-v6.0UTF8-20181112.zip
这个文件的 附件输出名称content-disposition 输出不标准；应该是：Content-Disposition;

导致最后识别到的文件名为download.php；而创建download.php文件时被安全校验拦截，不允许创建php文件从而移动失败引起。


后面版本兼容一下这种情况。

**Comment by kalcaddle** [comment]
已经做了兼容：

下载这个文件，覆盖到同样位置即可：
https://github.com/kalcaddle/KodExplorer/blob/master/app/function/web.function.php



后面版本自动升级会加入，目前可以先手动覆盖这一个文件即可。。
