### ISSUE TITLE
上传大文件“上传失败(合并异常) [upload_success]”

### ISSUE THREAD

**Issue by Hubray** [kalcaddle/KodExplorer#326]
上传大于1G的文件，遇到过多次这样的情况

刷新后倒是可以看到上传的文件

PHP的超时等参数(max_input_time/max_execution_time)，已经设置3600

服务器环境是宝塔下的nginx/php7.2/centos7，只装了这些

**Comment by kalcaddle** [comment]
上传请求服务器没有返回，或者中断会报这个错误。
一般原因是因为请求超时了。超时时间可以长一点；内存限制可以大一点。
