### ISSUE TITLE
Can't read video on firefox and VLC don't open on chrome-firefox

### ISSUE THREAD

**Issue by IIPoliII** [kalcaddle/KodExplorer#327]
Hello,
I have 2 issues the first one is that for an unkown reason on firefox i can't play anyvideo it plays stop, plays stop and stay in a black screen
![image](https://user-images.githubusercontent.com/29628512/54303529-78d9f500-45c3-11e9-9253-009f3a60f9f5.png)
On chrome it works.

Secondly on chrome, firefox it does me this error for VLC
![image](https://user-images.githubusercontent.com/29628512/54303561-8b542e80-45c3-11e9-8cb9-38e89e14da7f.png)

How do i fix this thanks a lot !

**Comment by simon511000** [comment]
I have the same problem

**Comment by kalcaddle** [comment]
###  is about the html5 vedio type support 

borwser only support the media like : mp4,mov..
you can see this:
https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility
