### ISSUE TITLE
Js File 現在還是壓縮過的，目前已經有用 GPL v3 的 License，這還是必要的嗎？

### ISSUE THREAD

**Issue by gcaaa31928** [kalcaddle/KodExplorer#328]
如題

基於目前這個 Project 已經受GPL v3的保護

Js File 是否有機會提供未壓縮過後的版本

**Comment by kalcaddle** [comment]
github上提供的是release的dist版本；
js源码发布时有打包、编译等操作；一般人不会需要；后面会考虑将源码及相关打包工具教程提供出来

**Comment by gcaaa31928** [comment]
還是希望可以將 javascript open source 出來

讓全世界的人做 KodExplorer 的 contributor
