### ISSUE TITLE
关于上传大文件高负载问题

### ISSUE THREAD

**Issue by Hubray** [kalcaddle/KodExplorer#329]
部署之前，我参照了官网帮助里给出的推荐配置

因为网盘基本上都是我个人使用，所以用了1G1C的VPS来部署

不过实际使用中发现，上传大文件(1G-5G)很容易就满载了

后来用换了其他服务商的同配置机器测试了下，也是很容易满载

这个情况是不是需要更改那里的设置，或者需要升级到一个什么样的配置

**Comment by kalcaddle** [comment]
上传为了使速度最大化，采用了分片多线程并发上传。
这时要求服务器内存相对需要大一点；如果性能偏低，可以通过nginx来配置限速。
