### ISSUE TITLE
使用X-Sendfile下载，这个header是不是设置反了

### ISSUE THREAD

**Issue by xy9860** [kalcaddle/KodExplorer#331]
//调用webserver下载  file.function.php
	$server = strtolower($_SERVER['SERVER_SOFTWARE']);
	if($server && $GLOBALS['config']['settings']['httpSendFile']){
		if(strstr($server,'nginx')){//nginx
			**header("X-Sendfile: ".$file);**
		}else if(strstr($server,'apache')){ //apache
			**header('X-Accel-Redirect: '.$file);**
		}else if(strstr($server,'http')){//light http
			header( "X-LIGHTTPD-send-file: " . $file);
		}
		return;
	}

**Comment by kalcaddle** [comment]
web server大家标准不一致；
取决于服务器配置，我们测试时是按这样配置的；

交换一下兼容性更好，后面版本加入以下优化。
