### ISSUE TITLE
打开编辑器的时候，会出现两个加载图标

### ISSUE THREAD

**Issue by xy9860** [kalcaddle/KodExplorer#333]
打开编辑器的时候，页面的加载图标和编辑器的加载图标一起出现了，这样看起来有点难受
![Z8B$~S) )JVS@HC3_(UO~6H](https://user-images.githubusercontent.com/25838633/55052560-64522e00-5094-11e9-8d8f-082268d92e5d.png)

**Comment by kalcaddle** [comment]
实际上是两个页面，所以会有两个加载图，后面优化一下。
