### ISSUE TITLE
Hard to disconnect from kodcloud.com

### ISSUE THREAD

**Issue by adamsson6** [kalcaddle/KodExplorer#334]
Hi, I'm trying to run this app with no connection to api.kodcloud.com or static.kodcloud.com. But it looks like there are hidden urls in the code, I replaced all strings api.kodcloud.com and static.kodcloud.com but the app still connect to the api server and I don't want that... please do you have an idea ?

Thank you

**Comment by kalcaddle** [comment]
Hello, the link request is used to detect the version update, to ensure that you can notify everyone when there is an emergency bug. The link is placed in the obfuscated dist version code. It is recommended to keep the current state
