### ISSUE TITLE
An error for adminer in php 7.3.3

### ISSUE THREAD

**Issue by dgautumn** [kalcaddle/KodExplorer#335]
On my php 7.3.3 webserver ( it is php:apache docker image on http://hub.docker.com ), while requesting to adminer gets an warning page and no login window, I checked that the offical adminer newest version has fixed this problem. Thanks.

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/kodexplorer/plugins/adminer/adminer/index.php on line 1189

page likes below:

![TIM图片20190402171417](https://user-images.githubusercontent.com/30062447/55390908-c914f900-556a-11e9-93b4-d741a96645e6.png)

**Comment by Windelight** [comment]
Tim图片 什么鬼？直接写中文不好吗？你这机翻能力有点low-level啊，不过这个自带的Adminer的确已经9个月没有更新了

**Comment by Windelight** [comment]
#336 提交了一个PR，并更新了一下

**Comment by dgautumn** [comment]
好，万分感谢。
