### ISSUE TITLE
除了admin以外播放视频报错？

### ISSUE THREAD

**Issue by bulubula** [kalcaddle/KodExplorer#337]
除了admin以外播放视频报错？
同一个视频文件，admin登录就可以播放，文件权限都是777，default就不能放，弹出一个Ajax error说404，别的图片都可以正常浏览，为啥呢？谢谢啊

**Comment by kalcaddle** [comment]
像是权限设置或服务器配置问题；404的话看一下浏览器控制台。应该很好排查。
