### ISSUE TITLE
TXT设置自动换行，换的行前面有空白，求解决

### ISSUE THREAD

**Issue by twamix** [kalcaddle/KodExplorer#339]
TXT设置自动换行，如果编辑框宽度小于段落宽度，txt换的行前面有空白，和在windows上用txt编辑文本正好相反，求解决

**Comment by kalcaddle** [comment]
属于ace editor 编辑器本身的特性。等他们修复后我们更新版本。

**Comment by twamix** [comment]
这个是你们参数选择的问题
https://raw.githack.com/ajaxorg/ace/8cbab2bcca20d7d94f41edec4bc6d53c1212a362/kitchen-sink.html

Indented Soft Wrap 这一项勾选掉，就可以了

另外一个严重的bug ，就是这款编辑器，在所有的移动设备上，编辑器的内容都不能被选择-复制-粘帖，似乎这个问题已经5年没有修复了，
https://github.com/ajaxorg/ace/issues/2265

现在移动办公这么方便，是不是应该更换编辑器了，呵呵

**Comment by kalcaddle** [comment]
后续版本优化
