### ISSUE TITLE
如何访问Linux用户家目录？

### ISSUE THREAD

**Issue by gitby2018** [kalcaddle/KodExplorer#340]
可道云的用户home目录太深，操作Linux的时候要输入的路径太长不方便，自己之前在/home下建立了一个/home/download目录，想用可道云进行管理，用收藏确定了路径，但是提示没有操作的权限，应该如何设置呢？

**Comment by kalcaddle** [comment]
只有管理员才能访问到真实物理路径。
路经长的话，可以添加到收藏夹，或者查看config/config.php 重新指定data目录。
