### ISSUE TITLE
BUG，移动浏览器无法选择-复制-粘帖

### ISSUE THREAD

**Issue by twamix** [kalcaddle/KodExplorer#341]
一个严重的bug ，就是这款编辑器，在所有的移动设备上，编辑器的内容都不能被选择-复制-粘帖，似乎这个问题已经5年没有修复了，
ajaxorg/ace#2265

现在移动办公这么方便，是不是应该更换编辑器了哪？

另外
https://github.com/kalcaddle/KodExplorer/issues/339
这个问题，
不是他们编辑器的问题，是你们参数选择的问题
https://raw.githack.com/ajaxorg/ace/8cbab2bcca20d7d94f41edec4bc6d53c1212a362/kitchen-sink.html

Indented Soft Wrap 这一项勾选掉，就可以了

**Comment by kalcaddle** [comment]
后续版本优化。复制粘贴可能还得等官方修复

**Comment by twamix** [comment]
5年都没修复，希望不大，建议你们在增加一款编辑器插件，这样可以自己设定打开方式

**Comment by twamix** [comment]
https://github.com/ajaxorg/ace/issues/3675#issuecomment-394048821
这个解决方案，看看对你们是否有帮助

**Comment by w1324296014** [comment]
> [ajaxorg/ace#3675 (comment)](https://github.com/ajaxorg/ace/issues/3675#issuecomment-394048821)
> 这个解决方案，看看对你们是否有帮助

请问这个解决方案该怎么用啊？
