### ISSUE TITLE
登录前后的这个信息页面可否统一样式？

### ISSUE THREAD

**Issue by xy9860** [kalcaddle/KodExplorer#344]
登录前的外观
![PC{Z0`ST@(@SRH{QD_ MG9](https://user-images.githubusercontent.com/25838633/56483713-38dd2a80-64fe-11e9-803b-29a374a5aa7c.png)
登录后的外观
![CT }$%YEVB58LSE ( )ZPWB](https://user-images.githubusercontent.com/25838633/56483725-44305600-64fe-11e9-9582-a2ad331f7a38.png)
感觉登录前的样式更加美观，能不能统一样式呢？

**Comment by kalcaddle** [comment]
后续会优化一下，这个也可以自行写全局css进行调整。
