### ISSUE TITLE
Change the user limit on KodExplorer

### ISSUE THREAD

**Issue by Cafe31** [kalcaddle/KodExplorer#346]
Hello,

From user number 50 (in system_member.php), I encounter this error:
当前版本已经超过用户上限，请联系管理员分配名额! (The current version has exceeded the user limit, please contact the administrator to allocate the quota!)

Do you know how to deal with this problem?

I searched everywhere in the configuration but did not find anything.

Thanking you in advance for your help

**Comment by kalcaddle** [comment]
The number of users supported by different licensed versions,
We have already contacted you after sales for .
