### ISSUE TITLE
下载不能断点续传？

### ISSUE THREAD

**Issue by bulubula** [kalcaddle/KodExplorer#347]
我用cloud-torrent下载文件到服务器，kod下载不能断点续传，不能多线程。但是从cloud-torrent页面下载却可以。
情况：下载用的idm，php-fpm以root运行，可以在线播放cloud-torrent下载的文件，但是下载不能断点续传，

**Comment by kalcaddle** [comment]
kod本身是支持断点续传的，具体应用和web server配合；php需要开启多进程。
参考官网demo是可以断点续传的（下载支持暂停，就等于支持断点续传。）
