### ISSUE TITLE
RAR格式打开总是报错[Error]Can't Open; shell_exec Can't use

### ISSUE THREAD

**Issue by Hubray** [kalcaddle/KodExplorer#348]
错误如下，之前在linux下部署，遇到这个问题，没在意

后来换了win环境，依然会有这个报错，是需要安装什么扩展吗？
```
出错了！
[Error] Can't Open; shell_exec Can't use

```

**Comment by kalcaddle** [comment]
服务器配置问题。提示的很明显了，
服务器禁用了shell_exec函数，取消禁用即可，具体百度php.ini   disable_functions。
