### ISSUE TITLE
全屏播放视频时按下空格键造成死循环

### ISSUE THREAD

**Issue by hbfrank** [kalcaddle/KodExplorer#349]
使用Dplayer播放视频时，选择全屏（系统级全屏，非浏览器全屏）后，按一下空格键，页面将会不停地打开新的播放器并陷入死循环，只能关闭浏览器页面。
试验发现，在视频条目（优先关联Dplayer的格式类型）后，按下空格键将打开一个播放器，在播放过程中，空格键的功能并不是播放/暂停，而是仍然打开一个新的播放器。这可能是系统全屏播放时造成死循环的一个原因。

**Comment by kalcaddle** [comment]
播放器本身快捷键和kod快捷键冲突了，
后续会做优化。
