### ISSUE TITLE
Problem uploading folder

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KODExplorer#35]
Hi,

There is a serious bug on your library and I would like to help you reporting it.

Open an empty directory on file explorer of KodExplorer and leave it open inside the browser. After that drag a folder with some subdirectories/files inside of it from the computer to the browser. The first I do that everything will work fine.

But if I do that another time all kind of unexpected behaviour may happen. Instead of overwriting the files, KodExplorer creates several directories in the wrong places inside the already upload folder. It corrupts all the tree. It's very easy to reproduce.

The expected behaviour should be this: if I overwrite a folder it should ovewrite every file/directory inside of it. But it's not what happens. If you need more info I will be glad to help you.

NOTE: on previous version overwriting was never good but at this version it makes a mess when overwriting.

**Comment by kalcaddle** [comment]
Thanks for reporting.

when drag uploading a folder ,at the same time open another folder,it will lead to this problem.

we have fixed this bug already.  before version 3.21 all has this problem;
we will fixed this at next version .

**Comment by gilperon** [comment]
Thank you so much, you made a really nice job with this library! Do you have any idea when you will release the next version with this thing solved? Cause I use your amazing code on a production server and I really would like to keep using it cause your file manager is the BEST ONE around.

I also would like to give you an idea for future versions: the only thing that still makes me use Filezilla is that your file manager does not show the local tree of the files in my computer so I could drag them easily in one screen to the remote server. I wish you could make a left and right panel just like Filezilla so in the left it displays my current computer tree files/directories and on the right the remote server tree (which already displays really fine).

Thank you so much for replying me back and I really do appreciate your effort into this powerfull code your are maintaining!

**Comment by kalcaddle** [comment]
Thank you for supporting our products,your suggest we will have a try.
I will apply oneself to this library  better and better

**Comment by gilperon** [comment]
Thank you so much, congrats! That's a nice product you have, it's very easy to see you are very commited to it! Keep on the good work :)

**Comment by batata004** [comment]
@kalcaddle hi my friend? Any update into this? When are you gonna release a new version with this bug fixed? This library is amazing and if you  need help to improve its code, create a documentation I am here to help! You really need to focus in fixing bug and improving this breat library otherwise people may stop using it.

**Comment by limeng0403** [comment]
曾经有人提过这个问题。

**Comment by batata004** [comment]
Sorry, I am really sorry I dont understand chinese and could not even read what you sair @limeng0403

**Comment by limeng0403** [comment]
@batata004 it's does not matter.Someone once asked a similar question,i said.

**Comment by batata004** [comment]
@limeng0403  it's sad that someone didnt have an answer about that... hope an update come soon cause it's been long since last update and it is plenty of bugs

**Comment by kalcaddle** [comment]
we have fixed this bug already. before version 3.21 all has this problem;
we will fixed this at next version . 
version 3.4 is a big version; there are many new feature; it will pulish at August

**Comment by batata004** [comment]
\o/ UHULL!!!!!! Thank you so much man, you are awesome providing your time to improve this library :)

**Comment by batata004** [comment]
And if I could suggest one more thing: could you please create just and "explorer" library without all the other stuff (desktop...)? I only use your file explorar and it would be nice to download only this module :)

**Comment by kalcaddle** [comment]
You can close the function if you didn't need
1. open setting
2.system settings
3.menu management
4. hide or add the item that you need.  save

**Comment by batata004** [comment]
@kalcaddle tht's good to know my friend :) I hided it right now and it worked. But it would be nice to only be able to download the explorer and editor cause I work in a really limited space server and I would like to save every bit :)

**Comment by kalcaddle** [comment]
Last version 3.34 has fix it
You can have a try.
