### ISSUE TITLE
系统设置里的目录排除似乎不起作用

### ISSUE THREAD

**Issue by Hubray** [kalcaddle/KodExplorer#354]
环境是nginx，PHP7.2，我添加了后缀，还是能看到这些后缀的文件

创建目录排除里默认有的.git后缀的文件，依然能正常看到

是PHP设置或者是那些函数被禁用的原因吗？

**Comment by kalcaddle** [comment]
目前暂不支持通配，需要将派出的文件名或文件夹名写完整。
