### ISSUE TITLE
离线下载遇到的一些问题，必须开启网页才能保持下载和下大文件卡操作中

### ISSUE THREAD

**Issue by mycode233** [kalcaddle/KodExplorer#355]
PHP的max_execution_time和max_input_time已经设置了3600

浏览器是chrome

使用离线下载时，关闭标签会导致下载中断，chrome也会提示
http://img.233255.xyz/image/G7G

还有就是下载较大文件时候，会卡操作中的读条

http://img.233255.xyz/image/Bhv

nginx和apache下都有这个问题

**Comment by kalcaddle** [comment]
这个是服务器配置有关，还有，超时时间是和多方面都有关系的。
没有太好办法。
