### ISSUE TITLE
如何将admin用户的根目录也替换为 /

### ISSUE THREAD

**Issue by helixs** [kalcaddle/KodExplorer#356]
因为最近想进行二次开发，通过api查看目录的时候，普通用户直接可以传入“/”所谓的根目录查看目录结构，可是管理员用户传入"/"就是空的，必须传入网站所在的根目录(如“/www/wwwroot/kod.xxx.com/data/User/admin/home/”)，才可以看到结构，如何让管理员也很友好的查看目录结构。一小白开发者，对php不是很了解。

**Comment by kalcaddle** [comment]
只有管理员是能看到物理路径的。当前版本是这样设计的。
后续版本不再基于物理目录做处理的，会以虚拟目录的方式。
