### ISSUE TITLE
多关键词搜索 优化

### ISSUE THREAD

**Issue by heavenkiller2018** [kalcaddle/KodExplorer#357]
文档搜索里只能按一个关键词进行搜索， 这样文档数量大的时候，搜索质量很差， 建议可以按多关键词进行搜索。 譬如想搜索一个 同时有python 和 flask 关键词的代码文件， 现在只能搜python或flask , 这样搜索出来的结果非常不精准，就失去了文件管理全文搜索的意义了

**Comment by kalcaddle** [comment]
这一块做好，会比较复杂。后续会逐步优化。
