### ISSUE TITLE
"504 Gateway Time-out"  Error when i compress some files or folder...

### ISSUE THREAD

**Issue by Morglaf** [kalcaddle/KodExplorer#360]
Some folder (not all) make me an error when i try too compress them... I chmod the folders (777) and no change. (and this is not depending of the size...

If you have some clue...

**Comment by varoOP** [comment]
I have the same problem. I am using Nginx and php7.3 !

**Comment by kalcaddle** [comment]
Because the program runs out of time.
It is related to the timeout configuration of php.ini and nginx or other web servers.

php: php.ini  set max_execution_time; the recommended setting is 3600;
The nginx configuration can search client_body_timeout; it is recommended to set it to 3600 as well.
