### ISSUE TITLE
选中多个文件下载时，如何能不自动压缩下载

### ISSUE THREAD

**Issue by Hubray** [kalcaddle/KodExplorer#362]
多个小文件压缩倒是没什么影响

就是下载多个大文件时候，也会压缩，而且因为体积大小问题， 基本上没法顺利压缩

所以如何能实现选中多个文件下载时，不进行自动压缩，而是多个文件同时下载

**Comment by kalcaddle** [comment]
是有具体技术原因，基本上浏览器上很难实现。

后面的客户端会支持该特性，目前正在开发中。
