### ISSUE TITLE
关于调用失败错误码的问题

### ISSUE THREAD

**Issue by helixs** [kalcaddle/KodExplorer#363]
我正在进行二次开发，做一个开源文件管理的移动客户端，数据交互主要都是按照json方式，如果遇到错误，或者token过期，会返回html格式的错误信息，可以获取类似的json格式，或者匹配的特定错误码呢？不然过滤网页信息太麻烦了。

**Comment by kalcaddle** [comment]
所有接口请求附带设备参数HTTP_X_PLATFORM 即可；
纯接口访问；


例如文解决列表：?explorer/pathList&path=/&HTTP_X_PLATFORM=xxx
