### ISSUE TITLE
下载大体积文件或者长时间下载，会下载会失败

### ISSUE THREAD

**Issue by 1270001** [kalcaddle/KodExplorer#365]
目前用的是LNMP1.6测试，PHP版本是7.2，centos7

环境装好，不做更改任何设置情况下，安装可道最新4.40，设置好目录权限775和www所属，未添加SSL

在三个不同的网络下进行下载测试

**下载大文件，速度快的话，总是到6G就会停止下载，然后如下报错，

或者是速度较慢，大概1小时20分左右，会停止下载，也是这个报错**

https://i.loli.net/2019/07/11/5d272ea7ed70952069.png

不过这种如果使用文件的网站目录直链下载，倒是没这个问题了，所以怀疑跟PHP那里设置有关

目前稍微试了调大PHP的max_execution_time和request_terminate_timeout，但是还是会在6G报错

**Comment by kalcaddle** [comment]
nginx 和php超时时间都需要进行配置；大于你某个操作需要的时间。
