### ISSUE TITLE
打开损坏的压缩包，会导致PHP耗尽资源直到PHP时间结束

### ISSUE THREAD

**Issue by Hubray** [kalcaddle/KodExplorer#366]
因为上传需求的原因，我的PHP执行时间都是一小时以上

今天在线打开一个压缩包发现一直打不开，遂下载下来，才发现是压缩包有问题

之后过了一段时间发现网站几乎打不开了，SSH过去才发现是php跑满负载了，重启后正常了

之后测试了几次，确实打开损坏的压缩包会导致PHP一直满载，直到执行时间结束

不知道以后能不能对压缩包的判定进行优化

不过因为PHP的执行性质，这个要求应该也不太好实现，这里且当作一个使用反馈吧

**Comment by kalcaddle** [comment]
可以将有问题的压缩包提供一下我们测试看看，我们尽量优化一下。
