### ISSUE TITLE
Login Page Keeps Refreshing

### ISSUE THREAD

**Issue by thedudster** [kalcaddle/KodExplorer#368]
Hi i am using ubuntu 18.04 with Nginx 1.14.0 so today I installed kodexplorer in /var/www/kod on port 8080 and it worked fine after configuring admin password whenever I click login it just reloads the page and nothing happens there are no errors in my Nginx error log as well as in my chrome console.

These are my /etc/Nginx/sites-available/kod file content and I think there is an issue in it and it is something related to cache or cookie.

  <pre> server {
        listen 8080;
        root /var/www/kod;
        index index.php index.html index.htm index.nginx-debian.html;
        server_name localhost;

        location / {
                try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
        }

        location ~ /\.ht {
                deny all;
        }

}</pre>

**Comment by kalcaddle** [comment]
May be caused by your server configuration, unfamiliar can use bt.cn 
one-click deployment of web server
