### ISSUE TITLE
Cannot delete file or folder

### ISSUE THREAD

**Issue by P2T** [kalcaddle/KODExplorer#37]
When I try to delete a file I got this error:
"Path can't write, check the permission"
I can edit, move, rename but not delete.
If I set 777 on the file or the folder, no change.

**Comment by kalcaddle** [comment]
miss  a folder "kod/data/User/***/recycle"  (github auto ignore the empty folder.  try clone the last version)
or  create the folder "recycle"  by yourself

**Comment by P2T** [comment]
Thanks
