### ISSUE TITLE
如何限制通过真实路径访问文件

### ISSUE THREAD

**Issue by pch18** [kalcaddle/KodExplorer#370]
实际使用过程中发现，直接访问文件的地址是可以绕过限制无登陆状态下访问的。

比如一个图片生成的分享链接是这样的
`http://192.168.50.51/index.php?share/file&user=1&sid=aTSB9H5f`
但是通过
`http://192.168.50.51/data/User/admin/home/%E6%88%91%E7%9A%84%E6%96%87%E6%A1%A3/pay/head.jpg`
这个地址，无登陆状态下可以下载任意文件。
如何限制第二种访问？？
能想到的就是用rewrite，看到`config/setting.php`文件中有关于rewrite配置，不知如何使用？
```php
	'paramRewrite'		=> false,		 //开启url 去除? 直接跟参数
```

**Comment by pch18** [comment]
经过尝试，可以在nginx中加入
```
location ^~ /data/ {
        internal;
}
```
来限制浏览器直接访问`/data`文件夹，
但是还是有一个问题，
普通用户打开文件，是通过`/index.php?explorer/fileProxy&accessToken=`这样一个代理来下载文件，
但是管理员通过`右击-浏览器中打开`的时候，是直接访问`/data`的实际路径。

我这里限制了通过浏览器不能访问`/data`文件夹，所以管理员`右击-浏览器中打开`是不能访问的。

如果设置管理员`右击-浏览器中打开`也通过`/index.php?explorer/fileProxy&accessToken=`这样一个文件代理呢？？

**Comment by kalcaddle** [comment]
![image](https://user-images.githubusercontent.com/3761968/62107811-0603b900-b2db-11e9-9b54-07758ed801b5.png)

看config/config.php 中说明，将data目录移到web目录之外即可；
默认是在kod下面，因为不知道外部那个目录可写，所以有需要的可以手动迁移一下即可。
