### ISSUE TITLE
登陆后 关于界面 的 云LOGO不显示

### ISSUE THREAD

**Issue by pch18** [kalcaddle/KodExplorer#371]
# 登陆界面
![image](https://user-images.githubusercontent.com/19822708/62064261-6c4ef400-b267-11e9-8876-56e930204ebe.png)
# 登陆后界面
![image](https://user-images.githubusercontent.com/19822708/62064277-7a9d1000-b267-11e9-9aba-d4592d93b838.png)
# 原因是，登陆界面有设置这个，而登陆后界面没有设置这个。
![image](https://user-images.githubusercontent.com/19822708/62064354-a02a1980-b267-11e9-9dd1-eb40622d679d.png)
# 希望尽快完善，不然这里没有 logo 看着变扭。

**Comment by kalcaddle** [comment]
好的，感谢提醒，后面版本会处理。

**Comment by kalcaddle** [comment]
目前可以在系统设置中，全局css中加入
`
[class^="icon-"]:before, [class*=" icon-"]:before {
    -webkit-text-fill-color: initial;
}
`
