### ISSUE TITLE
开启httpSendFile后，不能打开文件的bug 

### ISSUE THREAD

**Issue by pch18** [kalcaddle/KodExplorer#374]
1. 如图所示, nginx和apache的header写反了, 
nginx 用 `X-Accel-Redirect`
apach 用 `X-Sendfile`

2. 还有 `X-Accel-Redirect` 后面路径应该是 `/` 开头的相对于程序运行目录的路径
原程序里是用的 绝对路径, 导致找不到文件.

我提交了 PR 希望可以参考一下. 

![image](https://user-images.githubusercontent.com/19822708/62191853-66642a80-b3af-11e9-89cd-313cddebd606.png)

**Comment by kalcaddle** [comment]
感谢,后面版本会合并.
