### ISSUE TITLE
希望多语言支持用点心

### ISSUE THREAD

**Issue by pch18** [kalcaddle/KodExplorer#376]
推荐这个软件给日本朋友使用，
被指出了一大堆奇怪翻译。

这两年谷歌翻译已经智能很多了，
希望多语言能重新翻译一下。

最搞笑的是 `space key`  翻译成  `宇宙按键`

**Comment by simon511000** [comment]
exactly the same in French, but worse I think

**Comment by kalcaddle** [comment]
😆, 多语言就是谷歌翻译的,可能词语太短准确率会不高;
基本上有问题都靠大家提pr,毕竟除了中英文其他语言一脸懵逼.
