### ISSUE TITLE
Yozo Office View is not working

### ISSUE THREAD

**Issue by SherabGyatso** [kalcaddle/KodExplorer#382]
It is showing an error when I use the Yozo office view for docs file

**Comment by kalcaddle** [comment]
you can do it by yourself, like others plugins.

**Comment by SherabGyatso** [comment]
Thank you, Mr kalcaddle. can you please tell me in detail what you mean of doing it by yourself. I didn't get it since the Yozo apps are not working when I used to open the docs file.
