### ISSUE TITLE
Flash is no more supported by google chrome due to security issues  

### ISSUE THREAD

**Issue by codesiddhant** [kalcaddle/KodExplorer#383]
Flash is more supported by google chrome due to security issues.
can we use any other software instead of using adobe flash player
if yes then. please tell us how?
I want your reply as soon as possible.
all documentation is in Chinese.
it's really very hard to understand your comments inside this project

**Comment by simon511000** [comment]
> all documentation is in Chinese.
it's really very hard to understand your comments inside this project

I do not know if English documentation will come out someday ...
I asked for English documentation 1 year ago but still nothing #303
