### ISSUE TITLE
含中文的RAR文件打开后提示Match Nothing Content

### ISSUE THREAD

**Issue by Hubray** [kalcaddle/KodExplorer#385]
但是把压缩文件的把名字改成不含中文的就能打开了

搜索引擎看了了下，好像说是跟locale有关，但是内容太少，没找到解决方法

这是我的locale 情况
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by kalcaddle** [comment]
文件内中文编码,当前系统不识别引起的.

**Comment by ThermalEng** [comment]
请问怎么解决，能搞定了吗
