### ISSUE TITLE
希望加入webdav功能

### ISSUE THREAD

**Issue by chaosye0** [kalcaddle/KodExplorer#386]
希望加入webdav功能，那样很多软件都可以使用自建的网盘了，功能上就很完善了

**Comment by kalcaddle** [comment]
新版大版本5.0发布后会加入。
新版支持各类第三方存储，包括ftp，阿里oss，亚马逊S3等


这一块已在开发计划中。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chaosye0 <notifications@github.com&gt;
发送时间: 2019年10月13日 12:14
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] 希望加入webdav功能 (#386)




希望加入webdav功能，那样很多软件都可以使用自建的网盘了，功能上就很完善了

**Comment by kalcaddle** [comment]
包括PC客户端，移动端APP。全端覆盖



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chaosye0 <notifications@github.com&gt;
发送时间: 2019年10月13日 12:14
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] 希望加入webdav功能 (#386)




希望加入webdav功能，那样很多软件都可以使用自建的网盘了，功能上就很完善了

**Comment by chaosye0** [comment]
@kalcaddle 哇，期待更新5.0

**Comment by pch18** [comment]
棒 期待 还有多久到来啊

**Comment by whyun1** [comment]
什么时候发布啊？

**Comment by wanghaisheng** [comment]
@kalcaddle   这个特效网页介绍里有了，但看不到丝毫文档  下不勒手
