### ISSUE TITLE
希望右键菜单在看图片属性的时候带上exif等拍摄信息

### ISSUE THREAD

**Issue by dhso** [kalcaddle/KodExplorer#387]
希望右键菜单在看图片属性的时候带上exif等拍摄信息，谢谢

**Comment by kalcaddle** [comment]
这个对系统有一定要求，需要安装exif扩展配合来处理。后面会考虑支持



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Hadong <notifications@github.com&gt;
发送时间: 2019年10月13日 13:19
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] 希望右键菜单在看图片属性的时候带上exif等拍摄信息 (#387)




希望右键菜单在看图片属性的时候带上exif等拍摄信息，谢谢

**Comment by dhso** [comment]
> 这个对系统有一定要求，需要安装exif扩展配合来处理。后面会考虑支持 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Hadong <notifications@github.com&gt; 发送时间: 2019年10月13日 13:19 收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[kalcaddle/KodExplorer] 希望右键菜单在看图片属性的时候带上exif等拍摄信息 (#387) 希望右键菜单在看图片属性的时候带上exif等拍摄信息，谢谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是的，所以可以考虑在开启插件中心里面exif信息插件的时候，再看图片信息的时候就会出现exif信息。
