### ISSUE TITLE
Can't change login image

### ISSUE THREAD

**Issue by uudruid74** [kalcaddle/KodExplorer#389]
I'm admin, at System -> Wallpaper -> Login and deleting these items doesn't seem to do anything (they come back).  Add will open a file selector, but there is no way to select a file!

**Comment by uudruid74** [comment]
OK.  I figured out the issue.  The window that opens to select does not fit on my screen.  There needs to be some better control over the Max window size

**Comment by kalcaddle** [comment]
replace images source on /data/images/
