### ISSUE TITLE
Reading Latin1 Encoded Files

### ISSUE THREAD

**Issue by P2T** [kalcaddle/KODExplorer#39]
Hello,
In the new version, when opening a latin1 iso-8859-1 encoded file, I get the following error:
Warning: mb_convert_encoding(): Illegal character encoding specified in /var/www/kod/controller/editor.class.php on line 34

**Comment by kalcaddle** [comment]
we will fixed this bug next version

**Comment by kalcaddle** [comment]
Last version 3.34 , fix it
You can have a try.
