### ISSUE TITLE
文件安全如何保证呢？

### ISSUE THREAD

**Issue by nealwon** [kalcaddle/KodExplorer#392]
我注意到文件直接被存放在documentRoot的子目录里，可以通过URL直接访问到文件!

不知道对这个是否有考虑改进？

UI和使用上都不错，就是这个安全问题略有疑虑！

**Comment by kalcaddle** [comment]
可以将data目录移到web目录之外，
查看config/config.php 有说明



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: none <notifications@github.com&gt;
发送时间: 2019年10月26日 07:58
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] 文件安全如何保证呢？ (#392)




我注意到文件直接被存放在documentRoot的子目录里，可以通过URL直接访问到文件!
 
不知道对这个是否有考虑改进？
 
UI和使用上都不错，就是这个安全问题略有疑虑！

**Comment by nealwon** [comment]
对的，第一次用这个，没去看源码！

**Comment by MrThanlon** [comment]
其实还可以对web server进行设置，禁止某个目录的访问
