### ISSUE TITLE
YARA.php_malware_hexinject.UNOFFICIAL FOUND in cpanel

### ISSUE THREAD

**Issue by AmirAmraei** [kalcaddle/KodExplorer#394]
hi
i cant uplaod kodcloud in my host with cpanel , because show this message
***The file you uploaded, Kod.zip, contains a virus so the upload was canceled: YARA.php_malware_hexinject.UNOFFICIAL FOUND***

What's the solution?

**Comment by kalcaddle** [comment]
error judge by some software on your server.
