### ISSUE TITLE
Skip login page

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KODExplorer#40]
Hi,

In the previous versions that I used of kodexplorer I did some "not easy" changes to your code to skip the login page but in this new version this change is not working anymore.

Maybe you can help me with an easiest way: I have a private server and I want my user to access the KodExplorer without login, I want him to be logged in automatically as admin. How can I do that?

**Comment by kalcaddle** [comment]
you can open a url like 

http://demo.kalcaddle.com/index.php?user/loginSubmit&name=demo&password=demo&rember_password=1


also you can config that auto login with guest: 
step 1: use admin login kodexplorer
step 2:"system setting"==>"Guest auto login: "  open the switch

**Comment by gilperon** [comment]
Thank you man :) You are awesome!
