### ISSUE TITLE
关于上传事提示该目录没有写权限问题，求助

### ISSUE THREAD

**Issue by kva159** [kalcaddle/KodExplorer#400]
首先，感谢写出这么优秀的软件
我在openwrt  X86中使用该插件搭建完成后，在上传时提示该目录没有写权限
截图如下
![TIM截图20191231160800](https://user-images.githubusercontent.com/33386548/71614653-e8b77b80-2be7-11ea-8cfd-786bb0551974.png)
![TIM截图20191231160814](https://user-images.githubusercontent.com/33386548/71614655-ece39900-2be7-11ea-994d-0ceca4b6422a.png)

我已经对相关目录下的所有文件件授予了7777权限
![image](https://user-images.githubusercontent.com/33386548/71609788-53f05600-2bc6-11ea-80c3-4a097056e1da.png)
![QQ拼音截图20191231120935](https://user-images.githubusercontent.com/33386548/71610420-dd565700-2bcb-11ea-9a63-d69cf92a87e5.png)

请问还需要修改哪里才能正常上传
谢谢！

**Comment by kalcaddle** [comment]
包括上传目录及上传系统缓存文件夹目录,都需要读写权限.
