### ISSUE TITLE
局域网搭建有问题

### ISSUE THREAD

**Issue by eastFu** [kalcaddle/KodExplorer#401]
看了源代码，里面大量功能依赖于kod的各种api和资源服务器，不能实现完全内网本地搭建...

**Comment by kalcaddle** [comment]
内网完全可以用，只是插件市场不能使用，部分依赖第三方api的服务用不了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 咚呲嗒呲 <notifications@github.com&gt;
发送时间: 2020年1月17日 09:25
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] 局域网搭建有问题 (#401)




看了源代码，里面大量功能依赖于kod的各种api和资源服务器，不能实现完全内网本地搭建...
