### ISSUE TITLE
可道云重大安全漏洞：无需密码即可访问所有资源

### ISSUE THREAD

**Issue by bingcheng1998** [kalcaddle/KodExplorer#402]
可道云最新版本（老版本也是）有重大安全风险。

测试方法：
![image](https://user-images.githubusercontent.com/26592478/74346220-34199800-4dea-11ea-92bb-92c126b40ccc.png)
新建一个html，尝试外链打开，如上图，打开后复制此html，发现可以在任意未注册设备打开。

这样任何人只要有你的可道云地址，可以尝试出所有文件，并且下载。

**Comment by kalcaddle** [comment]
1. 只有管理员才能访问导出物理路径; 右键属性加密连接输入文件外链, 本身就是预留设计的功能;
2. 担心文件目录安全的可以将data目录移到web目录之外;
具体参考: https://github.com/kalcaddle/KodExplorer/issues/392

如果担心web目录变量这个基本是多虑了,做好防止列目录即可; 
比如我的 demo.kodcloud.com 下面有一个文件存的是某个用户银行卡密码你能拿到? 
遍历,基本上是不可能的.

**Comment by dsafaasdw** [comment]
没太看懂这个
