### ISSUE TITLE
ace 编辑器有问题

### ISSUE THREAD

**Issue by w3yyb** [kalcaddle/KodExplorer#405]
编辑文件时，在光标处插入字符，就会跑到别的位置了，我是chrome 80浏览器。

**Comment by kalcaddle** [comment]
mac  chrome 80 没测试出该问题, 麻烦提供一下截图或视频

**Comment by w3yyb** [comment]
请查看这视频   [https://www.hdycsx.com/WeChat_20200305085714.mp4](https://www.hdycsx.com/WeChat_20200305085714.mp4)

**Comment by kalcaddle** [comment]
还是没有测试出来,你去ace官方测试下看看.


 原始邮件 
发件人: Lenix<notifications@github.com>
收件人: kalcaddle/KodExplorer<KodExplorer@noreply.github.com>
抄送: warlee<824691958@qq.com>; State change<state_change@noreply.github.com>
发送时间: 2020年3月5日(周四) 09:01
主题: Re: [kalcaddle/KodExplorer] ace 编辑器有问题 (#405)


请查看这视频 https://www.hdycsx.com/WeChat_20200305085714.mp4

**Comment by w3yyb** [comment]
官网的也有这问题：）

**Comment by kalcaddle** [comment]
那可能是你自己浏览器哪里字体相关有问题; 
我们测试了各种浏览器都没这个问题.


 原始邮件 
发件人: Lenix<notifications@github.com>
收件人: kalcaddle/KodExplorer<KodExplorer@noreply.github.com>
抄送: warlee<824691958@qq.com>; State change<state_change@noreply.github.com>
发送时间: 2020年3月6日(周五) 18:15
主题: Re: [kalcaddle/KodExplorer] ace 编辑器有问题 (#405)


官网的也有这问题：）

**Comment by w3yyb** [comment]
可能 吧，我换了firefox就没问题了

**Comment by w3yyb** [comment]
官方回应：This happens because the font is not monospace, ace supports only monospace fonts for now.
