### ISSUE TITLE
data 目录不存在!  (检查 DATA_PATH);

### ISSUE THREAD

**Issue by bsidhu009** [kalcaddle/KodExplorer#406]
data directory does not exist!

(check DATA_PATH);

**Comment by kalcaddle** [comment]
mean


data directory does not exist!



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bsidhu009 <notifications@github.com&gt;
发送时间: 2020年2月28日 01:58
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] data 目录不存在!  (检查 DATA_PATH); (#406)




data directory does not exist!
 
(check DATA_PATH);

**Comment by FunnyTeacher** [comment]
![image](https://user-images.githubusercontent.com/19985721/75502998-5e38a000-5a0f-11ea-83ab-38094d380aa2.png)

**Comment by PaulKsi** [comment]
still apears
