### ISSUE TITLE
目录权限错误

### ISSUE THREAD

**Issue by garypang13** [kalcaddle/KodExplorer#407]
PHP Version 7.2
[Error Code:1002] 目录权限错误！
程序目录及所有子目录已经设置为了777

**Comment by garypang13** [comment]
降级到[e543e0ec4aabdce63730af4a63016bf5b95ab03c](https://github.com/kalcaddle/KodExplorer/tree/e543e0ec4aabdce63730af4a63016bf5b95ab03c) 后恢复正常,

**Comment by SergioDaroca** [comment]
Hi! I'm truly amazed with KodExplorer.
I had the same error. And my permissions where correctly set up.
In the end I had  a missing trailing slash at config/define.php:
<?php define ('DATA_PATH', '/srv/ ... /data**/**');
