### ISSUE TITLE
install doesn't work

### ISSUE THREAD

**Issue by augras** [kalcaddle/KodExplorer#409]
Hi, i try to install KodExplorer but i get Fatal error: require(): Failed opening required '/public_html/kodexplorer/app/template/user/install.html' (include_path='.:/opt/alt/php74/usr/share/pear') in /public_html/kodexplorer/app/core/Controller.class.php on line 72.
I download the KodExplorer-master.zip file, extract it, upload the folder by ftp, put the rights to 777 for all included folders and files.
Can you help me please.
Thank you,
Philippe

**Comment by kalcaddle** [comment]
server error

**Comment by GokulNC** [comment]
Running with root access helped: `sudo php -S 0.0.0.0:8000`
