### ISSUE TITLE
上传大文件报错

### ISSUE THREAD

**Issue by pangqingyuan1991** [kalcaddle/KODExplorer#41]
我在nas上部署了这个项目，然后上传一个6G的大文件，上传过程没报错，但是上传到100%后，过了一会就报“上传失败（server）”，我在后台可以看到此时服务器的php还在创建文件，因为这个文件在不停的增大。最后，比对文件md5一致，说明上传是成功的。是不是bug?

**Comment by kalcaddle** [comment]
是上传成功的，提示信息错误了。下个版本会修复。
