### ISSUE TITLE
在登录失效后重新登录，无限弹系统错误或者token_error

### ISSUE THREAD

**Issue by liesauer** [kalcaddle/KodExplorer#411]
版本：v4.40
问题：rt，在登录很久时间之后，重新登录进入系统，操作任何东西都会弹系统错误，偶尔弹token_error，然后又要你重新登录，然后又弹错误。。。
经测试，在f12下关闭缓存重新登陆才能重新进去。

**Comment by kalcaddle** [comment]
应该是服务器session配置问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: L!εsAμεr <notifications@github.com&gt;
发送时间: 2020年3月22日 18:44
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] 在登录失效后重新登录，无限弹系统错误或者token_error (#411)





 
版本：v4.40
 问题：rt，在登录很久时间之后，重新登录进入系统，操作任何东西都会弹系统错误，偶尔弹token_error，然后又要你重新登录，然后又弹错误。。。
 经测试，在f12下关闭缓存重新登陆才能重新进去。

**Comment by liesauer** [comment]
@kalcaddle 以前没有的，而且服务器配置也没有改动过。
