### ISSUE TITLE
添加代理选项

### ISSUE THREAD

**Issue by naranakula** [kalcaddle/KodExplorer#414]
服务器一般在内网，不能直接上外网，使用某个代理服务器才能访问外部网站；
这样导致在安装插件的时候不能访问外部服务器，最终安装失败；
是否可以提供一个配置项，配置全局外网代理ip以及端口号？

**Comment by kalcaddle** [comment]
这个程序不太好实现,最好在服务端网络处做处理; 
可以根据域名自动进行代理. 


 原始邮件 
发件人: 马<notifications@github.com>
收件人: kalcaddle/KodExplorer<KodExplorer@noreply.github.com>
抄送: Subscribed<subscribed@noreply.github.com>
发送时间: 2020年3月30日(周一) 16:48
主题: [kalcaddle/KodExplorer] 添加代理选项 (#414)


服务器一般在内网，不能直接上外网，使用某个代理服务器才能访问外部网站；
 这样导致在安装插件的时候不能访问外部服务器，最终安装失败；
 是否可以提供一个配置项，配置全局外网代理ip以及端口号？
