### ISSUE TITLE
Edit file by URL is not working

### ISSUE THREAD

**Issue by coffe1nk2** [kalcaddle/KodExplorer#415]
Hi,

I am refering to this issue #69 

I can access Directory and file using this URL

- `http://kmnote/kodexplorer/index.php?explorer/index&path=data/User/admin/home/Journal/2020/04/`
- `http://kmnote/kodexplorer/index.php?explorer/fileView&path=data/User/admin/home/Journal/2020/04/HAIP.md`

But I can't edit file directly using this URL

`http://kmnote/kodexplorer/index.php?editor/edit&filename=data/User/admin/home/Journal/2020/04/HAIP.md`

My Question, How to edit file directly from URL?

Thank you

**Comment by kalcaddle** [comment]
like this:
http://localhost/kod/kod_dev/index.php?editor/edit#filename=/tmp/1.txt
