### ISSUE TITLE
Use sha1 or sha256 instead of md5 for password digests

### ISSUE THREAD

**Issue by GuyPaddock** [kalcaddle/KodExplorer#416]
This app uses MD5-digests for password storage, but MD5 has been rainbow-tabled for a long time now. 

It would be best if everywhere the app is using `md5()` it was instead using `sha1()` or `hash('sh256')`.

**Comment by kalcaddle** [comment]
you can do it by yourself

**Comment by GuyPaddock** [comment]
Lovely response.
