### ISSUE TITLE
如何隐藏以点（.___）开头的文件

### ISSUE THREAD

**Issue by RealKiro** [kalcaddle/KodExplorer#418]
如何隐藏 `.` 开头的文件？我设置里面好像没找到这个开关（小声
![image](https://user-images.githubusercontent.com/33367701/78999126-97227380-7b7c-11ea-854e-edb5999c3278.png)

**Comment by kalcaddle** [comment]
暂不支持该功能



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 未日 <notifications@github.com&gt;
发送时间: 2020年4月10日 22:44
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] 如何隐藏 `.` 开头的文件 (#418)





 
如何隐藏 . 开头的文件？我设置里面好像没找到这个开关（小声

**Comment by RealKiro** [comment]
有部分轻应用网页失效导致打不开
![image](https://user-images.githubusercontent.com/33367701/79038037-c383d180-7c08-11ea-9b5c-debc3139e305.png)

我通过admin权限修改替换为其它的，通过guest权限登陆还是原来的轻应用
![image](https://user-images.githubusercontent.com/33367701/79038016-9a634100-7c08-11ea-9766-c6866269052a.png)
所以逻辑是：能不能加个勾选选项使修改的`设置`能全部生效？

**Comment by kalcaddle** [comment]
不能，每个轻应用安装后就是独立的文件了，需要用户重新安装一下即可



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 未日 <notifications@github.com&gt;
发送时间: 2020年4月11日 15:32
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: warlee <824691958@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] 如何隐藏以点（.___）开头的文件 (#418)
