### ISSUE TITLE
如何获得accessToken?

### ISSUE THREAD

**Issue by hcwang** [kalcaddle/KodExplorer#420]
在[可道云API开发文档](https://doc.kodcloud.com/v2/#/user/user?id=获取accesstoken)中提到的获得accessToken的方案似乎不可用？是否有新的方案？谢谢。

**Comment by kalcaddle** [comment]
http://doc.kodcloud.com/v2/#/user/user


详见文档。开发需求比较多可以购买授权版，我们提供专业的开发指导与技术支持。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: joycode <notifications@github.com&gt;
发送时间: 2020年4月16日 20:20
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] 如何获得accessToken? (#420)





 
在可道云API开发文档中提到的获得accessToken的方案似乎不可用？是否有新的方案？谢谢。

**Comment by hcwang** [comment]
通过文档中的描述，在当前开源版本的4.4中，通过http://server/?user/index/loginSubmit&name=[用户名]&password=[密码] 中只能获得一个登录页面，好象index method not found。是不是因为有bug?

**Comment by kalcaddle** [comment]
kodexplorer 开发文档: http://doc.kodcloud.com/#/api/user
kodbox 开发文档: http://doc.kodcloud.com/v2/#/user/user

不同产品,注意不要搞错.

**Comment by hcwang** [comment]
感谢！
