### ISSUE TITLE
上传速度慢

### ISSUE THREAD

**Issue by msoayu56** [kalcaddle/KodExplorer#423]
同样的设备、文件，用FileBrowser就很快，可以跑满，但是用可道云就很慢，速度时快时慢。

**Comment by msoayu56** [comment]
Raspbian + php7.3 + Apache2

**Comment by kalcaddle** [comment]
一般是配置问题，邮件回复个地址和账号看看



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: msoayu56 <notifications@github.com&gt;
发送时间: 2020年4月22日 14:27
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] 上传速度慢 (#423)






Raspbian + php7.3 + Apache2

**Comment by msoayu56** [comment]
> 一般是配置问题，邮件回复个地址和账号看看 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: msoayu56 <notifications@github.com&gt; 发送时间: 2020年4月22日 14:27 收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[kalcaddle/KodExplorer] 上传速度慢 (#423) Raspbian + php7.3 + Apache2 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我是内网搭建的...

**Comment by msoayu56** [comment]
![image](https://user-images.githubusercontent.com/38905616/80052834-361c7780-854e-11ea-8c1f-67ab7b674b32.png)
用可道云上传时快时慢
用filebrowser就很稳定
![image](https://user-images.githubusercontent.com/38905616/80053142-cd81ca80-854e-11ea-8847-03da60bb6321.png)

**Comment by kalcaddle** [comment]
kod针对大文件做了分片多线程上传，分片并计算处理在前端完成会有一定时间。所以会有间歇低峰。


程序主要考虑各种服务器配置兼容性，配置不一定是最优的，可以自行调整分片大小，并发数调优。
http://doc.kodcloud.com/#/others/options







发自我的iPhone


------------------ 原始邮件 ------------------
发件人: msoayu56 <notifications@github.com&gt;
发送时间: 2020年4月23日 10:40
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: warlee <824691958@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] 上传速度慢 (#423)







用可道云上传时快时慢
用filebrowser就很稳定

**Comment by msoayu56** [comment]
好吧，那我就用可道云看看文件，传文件还是FTP吧
