### ISSUE TITLE
Community ?

### ISSUE THREAD

**Issue by TwanoO67** [kalcaddle/KodExplorer#424]
Hello,

Is there any forum, chat or group with a user community ?
I'm searching some people to discuss about that in English or French.

If not, I will be happy to build one.
Making some discussions, tutorials, videos, on how to install/configure/use KodExplorer and plugins.

Please share community links here, or contact me by email: perso at weberantoine dot com   if you're interessted to build one :)

**Comment by kalcaddle** [comment]
http://bbs.kodcloud.com/
