### ISSUE TITLE
生成缩略图大量占用CPU导致网页卡死 

### ISSUE THREAD

**Issue by phoenixsfly** [kalcaddle/KodExplorer#425]
在开启「**开启图片缩略图**」功能后，如果打开一个包含大量照片的文件夹时，网页会直接卡死，几乎任何操作都无法继续

经过筛查，发现是生成缩略图会大量占用服务器CPU，CPU 占用几乎达到100%。
我的运行环境是是intel i7 7700hq，8GB内存。
这是一个很棘手的问题，其他开源网盘也或多或少存在这类问题，比如大名鼎鼎的nextcloud，生成缩略图也会占用大量CPU，导致很卡，无法浏览照片。

对比其他开源网盘程序，有如下解决方案：
1. 直接不显示缩略图，可道云也可以设置不显示缩略图，但是当双击打开某张图片后，此时还是会对这张图片生成缩略图（耗时约0.5~1s），然后展示。
2. 调用效率更高的缩略图转码程序，例如采用**ImageMagick** ,php有对应地模块叫imagick，许多php程序为了追求高效图片处理均采用这种方案。
3. 只对大图片重新生成缩略图，对于小图片直接传输，以原始图片作为缩略图（Filerun采用这种做法）
4. 在后台CPU空闲时候检索用户目录预先生成缩略图 （Nextcloud中的preview generator）

**Comment by kalcaddle** [comment]
你好:


主要是服务器硬件配置; 程序也做了相关优化: 
1. 图片缩略图只有首次加载才进行图片处理;生成过了不会再生成,不会耗费服务器资源
2. 图片列表区域会有懒加载,只有文件列表在显示区域时才加载图片; 即会触发服务器生成缩略图;
3. 可以在个人中心关闭图片缩略图功能:  右上角菜单—个人中心—— 取消勾选”开启图片缩略图”




推荐使用kodbox新版本; 支持分页加载; 可以自定义每页显示内容数;
安装包: http://static.kodcloud.com/update/download/kodbox.1.07.zip
更新说明: https://doc.kodcloud.com/v2/#/help/changeLog


PC端客户端:
Win安装包: http://static.kodcloud.com/update/client/%E5%8F%AF%E9%81%93%E4%BA%91%20Setup%200.1.3-x64.exe
Mac安装包: http://static.kodcloud.com/update/client/%E5%8F%AF%E9%81%93%E4%BA%91-0.1.3.dmg








 原始邮件 
发件人: phoenixsfly<notifications@github.com>
收件人: kalcaddle/KodExplorer<KodExplorer@noreply.github.com>
抄送: Subscribed<subscribed@noreply.github.com>
发送时间: 2020年4月22日(周三) 21:39
主题: [kalcaddle/KodExplorer] 生成缩略图大量占用CPU导致网页卡死 (#425)


如果打开一个包含大量照片的文件夹时，网页会直接卡死，几乎任何操作都无法继续
经过筛查，发现是生成缩略图会大量占用服务器CPU，CPU 占用几乎达到100%，运行环境是是intel E3，4GB内存。
 这是一个很棘手的问题，其他开源网盘也或多或少存在这类问题，比如大名鼎鼎的nextcloud，生成缩略图也会占用大量CPU，导致很卡，无法浏览照片。
对比其他开源网盘程序，有如下解决方案：
直接不显示缩略图，可道云也可以设置不显示缩略图，但是这样体验大打折扣 调用效率更高的缩略图转码程序，例如采用ImageMagick （强烈推荐） 只对大图片重新生成缩略图，对于小图片直接传输，以原始图片作为缩略图（Filerun采用这种做法） 在后台CPU空闲时候检索用户目录预先生成缩略图 （Nextcloud中的preview generator）

**Comment by phoenixsfly** [comment]
感谢回复！
缩略图确实知会在首次加载生成并缓存在thumb目录中，但是仅仅是首次加载就会卡顿很久，这样的体验实在太糟糕。
我在不同机器上都部署了这个应用（E3 I7 I3）都会导致卡死，说明原生php执行图片处理效率太低，还是希望开发组能考虑调用**imagick**这款更高效地模块，加速图片处理，给用户带来更好地体验！

**Comment by kalcaddle** [comment]
大部分服务器是没有该图片扩展的，建议使用分页浏览，每页20条





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: phoenixsfly <notifications@github.com&gt;
发送时间: 2020年4月22日 21:58
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: warlee <824691958@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] 生成缩略图大量占用CPU导致网页卡死  (#425)





 
感谢回复！
 缩略图确实知会在首次加载生成并缓存在thumb目录中，但是仅仅是首次加载就会卡顿很久，这样的体验实在太糟糕。
 我在不同机器上都部署了这个应用（E3 I7 I3）都会导致卡死，说明原生php执行图片处理效率太低，还是希望开发组能考虑调用imagick这款更高效地模块，加速图片处理，给用户带来更好地体验！
