### ISSUE TITLE
Pdf thumbnail

### ISSUE THREAD

**Issue by jamalkhan2k6** [kalcaddle/KodExplorer#426]
Hi,
I have noticed that pdf first page is visible as thumnail in the demo, but it doesnt show the thumbnail if I host it myself. Is there something I need to do?

**Comment by kalcaddle** [comment]
you can do it by yourself

**Comment by jamalkhan2k6** [comment]
Thanks, could you give me some pointers for it.
Any help would be great.

**Comment by kalcaddle** [comment]
need to use imagemagick;
