### ISSUE TITLE
不能清空回收站？

### ISSUE THREAD

**Issue by pangqingyuan1991** [kalcaddle/KODExplorer#43]

**Comment by kalcaddle** [comment]
是因为用github 或者从gitosc clone安装的。
由于git不能提交空目录导致回收站默认不存在。

解决方法：
1.手动给每个用户建立文件夹 data/User/***/recycle
2.现在github已经做了对应更新；也可以直接覆盖

**Comment by pangqingyuan1991** [comment]
我是说删除文件都是放到回收站目录，但是找不到清空回收站的选项。

**Comment by kalcaddle** [comment]
文件管理——左下角点击回收站，有『清空回收站』选项
也可以直接右键左下角回收站清空。
