### ISSUE TITLE
Refused to frame 'https://www.xxxxxxxx.xxx/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors

### ISSUE THREAD

**Issue by ghopretz** [kalcaddle/KodExplorer#430]
Refused to frame 'https://www.xxxxxxxx.xxx/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors http://xxxxxxxx.xxx/phppgadmin/".

how to solve that?

**Comment by kalcaddle** [comment]
look this .
https://developer.mozilla.org/docs/Web/HTTP/Headers/Content-Security-Policy
