### ISSUE TITLE
5.0什么时候发布啊？

### ISSUE THREAD

**Issue by whyun1** [kalcaddle/KodExplorer#432]
讲了这么久了，都还不知道什么时候发布。。。

**Comment by kalcaddle** [comment]
发布大半年了，


https://kodcloud.com/download

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: whyun1 <notifications@github.com&gt;
发送时间: 2020年5月30日 17:57
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] 5.0什么时候发布啊？ (#432)
