### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by TWINGSISTER** [kalcaddle/KodExplorer#434]
I am using KodExplorer in my webinar
http://primi235711.altervista.org/moodle/mod/scorm/view.php?id=75 and i can't find any documentation for the plugin architecture. I was trying to have editors to create a free clone of O365 linked to KE and found none. Using Docker afaik means monthly fee so the best I have found for free is 
this API
https://www.offidocs.com/index.php/sdk-xls-ppt-doc-online-libreoffice-offidocs 
or this 
https://office.ssuiteoffice.com/ + webdav

I have no idea on how to develop a KOD plugin to integrate this, 

However, for the use in my webinars this is not necessary  so thanks for this wonderful piece of software and let's say my encouragement for some english docs for plugin development.

**Comment by kalcaddle** [comment]
请参考现有插件的代码编写插件;
后续会提供英语的插件开发文档.
Please refer to the code of existing plug-ins to write plug-ins;

The following will provide English plug-in development documents
