### ISSUE TITLE
php版本离线下载 限制下载数 怎么修改？

### ISSUE THREAD

**Issue by ilovebamboo** [kalcaddle/KodExplorer#435]
同时下载文件太多容易超时，我一次性复制150个链接下载，任务太多 提示失败。哪里可以修改同时下载任务数？
![image](https://user-images.githubusercontent.com/6214084/83831603-5416f380-a71a-11ea-9d87-bf3c506eacba.png)

**Comment by kalcaddle** [comment]
不支持修改，可以将PHP运行线程数加大



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Lotus <notifications@github.com&gt;
发送时间: 2020年6月5日 10:50
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] php版本离线下载 限制下载数 怎么修改？ (#435)





 
同时下载文件太多容易超时，我一次性复制150个链接下载，任务太多 提示失败。哪里可以修改同时下载任务数？

**Comment by ilovebamboo** [comment]
![image](https://user-images.githubusercontent.com/6214084/83832019-3eee9480-a71b-11ea-947d-31cefef4f0d6.png)
我改成1000 了 8G内存 windows 2008系统

**Comment by ilovebamboo** [comment]
![image](https://user-images.githubusercontent.com/6214084/83832053-5594eb80-a71b-11ea-9e55-35912bf45b83.png)
我改成1000 了 8G内存 windows 2008系统

**Comment by ilovebamboo** [comment]
![image](https://user-images.githubusercontent.com/6214084/83832091-72c9ba00-a71b-11ea-823f-b91de6b330b0.png)
