### ISSUE TITLE
redirected you too many times when trying to open Adminer

### ISSUE THREAD

**Issue by Q8root** [kalcaddle/KodExplorer#437]
When i try to open Adminer, browser return error:-
This page isn’t working192.168.1.6 redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
http://192.168.1.6:8088/KodExplorer/index.php?user/sso&app=AdminerAccess&check=roleID&value=1&link=http%3A%2F%2F192.168.1.6%3A8088%2FKodExplorer%2Fplugins%2Fadminer%2Fadminer%2F

I am using KodExplorer in windows 10 with xampp PHP 7.2.30

**Comment by kalcaddle** [comment]
clear the cookie and then have a try.
