### ISSUE TITLE
在线解压缩

### ISSUE THREAD

**Issue by skiy** [kalcaddle/KODExplorer#44]
完美取代FTP管理：可用于服务器文件管理,支持图片、音乐、视频预览，**在线解压缩**，文件夹拖拽上传……。

你们所说的在线解压缩在哪里？我可找不到这功能。

补充一下，是tar的包

**Comment by kalcaddle** [comment]
目前只支持zip加压缩  无需第三方扩展。

tar的包后面加入，需要系统支持（linux 并且允许php执行shell脚本。）
