### ISSUE TITLE
How to create custom plugin server?

### ISSUE THREAD

**Issue by werasik2aa** [kalcaddle/KodExplorer#441]
Please give me api for download plugins from app store

**Comment by simon511000** [comment]
I think the API is not public and the server is not open source but you can change the server [here](https://github.com/kalcaddle/KodExplorer/blob/master/config/setting.php#L21)
and try to understand in the source code of KodExplorer to create your own store. But it's complicated because JS files are minified

**Comment by werasik2aa** [comment]
> I think the API is not public and the server is not open source but you can change the server [here](https://github.com/kalcaddle/KodExplorer/blob/master/config/setting.php#L21)
> and try to understand in the source code of KodExplorer to create your own store. But it's complicated because JS files are minified

Can you help with source? i saw you https://github.com/kalcaddle/KodExplorer/issues/307 almost done

**Comment by werasik2aa** [comment]
i want create fully linux desktop without x screen

**Comment by werasik2aa** [comment]
almost ) just use web enviroment as linux)

**Comment by werasik2aa** [comment]
But i dont know what is it... $config = json_decode(file_get_contents("config.json"),true);

**Comment by werasik2aa** [comment]
![image](https://user-images.githubusercontent.com/20810116/90850318-09506380-e37a-11ea-89b4-e3def5cfea9d.png)
But i can create apps here . but i want create repository for apps...

**Comment by simon511000** [comment]
Yes it was a test that I made, a long time ago but it never really worked

But KodExplorer is not linux
KodExplorer tries to simulate an operating system directly in JavaScript but has nothing to do with Linux
I don't know if it's possible but you can try to install Linux on VirtualBox and access it from a web browser with X client
