### ISSUE TITLE
[Feature request] 系統模式

### ISSUE THREAD

**Issue by HuJK** [kalcaddle/KodExplorer#443]
目前的版本看起來是在kodexplorer系統內管理多個使用者，對外部文件系統來說，所有檔案都是屬於php

想請問能不能推出一個系統模式(名字隨便取的)，使用linux的pam模組

帳密系統的話，直接用linux的帳密登入，登入以後就直接是哪個使用者的身份。
kodexplorer自己就不負責使用者管理的部分了，也不需要資料庫儲存這類資訊了

daemon可能是以root運行的，或是以普通使用者身份運行。
收到登入請求以後，就su切換成他的身份跑一個後端，按cookie把操作都轉發給那個使用者的後端。還要注意跑的後端只有daemon能連，別人不能連

有特權的sudo使用者，還能執行chown chmod，或是掛載硬碟/nfs等，總之就變成一個網頁版的檔案管理器的感覺，而不僅僅是一個雲盤的感覺

**Comment by kalcaddle** [comment]
这个需要系统权限, 可以给webroot chmod更高或更低的权限,
