### ISSUE TITLE
有支持webssh 的插件吗

### ISSUE THREAD

**Issue by ahKevinXy** [kalcaddle/KodExplorer#444]

**Comment by kalcaddle** [comment]
暂时没有，github上有webssh类项目，可以自行安装。go语言的那个体验不错



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ahKevinXy <notifications@github.com&gt;
发送时间: 2020年9月16日 10:00
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] 有支持webssh 的插件吗 (#444)

**Comment by ahKevinXy** [comment]
已经解决
