### ISSUE TITLE
上传文件时报错

### ISSUE THREAD

**Issue by WriteMemory** [kalcaddle/KodExplorer#445]
使用环境：
debian testing
nginx 1.18.0
php-fpm 7.4
sqlite3

出错信息：
出错了! (warning!)
think_trace();
database is locked[ SQL语句 ] :SELECT * FROM `io_source` WHERE ( sourceID = '8' ) LIMIT 1

**Comment by kalcaddle** [comment]
推荐使用mysql+redis; 
sqlite不支持并发,
即便我们程序作了加锁机制依旧不能完全避免请求过快时同时读写操作
