### ISSUE TITLE
I lost menu

### ISSUE THREAD

**Issue by jmruas** [kalcaddle/KodExplorer#447]
I lost the side menu (Desktop...)
How can I solve this?
Thank you.

**Comment by kalcaddle** [comment]
kodexplorer:  copy data/system/day/xxx/* to data/system.
kodbox: restore your database backup;

**Comment by jmruas** [comment]
Thank you.
I installed in a new folder too see how to do the original menu. Now it's easy if I lost it again. 
The problem is to answer this: why I lost the menu?
