### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by jmruas** [kalcaddle/KodExplorer#448]
I want to translate KodCloud into Portuguese. Can someone tell me where/how to do this? Thank you.

**Comment by devilAPI** [comment]
Its under config/i18n/.

Please close this issue now.

**Comment by jmruas** [comment]
There are two Portuguese language: European Portuguese (pt_PT) and Brazilien Portuguese (pt_BR).
KodBox shows an error, because the flag is from European Portuguese and the language is Brazilien. 
European Portuguese does not exists and I would like to create it for future normal update like others languages.

**Comment by devilAPI** [comment]
Translate either both of them or the one youre from, if ure living in Portugal, do the pt_PT and if ur livin in Barazil, translate pt_BR. If u're not living in brazil or in portugal, translate pt_PT

**Comment by jmruas** [comment]
Thank you. 
I don't know how to create a pull request. It's not user friendly.

**Comment by jmruas** [comment]
Can you please add this two files (pt_PT is inside pt-PT folder and pt_BR inside pt-BR folder)?

[pt.zip](https://github.com/kalcaddle/KodExplorer/files/5874031/pt.zip)

**Comment by devilAPI** [comment]
@jmruas 
> I don't know how to create a pull request. It's not user friendly.
Please watch a tutorial or contact me on discord for further help -> devilAPI#7980

> I saw now this is about KodExplorer, not KodBox (that I use).
Im gonna search for the files in KodBox and then tell you where the language files are located.

> Can you please add this two files (pt_PT is inside pt-PT folder and pt_BR inside pt-BR folder)?
I will try, as i said i never heard something of KodBox and i have to look at it first.

**Comment by devilAPI** [comment]
I dont really know what you mean by "Can you please add this two files (pt_PT is inside pt-PT folder and pt_BR inside pt-BR folder)?" There are already files in the zip file.

**Comment by jmruas** [comment]
> https://github.com/bobby285271/kodbox
> 
> This one?

Yes!

> I dont really know what you mean by "Can you please add this two files (pt_PT is inside pt-PT folder and pt_BR inside pt-BR folder)?" There are already files in the zip file.

The files in the zip file are pt_PT and pt_BR translations. They are inside the appropriate folders in the zip file.

In this moment the tree is:
\i18n
|
\pt
|-- index.php

After now it must be:
1.
\i18n
|
\pt-PT
|-- index.php

2.
\i18n
|
\pt-BR
|-- index.php

then the folder \i18n\pt must be deleted.

Thank you for your great attention!
