### ISSUE TITLE
FRP穿透后无法访问含大文件的目录

### ISSUE THREAD

**Issue by Pyrokine** [kalcaddle/KodExplorer#449]
1、使用【https://github.com/dennischancs/kodexplorer】的docker镜像，系统是树莓派Debian10.6，部署后能够正常访问含有多个大文件的文件夹，但是在用FRP穿透后，访问此类文件夹会长时间无响应，然后弹出【Ajax Error】，内容为请求页面的Response，即【{ "code": true, "use_time": 0.05815005302429199……】，即获得了结果但是会卡死且无法呈现，【Timing】中【TTFB】仅有几十毫秒到数百毫秒，但【Content Download】会长达半分钟，在增加了Nginx的超时至十分钟后，能一直无响应十分钟直到超时，然后显示【net::ERR_CONNECTION_RESET】
2、在1的问题基础上尝试了更换了端口、启用FRP的KCP、更换为NPS穿透、检查MTU、手动部署Nginx-1.14.2、手动部署PHP7.3-FPM、提高所有超时和大小限制，均无法解决问题
3、尝试使用PHP8.0-FPM，但直接提示【Parse error: syntax error, unexpected token "match", expecting "(" in kodexplorer/app/function/common.function.php on line 762】，无法打开网页

**Comment by Pyrokine** [comment]
补充：
和文件大小无关，和数量有关，当一个文件夹内有15个左右的文件（或文件夹）时，就能复现，但在增大nginx和fpm的限制之后没有得到改善
client_header_buffer_size 32k;
large_client_header_buffers 4 128k;
client_max_body_size 500M;        
client_header_timeout 3600s;
client_body_timeout 3600s;

fastcgi_buffers 8 32K; 
fastcgi_buffer_size 32K;
fastcgi_connect_timeout 3600s;
fastcgi_send_timeout 3600s;
fastcgi_read_timeout 3600s;

proxy_connect_timeout 90;
proxy_send_timeout 90;
proxy_read_timeout 90;
proxy_buffer_size 32k;
proxy_buffers 32 32k;
proxy_busy_buffers_size 64k;

**Comment by kalcaddle** [comment]
这个和kod本身没啥关系, kod没做任何相关限制. 
应该还是网络或相关配置引起超时或其他什么原因.
