### ISSUE TITLE
php错误提示？

### ISSUE THREAD

**Issue by xirwajim** [kalcaddle/KODExplorer#45]
为什么在config里面打开了php错误提示？还是发布版本的时候忘记了修改？一些提示没有正常显示了。
@ini_set("display_errors","on");

**Comment by kalcaddle** [comment]
kod运行在各种机器或环境下，难免会遇到一些兼容问题。开启是为了收集错误容易定位。
关闭了某些用户反馈出错但很难逐个定位。

当然可以自行关闭

**Comment by xirwajim** [comment]
ok
