### ISSUE TITLE
kodexplorer可用的安卓旧版本app貌似没有下载地址了

### ISSUE THREAD

**Issue by WriteMemory** [kalcaddle/KodExplorer#452]

**Comment by kalcaddle** [comment]
官网下载页面有



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: WriteMemory <notifications@github.com&gt;
发送时间: 2020年10月21日 20:29
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] kodexplorer可用的安卓旧版本app貌似没有下载地址了 (#452)

**Comment by WriteMemory** [comment]
官网指向小米商城的可道云1.0.3是针对kodbox的，kodexplorer使用登录会报错，只有1.0.0版本正常，IOS上的AppStore就有可道云和KodExplorer之分

**Comment by kalcaddle** [comment]
注意页面右侧kodexplorer配套APP，豌豆荚上面的安卓版本



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: WriteMemory <notifications@github.com&gt;
发送时间: 2020年10月21日 21:18
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: warlee <824691958@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] kodexplorer可用的安卓旧版本app貌似没有下载地址了 (#452)






官网指向小米商城的可道云1.0.3是针对kodbox的，kodexplorer使用登录会报错，只有1.0.0版本正常，IOS上的AppStore就有可道云和KodExplorer之分
