### ISSUE TITLE
/var/www/kod/data/session/下的sess_*文件数量不断增加

### ISSUE THREAD

**Issue by xuefy** [kalcaddle/KodExplorer#453]
版本：kodexplorer 4.40
最近突然发现服务器的CPU占用总是很高，然后检查发现是由于/var/www/kod/data/session/下的sess_*文件数量不断增长，而php定时去给这些文件设置权限导致了CPU占用高。
新增的sess_*文件的内容全是“kod|i:1;”。
发现的时候文件数量已经十几万了，全部删除以后，文件还是会不断的新增出来。
昨天到今天大概十六个小时新增了两千五百多个文件。
这个会是什么原因导致的？应该怎么解决呢？ @kalcaddle

**Comment by kalcaddle** [comment]
session文件,php自带逻辑自己生成,属正常现象; 
自行百度session文件作用(维持每个访问用户会话状态)

文件数量: 取决于访问用户数; 什么时候删除取决于session过期时间

**Comment by xuefy** [comment]
session过期时间用是指config\config.php中的@ini_set('session.cache_expire',1800);吗？
昨天修改1800为30未见效果。

**Comment by kalcaddle** [comment]
修改只影响修改之后的; 
现有配置基本是最佳组合. 不建议修改,
/data/session/ 文件夹可以直接删除的(所有已登录用户会全部退出)

**Comment by xuefy** [comment]
我的kod是放在家里nas上的，而且非80、443端口，本意是仅自己使用。十几万的session完全不在预期内，还有其他的可能性吗？

**Comment by kalcaddle** [comment]
如果访问不正常的话,可能是被攻击了. 
检查webserver 请求日志;

**Comment by xuefy** [comment]
谢谢。我打开日志观察。

**Comment by xuefy** [comment]
从目前看到的日志来看。应该是共享给朋友的文件导致的，估摸着是他用的下载工具什么的泄漏了链接，导致大量的用户接入。
