### ISSUE TITLE
The public network access is normal, but the LAN (intranet) access error is reported

### ISSUE THREAD

**Issue by sidpixel** [kalcaddle/KodExplorer#454]
Brother,Could you  help me  find out what caused this.
Phenomenon: Through port mapping to the public network, the public network can be accessed normally; but when the LAN address is accessed, the login page is displayed abnormally and cannot be logged in;
Preliminary analysis: Preliminary analysis found that all xx.js files accessed through the intranet are garbled (see Figure 3), and the contents of these xx.js files can be read normally when accessed through the public network;
Environment: The above operations are all performed on the same PC, app version 4.4，and the cache has been completely cleared, PHP has been restarted many times, and the above exceptions have occurred.

Figure 1：lan access
<img width="2261" alt="Screen Shot 2020-11-01 at 23 10 21" src="https://user-images.githubusercontent.com/45841651/97806644-b6f3c300-1c97-11eb-87f8-9963ee9ae2c5.png">

Figure 2：wan access
<img width="748" alt="Screen Shot 2020-11-01 at 22 58 21" src="https://user-images.githubusercontent.com/45841651/97806573-303ee600-1c97-11eb-8557-9ac88000a9fa.png">

Figure 3：scramble code
<img width="1169" alt="Screen Shot 2020-11-01 at 23 13 15" src="https://user-images.githubusercontent.com/45841651/97806691-e99dbb80-1c97-11eb-819b-8c4fc7f22ee6.png">

**Comment by kalcaddle** [comment]
The js file is incomplete, check whether it is compressed by cdn acceleration and other similar tools, which may cause the code to run abnormally.
