### ISSUE TITLE
How to hide the folders with the prefix "@" in Synology Disk Station

### ISSUE THREAD

**Issue by kx001001** [kalcaddle/KodExplorer#455]
In Synology file system, there are lot of folder with prefix "@", this folders are supposed to be used by Synology itself. In normal cases, they are not necessary to display in KodExplorer file manager, but I can't find a way to exclude such folders with a wildcard.

**Comment by schnautz** [comment]
Good news! This is possible. In my case I had a lot of @eaDir folders showing, and I was able to hide them with the "Directory Exclusions" setting.

![image](https://user-images.githubusercontent.com/8277193/110394300-d168ef00-8031-11eb-8b3e-8410953fed02.png)
