### ISSUE TITLE
Problem with installation on Xampp

### ISSUE THREAD

**Issue by ThunderAGW** [kalcaddle/KodExplorer#456]
When I tried to run KodExplorer on XAMPP(Windows 10) I got this error:
![image](https://user-images.githubusercontent.com/64533301/99111584-a6313e80-2601-11eb-9eb2-02089e338a5f.png)

After some tries, I found out that this problem is from the define.php file in ./config/ , so I deleted the file and KodExplorer worked just fine. looks like the file overrides the data path to one that doesn't work.
At first I thought it's just me but then my friends reported this problem as well and the solution worked for them too. So I opened this issue.
Tnx for your awesome work!

**Comment by prasadbobby** [comment]
Hey hi is this now working on your PC

**Comment by ThunderAGW** [comment]
@prasadbobby 
Yo! After deleting define.php in ./config/ it works fine.

**Comment by prasadbobby** [comment]
Okay thank you
