### ISSUE TITLE
feature request - bulk rename files

### ISSUE THREAD

**Issue by themago** [kalcaddle/KodExplorer#457]

**Comment by kalcaddle** [comment]
please use kodbox
http://kodcloud.com



发自我的iPhone


------------------ Original ------------------

**Comment by themago** [comment]
thank you for the quick response but can you please tell me where I can bulk rename files using kodcloud?

**Comment by kalcaddle** [comment]
download here


https://kodcloud.com/download

发自我的iPhone


------------------ Original ------------------

**Comment by kalcaddle** [comment]
please use kodbox
http://kodcloud.com



发自我的iPhone


------------------ Original ------------------
