### ISSUE TITLE
有计划支持BOS/OSS等云存储吗?

### ISSUE THREAD

**Issue by ragnaroks** [kalcaddle/KODExplorer#46]
如题,百度的BAE和阿里的ACE部署后,默认使用临时空间,用户填入相应的云存储地址和key后切换到管理云存储.
目前Kodexplorer满足了作为一个文件管理器的大部分功能,但是使用云存储会是未来主流.

**Comment by kalcaddle** [comment]
后续会加入存储模块进行管理；
比如说添加其他kod，ftp，oss，或者webdav等；之间可以相互通信访问；


可以应用于各种场景。甚至是企业集群的管理。

**Comment by ragnaroks** [comment]
GJ,我们目前的项目就需要一个文件管理系统去管理BOS上面的文件,目前是我自己写的,但是问题是去操作文件的人是完全不懂技术的,他基本用不好...
希望Kodexplorer继续发展成为一个超功能的文件管理器,那时候我们也可以考虑商业kodexplorer了.
