### ISSUE TITLE
markdown flowchart can not display

### ISSUE THREAD

**Issue by SarcoZ** [kalcaddle/KodExplorer#466]
bug: md file flowchart can not display
image url with https can not dispaly

**Comment by kalcaddle** [comment]
1. Need to add prefix; such as
```seq
Alice->Bob: Hello Bob, how are you?
Note right of Bob: Bob thinks
Bob-->Alice: I am good thanks!
```

2. You have to make sure that the picture can be accessed normally and that the anti-leech processing is not done
