### ISSUE TITLE
Search bug in v4.45

### ISSUE THREAD

**Issue by renat2985** [kalcaddle/KodExplorer#469]
White search in all dark themes.
![Firefox_2021-04-08 10-07-14@2x](https://user-images.githubusercontent.com/1230815/113983625-caace200-9852-11eb-9167-2a0f80096b97.jpg)

**Comment by kalcaddle** [comment]
Thanks for the feedback, we'll fix it in the next release

In addition, it is highly recommended that you use kodbox,   https://github.com/kalcaddle/kodbox
which is more powerful and easy to use

**Comment by renat2985** [comment]
> In addition, it is highly recommended that you use kodbox, https://github.com/kalcaddle/kodbox
> which is more powerful and easy to use

My server doesn't support MySQL.
