### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function init_config()

### ISSUE THREAD

**Issue by pasayev** [kalcaddle/KodExplorer#470]
Hello,

I'm getting following error:

Fatal error: Uncaught Error: Call to undefined function init_config() in /home/teknorcom/public_html/musteri/index.php:5 Stack trace: #0 {main} thrown in /home/teknorcom/public_html/musteri/index.php on line 5

**Comment by kalcaddle** [comment]
May be missing files, or no read and write permissions.
