### ISSUE TITLE
请教关于分享链接会自动消失的问题

### ISSUE THREAD

**Issue by sancome** [kalcaddle/KodExplorer#471]
分享的时候，到期时间留空，在大概一个星期之后，分享会自动消失，不知道什么原因。

**Comment by kalcaddle** [comment]
默认是永久有效的, 失效原因可能是你服务器目录结构调整了,缓存数据被清除等情况可能引起该问题.
推荐使用kodbox,分享等信息存入数据库,目录变更,站点迁移等情况都能自动处理.
