### ISSUE TITLE
doesnt work with .htaccess url re-write

### ISSUE THREAD

**Issue by ravi-beniwal** [kalcaddle/KodExplorer#472]
for last 5 day. I'm getting the below issues
1. with url-rewite htaccess, it doesnt work.
2. **err_connection_reset** while trying to access the explorer  after adding another htaccess to explorer base dir
as 
RewriteEngine Off
RewriteEngine On

**Comment by kalcaddle** [comment]
It depends on your own configuration

Kodexplorer does not affect this configuration
