### ISSUE TITLE
How to integrate custom php page into kodexplorer?

### ISSUE THREAD

**Issue by Gosokan** [kalcaddle/KodExplorer#477]
Hello,
I want to add custom php page into kodexplorer. As example: adding "phpinfo.php" or "some static php page". So this phpinfo.php or some static php page can only be accessed when logged into kodexplorer.

**Comment by kalcaddle** [comment]
you can add a file at kod folder. such phpinfo.php;

```
<?php
include ('config/config.php');
$app = new Application();
init_config();

if($_SESSION['kodLogin']){
	phpinfo();
}else{
	echo "not login";
}
```
