### ISSUE TITLE
onlyoffice预览文件名中有+或者%的文件失败

### ISSUE THREAD

**Issue by qiaogli** [kalcaddle/KodExplorer#478]
![image](https://user-images.githubusercontent.com/83851179/118214605-9c01d700-b4a2-11eb-8fb0-0eb6d61ed384.png)

![image](https://user-images.githubusercontent.com/83851179/118214249-f9495880-b4a1-11eb-9d7a-6bfcb1b5692b.png)
这个是文件名中有%
![image](https://user-images.githubusercontent.com/83851179/118214279-08300b00-b4a2-11eb-9686-2b5d2ad73fe4.png)
![image](https://user-images.githubusercontent.com/83851179/118214497-69f07500-b4a2-11eb-931c-774b8c25fca0.png)
+号的是先让你选编码，选完打开是空白的

**Comment by kalcaddle** [comment]
后续优化.
