### ISSUE TITLE
Potential security  vulnerabilities 

### ISSUE THREAD

**Issue by x3rz** [kalcaddle/KodExplorer#481]
Hello @kalcaddle I have found potential security vulnerabilities in your project which needs to get address please visit and check them

https://www.huntr.dev/bounties/22-kalcaddle/KodExplorer/
https://www.huntr.dev/bounties/21-kalcaddle/KodExplorer/
http://huntr.dev/bounties/20-kalcaddle/KodExplorer/
https://www.huntr.dev/bounties/19-kalcaddle/KodExplorer/
http://huntr.dev/bounties/18-kalcaddle/KodExplorer/
https://www.huntr.dev/bounties/11-kalcaddle/KodExplorer/
https://www.huntr.dev/bounties/10-kalcaddle/KodExplorer/

Regards,
x3rz

**Comment by kalcaddle** [comment]
Thanks,we will fixed it soon.

**Comment by x3rz** [comment]
Thank you sir for validating the report but there is one left that I personally feel is a potential vector please have a look.

https://www.huntr.dev/bounties/11-kalcaddle/KodExplorer/
