### ISSUE TITLE
4.46版本更新了看不到里面的文件了

### ISSUE THREAD

**Issue by 531014023** [kalcaddle/KodExplorer#484]
RT
![111](https://user-images.githubusercontent.com/22349094/125557781-8099e0ea-9ec3-4f5b-8484-aedbf7fb7b55.png)
![222](https://user-images.githubusercontent.com/22349094/125557791-8523eb51-6bbc-4a13-9ea9-e7d8686d7267.png)

**Comment by kalcaddle** [comment]
没发现该问题，外网的话提供一个地址和管理员账号我们测试一下


------------------ 原始邮件 ------------------
发件人: duyong ***@***.***&gt;
发送时间: 2021年7月14日 11:45
收件人: kalcaddle/KodExplorer ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484)





 
RT

**Comment by 531014023** [comment]
http://yunpan.93dd.top/
admin
dy15228164421!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kalcaddle/KodExplorer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 中午11:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484)





 没发现该问题，外网的话提供一个地址和管理员账号我们测试一下 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: duyong ***@***.***&amp;gt; 
 发送时间: 2021年7月14日 11:45 
 收件人: kalcaddle/KodExplorer ***@***.***&amp;gt; 
 抄送: Subscribed ***@***.***&amp;gt; 
 主题: 回复：[kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484) 
 
 
 
 
 
   
 RT

**Comment by 531014023** [comment]
F12是有报错
![333](https://user-images.githubusercontent.com/22349094/125558335-fde2d844-6174-4add-a9a6-030cd6cc45d4.png)

**Comment by kalcaddle** [comment]
你好
没有发现问题啊


你提供一下浏览器具体版本.


 原始邮件 
发件人: ***@***.***>
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
发送时间: 2021年7月14日(周三) 11:52
主题: Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484)


F12是有报错

**Comment by 531014023** [comment]
我换了Edage就没这个问题 但是在chrome上就不行







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kalcaddle/KodExplorer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 中午1:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484)





 你好
 没有发现问题啊
 
 
 你提供一下浏览器具体版本.
 
 
  原始邮件 
 发件人: ***@***.***&gt;
 收件人: ***@***.***&gt;
 抄送: ***@***.***&gt;; ***@***.***&gt;
 发送时间: 2021年7月14日(周三) 11:52
 主题: Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484)
 
 
 F12是有报错

**Comment by kalcaddle** [comment]
chrome版本号是多少, 我们就是用chrome测试的,你的网站就没有这个问题.
 原始邮件 
发件人: ***@***.***>
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
发送时间: 2021年7月14日(周三) 13:35
主题: Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484)


我换了Edage就没这个问题 但是在chrome上就不行 
 
 
 
 
 
 
 
 ------------------&nbsp;原始邮件&nbsp;------------------ 
 发件人: "kalcaddle/KodExplorer" ***@***.***&gt;; 
 发送时间:&nbsp;2021年7月14日(星期三) 中午1:23 
 ***@***.***&gt;; 
 ***@***.******@***.***&gt;; 
 主题:&nbsp;Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484) 
 
 
 
 
 
 你好 
 没有发现问题啊 
 
 
 你提供一下浏览器具体版本. 
 
 
 原始邮件 
 发件人: ***@***.***&gt; 
 收件人: ***@***.***&gt; 
 抄送: ***@***.***&gt;; ***@***.***&gt; 
 发送时间: 2021年7月14日(周三) 11:52 
 主题: Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484) 
 
 
 F12是有报错

**Comment by 531014023** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kalcaddle/KodExplorer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 中午1:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484)





 chrome版本号是多少, 我们就是用chrome测试的,你的网站就没有这个问题.
  原始邮件 
 发件人: ***@***.***&gt;
 收件人: ***@***.***&gt;
 抄送: ***@***.***&gt;; ***@***.***&gt;
 发送时间: 2021年7月14日(周三) 13:35
 主题: Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484)
 
 
 我换了Edage就没这个问题 但是在chrome上就不行 
  
  
  
  
  
  
  
  ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
  发件人: "kalcaddle/KodExplorer" ***@***.***&amp;gt;; 
  发送时间:&amp;nbsp;2021年7月14日(星期三) 中午1:23 
  ***@***.***&amp;gt;; 
  ***@***.******@***.***&amp;gt;; 
  主题:&amp;nbsp;Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484) 
  
  
  
  
  
  你好 
  没有发现问题啊 
  
  
  你提供一下浏览器具体版本. 
  
  
  原始邮件 
  发件人: ***@***.***&amp;gt; 
  收件人: ***@***.***&amp;gt; 
  抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt; 
  发送时间: 2021年7月14日(周三) 11:52 
  主题: Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484) 
  
  
  F12是有报错

**Comment by 531014023** [comment]
抱歉 好像不是浏览器的问题，我把所有的chrome插件关闭就恢复了，应该是插件的问题，但是也没办法复现是哪个插件出问题，因为我再次全部打开插件也没有问题了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kalcaddle/KodExplorer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 中午1:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484)





 chrome版本号是多少, 我们就是用chrome测试的,你的网站就没有这个问题.
  原始邮件 
 发件人: ***@***.***&gt;
 收件人: ***@***.***&gt;
 抄送: ***@***.***&gt;; ***@***.***&gt;
 发送时间: 2021年7月14日(周三) 13:35
 主题: Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484)
 
 
 我换了Edage就没这个问题 但是在chrome上就不行 
  
  
  
  
  
  
  
  ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
  发件人: "kalcaddle/KodExplorer" ***@***.***&amp;gt;; 
  发送时间:&amp;nbsp;2021年7月14日(星期三) 中午1:23 
  ***@***.***&amp;gt;; 
  ***@***.******@***.***&amp;gt;; 
  主题:&amp;nbsp;Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484) 
  
  
  
  
  
  你好 
  没有发现问题啊 
  
  
  你提供一下浏览器具体版本. 
  
  
  原始邮件 
  发件人: ***@***.***&amp;gt; 
  收件人: ***@***.***&amp;gt; 
  抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt; 
  发送时间: 2021年7月14日(周三) 11:52 
  主题: Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484) 
  
  
  F12是有报错

**Comment by 531014023** [comment]
再次测试了一遍 发现是油猴脚本的问题






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kalcaddle/KodExplorer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 中午1:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484)





 chrome版本号是多少, 我们就是用chrome测试的,你的网站就没有这个问题.
  原始邮件 
 发件人: ***@***.***&gt;
 收件人: ***@***.***&gt;
 抄送: ***@***.***&gt;; ***@***.***&gt;
 发送时间: 2021年7月14日(周三) 13:35
 主题: Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484)
 
 
 我换了Edage就没这个问题 但是在chrome上就不行 
  
  
  
  
  
  
  
  ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
  发件人: "kalcaddle/KodExplorer" ***@***.***&amp;gt;; 
  发送时间:&amp;nbsp;2021年7月14日(星期三) 中午1:23 
  ***@***.***&amp;gt;; 
  ***@***.******@***.***&amp;gt;; 
  主题:&amp;nbsp;Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484) 
  
  
  
  
  
  你好 
  没有发现问题啊 
  
  
  你提供一下浏览器具体版本. 
  
  
  原始邮件 
  发件人: ***@***.***&amp;gt; 
  收件人: ***@***.***&amp;gt; 
  抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt; 
  发送时间: 2021年7月14日(周三) 11:52 
  主题: Re: [kalcaddle/KodExplorer] 4.46版本更新了看不到里面的文件了 (#484) 
  
  
  F12是有报错

**Comment by kalcaddle** [comment]
部分浏览器兼容问题,已兼容并推送了更新.
