### ISSUE TITLE
通过 外链分享 文件夹，全局搜索这个 文件夹内的文件名 显示 您没有此权限，请联系管理员

### ISSUE THREAD

**Issue by GaryYou93** [kalcaddle/KodExplorer#487]
你好，通过 外链分享 文件夹，全局搜索这个 文件夹内的文件名 显示 您没有此权限，请联系管理员，请问这是什么问题，demo演示是可以的，谢谢！
![QQ截图20210811140037](https://user-images.githubusercontent.com/79907634/128977383-f7e498f4-30a5-4c27-9b1d-5f4d9e79a64e.jpg)
![QQ截图20210811140015](https://user-images.githubusercontent.com/79907634/128977387-b7d08dd5-8368-4adb-a1a1-6f845281611e.jpg)

**Comment by kalcaddle** [comment]
一个兼容问题, 已修复,下个版本更新.
