### ISSUE TITLE
怎么修改

### ISSUE THREAD

**Issue by 362227** [kalcaddle/KodExplorer#489]
离线下载，我想离线这种 https://123.com/dl.php?id=https://www.youtube.com/watch?v=n9q0iMcWWpA

但我的要求是贴youtube地址就可以，是长期使用哦。修改哪个文件，怎么修改

**Comment by 362227** [comment]
另外怎么禁掉登陆？公共用的，就是中转文件用的

**Comment by 362227** [comment]
离线的搞定了，禁掉登陆怎么禁

**Comment by kalcaddle** [comment]
外链分享文件夹, 访问者不需要登陆.
