### ISSUE TITLE
4.46版本在ubuntu20.04上极高的CPU使用率问题

### ISSUE THREAD

**Issue by ovonvm** [kalcaddle/KodExplorer#491]
如题，运行环境是aws ec2 ubuntu20.04 apache2.4+php7.2  官方apt包安装的。每次有URL请求CPU直接到100% 测试了两台小鸡都是这样。麻烦大佬瞅瞅是不是哪里有问题。

**Comment by ovonvm** [comment]
是请求kodexploer里面的链接 就会100%拉满 然后卡顿一会

**Comment by kalcaddle** [comment]
没遇到过该问题, 应该是服务器配置问题, 不熟悉可以使用宝塔面板一键搭建.
