### ISSUE TITLE
打开文件列表 出现io_file_meta:fileInfoMore;长度超出最大限制!(65536)

### ISSUE THREAD

**Issue by laozl** [kalcaddle/KodExplorer#494]
您好,我有一个文件夹里面文件比较多,然后双击打开的时候 就出现了 "io_file_meta:fileInfoMore;长度超出最大限制!(65536)",现在文件夹里面的内容我看不了,另外用webdav挂载那个目录后 那个文件夹显示为空

**Comment by kalcaddle** [comment]
自动读取图片exif或其他相关信息并存储时出错了.(读取的信息过长)
后面版本兼容一下.
