### ISSUE TITLE
文件名不合理

### ISSUE THREAD

**Issue by jiemo9527** [kalcaddle/KodExplorer#496]
最新版本中，添加相似文件名会被添加一串字符，相当不合理但又无法消除

'青瓷01 [AtkJSZHmJt0].mp4'  '青瓷21[eBeZZnqo7PM].mp4'
'青瓷02[VLdwct6TP7Y].mp4'   '青瓷22[T68c2188bao].mp4'
'青瓷03[AJWUdjezhto].mp4'   '青瓷23[qwEz-fkAvlw].mp4'
'青瓷04[lxuMvqXRGY4].mp4'   '青瓷24[2WNw10gryMo].mp4'
'青瓷05[3cdW0hvHiIo].mp4'   '青瓷25[_MkLloLCAXw].mp4'
'青瓷06[beBz2w_4834].mp4'   '青瓷26[Gvp2FYYgHjA].mp4'
'青瓷07[3I_l_qnF5RQ].mp4'   '青瓷27[hL1A-rHOy_g].mp4'
'青瓷08[Utf1KqnGuiA].mp4'   '青瓷28[o0sEZU2mrlg].mp4'
'青瓷09[TWL-2p_gE3Y].mp4'   '青瓷29[lZhIaTQAMy4].mp4'
'青瓷10[qXjCpwD_Xq4].mp4'   '青瓷30[V807p2O29Dw].mp4'
'青瓷11[1SpXAgl-_6w].mp4'   '青瓷31[nvwXeT-ceoo].mp4'
'青瓷12[UiLaoIPMBTs].mp4'   '青瓷32[CnGWsMPRj6M].mp4'
'青瓷13[b8L_0T2V4d0].mp4'   '青瓷33[CMp7l9y14yQ].mp4'
'青瓷14[TjPIwGH70cY].mp4'   '青瓷34[_pTRMQadxDY].mp4'
'青瓷15[_u36cU2T1xE].mp4'   '青瓷35[0h3_HseWucM].mp4'
'青瓷16[i34fLKsLeYA].mp4'   '青瓷36[poyiwDbyjMU].mp4'
'青瓷17[QapTnylyYoM].mp4'   '青瓷37[i5NByYmLUnw].mp4'
'青瓷18[GxwSZV_rv7s].mp4'   '青瓷38[4Mw2pwdqraI].mp4'
'青瓷19[WGZppl9MBDA].mp4'   '青瓷39[uSclEJNE4sA].mp4'
'青瓷20[ceFnkVXRskI].mp4'   '青瓷40[MdpJ8yjbOY4].mp4'

**Comment by kalcaddle** [comment]
你好,没有测试出该情况. 烦请描述一下具体操作步骤,谢谢.

**Comment by jiemo9527** [comment]
不是网盘的问题，是yt-dlp的问题 可忽略。
