### ISSUE TITLE
“版权或网站备案号”选项中带a标签时存在bug

### ISSUE THREAD

**Issue by Windelight** [kalcaddle/KodExplorer#498]
如图，如果加上A标签，会打穿输入框。
经测试KodBox无此问题(我也是看了kodbox才把kodexplorer加上标签的)

![image.png](https://s2.loli.net/2022/01/25/RKBu3A1y6QP4ODV.png)

**Comment by kalcaddle** [comment]
kodexplorer 不再开发新功能及特性.
推荐使用kodbox.
