### ISSUE TITLE
能否提供proxy配置，更新不了，怀疑是网络连不上github

### ISSUE THREAD

**Issue by jay763190097** [kalcaddle/KodExplorer#499]
如果更新的时候，能提供proxy配置就好了

**Comment by jay763190097** [comment]
系统手动下载更新包，更新好了，但是插件安装，还是有这个问题，如果可以proxy就能解决了。

**Comment by jay763190097** [comment]
![微信图片_20220330232144](https://user-images.githubusercontent.com/16317178/160871354-c990a9e3-1361-4b78-aa7a-f23745fd6b76.jpg)
http://kodcloud.yuzhi88.cn:9000/地址有啥问题呢

**Comment by kalcaddle** [comment]
App使用错了; 

kodbox和kodexplorer是两个产品; 对应两个App
kodexplorer - 对应kodexplorer; (服务端及App已不再维护, )
kodbox--对应App为"可道云"

**Comment by kalcaddle** [comment]
App使用错了; 

kodbox和kodexplorer是两个产品; 对应两个App
kodexplorer - 对应kodexplorer; (服务端及App已不再维护, )
kodbox--对应App为"可道云"
