### ISSUE TITLE
data.bin存在权限漏洞

### ISSUE THREAD

**Issue by caotao94** [kalcaddle/KodExplorer#502]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/31203266/162891335-35cd384a-8936-46e8-bfa6-c6cd194e6f6b.png">

**Comment by kalcaddle** [comment]
误判，忽略即可


------------------ 原始邮件 ------------------
发件人: caotao94 ***@***.***&gt;
发送时间: 2022年4月12日 14:03
收件人: kalcaddle/KodExplorer ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kalcaddle/KodExplorer] data.bin存在权限漏洞 (Issue #502)
