### ISSUE TITLE
PHP 8.1.2 运行出错

### ISSUE THREAD

**Issue by mnixry** [kalcaddle/KodExplorer#503]
```
Fatal error: Cannot acquire reference to $GLOBALS in /var/www/kod-explorer/app/function/web.function.php on line 753
```

**Comment by dovellous** [comment]
Prior to PHP 8.1, it was possible to create a reference to $GLOBALS array, and modify that reference. All changes would then be reflected in the global variables as well. From PHP 8.1, it is no longer allowed to create references to $GLOBALS variable. Further, it is no longer allowed to pass $GLOBALS to a function that expects a parameter by-reference.

**Comment by kalcaddle** [comment]
4.48: fixed.

**Comment by mnixry** [comment]
感谢您修复此问题

但是在我`git pull`拉取目前`master`分支最新的代码之后, 出现了新的错误:

```
Fatal error: Uncaught Error: Undefined constant "ACT" in /var/www/kod-explorer/app/function/helper.function.php:428 Stack trace: #0 /var/www/kod-explorer/app/function/helper.function.php(345): user_logout() #1 /var/www/kod-explorer/config/config.php(111): init_common() #2 /var/www/kod-explorer/index.php(3): include('...') #3 {main} thrown in /var/www/kod-explorer/app/function/helper.function.php on line 428
```

**Comment by kalcaddle** [comment]
已兼容处理.

**Comment by mnixry** [comment]
> 已兼容处理.

感谢，已能正常工作
