### ISSUE TITLE
外链分享页面 搜索结果列表 文件路径错误

### ISSUE THREAD

**Issue by mefgadah** [kalcaddle/KodExplorer#506]
![Snipaste_2022-05-14_17-47-42](https://user-images.githubusercontent.com/9023817/168420601-b54a4cf2-661a-4c70-9ba9-c8dacb226b11.png)

**Comment by mefgadah** [comment]
kodbox  V1.30.03

**Comment by kalcaddle** [comment]
没测试出该问题, 麻烦提供一下详细信息: 外链分享存储类型.
如果是onedrive的话最近插件修复了一个目录兼容问题, 看看是否升级了.
方便的话在提供个站点和账号我们看看  warlee#kodcloud.com

另外,kodbox的问题请发到kodbox下面.
