### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by anh-ai** [kalcaddle/KodExplorer#508]
How can I save content of files with UTF-8 coding?
Now, when I code Vietnamese character like: `Xin chào, tôi là Tuấn Anh` in to a PHP, HTML, MD,... files, after I saved, closed, reopen, it become: `Xin ch?o, t?i l? Tu?n Anh`

**Comment by kalcaddle** [comment]
same as: https://github.com/kalcaddle/kodbox/issues/118
