### ISSUE TITLE
【数据丢失】在群晖NAS使用 KodExplorer 

### ISSUE THREAD

**Issue by FloatingGuy** [kalcaddle/KodExplorer#511]
群晖 DSM6.0 升级到 DSM 7.0 后，KodExplorer 中的数据丢失。

KodExplorer  4.40-2019 版本（DSM升级前后版本未变）
基础依赖库做了升级 PHP，apach 

丢失的数据目录：/web/kodexplorer/data/

**Comment by kalcaddle** [comment]
这得看群晖升级做了什么, 是不是该目录被移走或重命名了.
kod本身肯定不会移动或做相关操作. 

如果是移走了,可以重新在kod中配置到新的目录, 或者移回原来的目录结构.
