### ISSUE TITLE
回收站中没有恢复按钮

### ISSUE THREAD

**Issue by NcyWindelight** [kalcaddle/KodExplorer#515]
KodBox和KodExplorer双持用户，版本4.50，发现KodExplorer在文件被删除之后无法直接恢复，只能剪切 粘贴的间接方法
![image](https://user-images.githubusercontent.com/116828155/207050569-9ad7845b-e278-403b-962f-837a07004810.png)

希望与KodBox的操作逻辑进行同步。

**Comment by kalcaddle** [comment]
可以通过剪切粘贴完成还原操作. 
目前kodexplorer处于维护阶段(解决bug或相关安全问题),不再做功能更新
