### ISSUE TITLE
发现controller/explorer.class.php一个bug

### ISSUE THREAD

**Issue by wish5115** [kalcaddle/KodExplorer#518]
代码位置：app/controller/explorer.class.php:1153
$saveFile = $savePath._DIR_CLEAR($filename);
这行代码有一个bug，当存储路径$savePath不存在时，系统会自动创建，但刚创建的文件夹，导致$savePath的路径少了"/"，那么，在调用$saveFile = $savePath._DIR_CLEAR($filename);这行代码时，$savePath会和后面的文件名连在一起导致下载文件路径错误。
比如：$savePath是 /aaa/bbb，$filename是1.jpg，那么这里会变成/aaa/bbb1.jpg，实际应该是/aaa/bbb/1.jpg

我通过：$saveFile = rtrim($savePath, '/').'/'._DIR_CLEAR($filename); 这样修改解决了，望官方能修复。

这里应该是_DIR这个函数bug导致的，可惜加密看不了，我在命令行直接发请求调用这个控制器的，通过web下载没发现问题，主要通过web都是在当前文件夹下载，也不存在新创建文件夹一说，哈哈哈。

**Comment by kalcaddle** [comment]
已兼容

**Comment by wish5115** [comment]
官方效率很高👍

**Comment by wish5115** [comment]
官方效率很高👍
