### ISSUE TITLE
为什么只能一个一个的上传？

### ISSUE THREAD

**Issue by bulesky89857** [kalcaddle/KodExplorer#521]
![image](https://user-images.githubusercontent.com/50124044/232241007-b3499e8e-41e4-43f2-b2c9-f7c978d6b993.png)

**Comment by bulesky89857** [comment]
设置完还是一个一个的上传？不知为什么

**Comment by kalcaddle** [comment]
大文件上传时会按分片大小分割成片上传(上述设置的5M)
并发指的是同时上传进程数量, 一个小文件,一个分片都属于一个进程; 所以如果一个文件比较大的时候看起来只有一个文件在上传,实际上是15个分片在上传.

**Comment by kalcaddle** [comment]
暂不支持.
