### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by horasjey** [kalcaddle/KodExplorer#524]
hallo,
i have isue
hot to solved it?
![image](https://github.com/kalcaddle/KodExplorer/assets/45363813/afa3821b-9401-4a1c-8fbe-c876f941423d)

**Comment by horasjey** [comment]
I have successfully resolved this problem, after I installed the required module,

but I have a new problem, I can't edit the file,
What is that because of?...?
![image](https://github.com/kalcaddle/KodExplorer/assets/45363813/520f1d31-cc79-4125-a1ad-9de6213c8379)

**Comment by kalcaddle** [comment]
file no permission;
chmod -Rf  777 /[kodfolderxxx]
