### ISSUE TITLE
编辑器无法粘贴内容

### ISSUE THREAD

**Issue by leafney** [kalcaddle/KodExplorer#527]
使用 kodExplorer 管理文件，创建了 `.txt` 或者 `.md` 文件来保存一些文本内容。复制内容过来粘贴会发现无法粘贴上内容。就是按下快捷键 `Command + V` 键之后没有反应。

但无法粘贴的情况还是偶发性的，有时候能粘贴上，有时候却不行。

粘贴不上的时候，多打开几次文件或者刷新浏览器，或者过一段时间，就好了。也可能仍然不行。

一开始以为是浏览器的问题，从最新版的 chrome换到了最新版的 edge ，仍然有问题。

希望官方可以看一下这个问题。

系统：Macos Sonnoma 14.1.1
KodExplorer: v4.51
Edge: 119.0.2151.72 
Chrome:  119.0.6045.199

**Comment by kalcaddle** [comment]
测试未发现该问题(win/mac:chrome/edge/360...  各个浏览器都测试,一切正常), 
确定输入光标是焦点状态.  偶然出现,排查一下是否系统安装了什么软件,对剪贴板做了什么处理,造成的吃冲突.

**Comment by leafney** [comment]
感谢。
