### ISSUE TITLE
Help me adminer Can not be opened

### ISSUE THREAD

**Issue by faizal21** [kalcaddle/KodExplorer#532]
Warning: Undefined array key "script" in /www/KodExplorer/plugins/adminer/adminer/index.php on line 171

Warning: Undefined array key "HTTP_X_FORWARDED_PREFIX" in /www/KodExplorer/plugins/adminer/adminer/index.php on line 171

Warning: Undefined array key "HTTPS" in /www/KodExplorer/plugins/adminer/adminer/index.php on line 171

Warning: session_cache_limiter(): Session cache limiter cannot be changed after headers have already been sent in /www/KodExplorer/plugins/adminer/adminer/index.php on line 171

Warning: session_name(): Session name cannot be changed after headers have already been sent in /www/KodExplorer/plugins/adminer/adminer/index.php on line 171

Warning: session_set_cookie_params(): Session cookie parameters cannot be changed after headers have already been sent in /www/KodExplorer/plugins/adminer/adminer/index.php on line 171

Warning: session_start(): Session cannot be started after headers have already been sent in /www/KodExplorer/plugins/adminer/adminer/index.php on line 171

Fatal error: Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /www/KodExplorer/plugins/adminer/adminer/index.php:20 Stack trace: #0 /www/KodExplorer/plugins/adminer/adminer/index.php(171): remove_slashes(Array, false) #1 {main} thrown in /www/KodExplorer/plugins/adminer/adminer/index.php on line 20

**Comment by kalcaddle** [comment]
adminer need update
