### ISSUE TITLE
版本已经更新到最新的了，但是app进入后还是一直说版本不是最新

### ISSUE THREAD

**Issue by Xingxiwei** [kalcaddle/KodExplorer#535]

**Comment by Xingxiwei** [comment]
app登录一致说版本一定要大于等于4.38，但是程序的版本已经4.52了

**Comment by kalcaddle** [comment]
检查一下服务器配置及版本号文件.
kodexplorer 及对应app不再更新,处于维护阶段. 推荐功能更完善的kodbox

**Comment by Xingxiwei** [comment]
kodbox没有详细教程阿，因为我用casaos装过不成功阿，那个文件请问在哪里查看呢？&nbsp;


Hey
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月27日(星期二) 下午2:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kalcaddle/KodExplorer] 版本已经更新到最新的了，但是app进入后还是一直说版本不是最新 (Issue #535)














 
检查一下服务器配置及版本号文件.
 kodexplorer 及对应app不再更新,处于维护阶段. 推荐功能更完善的kodbox

**Comment by kalcaddle** [comment]
https://kodcloud.com/download/
不熟悉服务器操作的, 推荐使用宝塔面板,应用中心可以一建部署.
