### ISSUE TITLE
移动版的文件管理中可以直接执行PHP

### ISSUE THREAD

**Issue by DapperX** [kalcaddle/KODExplorer#54]
移动端访问文件管理时点击PHP文件，该文件会被服务器执行，感觉比较危险，不知是bug还是feature

**Comment by kalcaddle** [comment]
由于限制了普通用户对php文件的上传，修改。
基本上没有什么安全性；古国知道地址，直接浏览器输入也是一样的

**Comment by kalcaddle** [comment]
由于限制了普通用户对php文件的上传，修改。
基本上没有什么安全性问题；如果知道地址，直接浏览器输入也是一样的
