### ISSUE TITLE
打开有很多文件的文件夹很慢

### ISSUE THREAD

**Issue by limeng0403** [kalcaddle/KODExplorer#58]
打开几百个文件的文件夹，打开速度很慢，怎么优化一下？

**Comment by kalcaddle** [comment]
_safasdfa_

**Comment by kalcaddle** [comment]
几百个不算多啊，如果是图片比较多的话，加载缩略图是会有一些影响。

**Comment by limeng0403** [comment]
希望可以测试一下，在一个文件夹下放入几百个图片文件，双击这个文件夹，文件列表空白要好久才能显示出来文件，之后再加载图片缩略图。加载缩略图慢我可以理解，服务器在美国，但是，列表空白好久，我觉得在交互上有点问题。

**Comment by kalcaddle** [comment]
新版本已经做了优化，可以下载后更新。
