### ISSUE TITLE
正常请求被认为恶意攻击

### ISSUE THREAD

**Issue by zhuo-jiejie** [kalcaddle/KODExplorer#61]
分享文件夹后, 获取文件列表, 如果文件夹中存在大量图片, 则会通过index.php?share/image代理显示图片, 造成短时间内请求数很大, 触发check_post_many()方法并发控制, 系统自动登出...

**Comment by kalcaddle** [comment]
可以先关闭该检查（直接返回）；
新版本已经做了优化。
