### ISSUE TITLE
手机用administrator账户打开时，打开文件显示的不是文件的内容

### ISSUE THREAD

**Issue by jainoo** [kalcaddle/KODExplorer#64]
手机用administrator账户打开时，打开文件显示的不是文件的内容，而是文件在网站上的链接。

**Comment by tutugreen** [comment]
没遇到这样的情况。。
截个图看看？

**Comment by jainoo** [comment]
@tutugreen 你好，这个没法发图片吧，我发在我的KOD里吧
下面是同一个文件不同账户用手机打开的样式：[administrator账户打开](http://code1.jaino.cn/index.php?share/file&user=admin&sid=HwyeAkUX)                  [default账户打开](http://code1.jaino.cn/index.php?share/file&user=admin&sid=gktjeKWs)

**Comment by tutugreen** [comment]
找不到文件（或没权限）？
另我手机以guest进入测试并没有还原该状况。

这个问题一直出现吗？
会不会是手机缓存？（尝试用隐身模式浏览）
试试用XAMPP搭建环境。

（PS；非官方，仅供参考。。。）

**Comment by jainoo** [comment]
@tutugreen 可能我没有说明白。不是找不到文件，手机上用administrator组的账户登录进去浏览一个文件相当于在浏览器打开这个文件的链接，比如内容是phpinfo();的php文件，打开会显示phpinfo的详细信息，而用default用户组打开则会显示这个文件的代码<?php phpinfo(); ?>

**Comment by kalcaddle** [comment]
Last version 3.34 , fix it
You can have a try.
