### ISSUE TITLE
Out of free space on server caused by KODEXPLORER

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KODExplorer#65]
Hi, today I went out of disk space on my server and after a long time trying to find the guilty one I discoreved it was KODEXPLORER.

For some reason, everytime a user removes a file, folder or anything from the server, KODEXPLORER does not actually remove the file, it moves it no another directory ""recycle bin". This effect is highly undersirable.

So I ask you: is there any configuration that I can turn on in order to prevent files from being move to recycle bin when the user deletes it?

**Comment by kalcaddle** [comment]
next version  we will add a options that you can turn it of.

**Comment by batata004** [comment]
glad :)

**Comment by kalcaddle** [comment]
Last version 3.34 , fix it
You can have a try.
