### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by jarisgv** [kalcaddle/KODExplorer#66]
Hello folks,
I'm just started with KODExplorer to attend some of my brazilian clients. 
So I had to translate it into portuguese (pt_BR) and I would like to share this with the community.
Regards from Brazil.
Jaris

![2016-05-02 13h01m32s](https://cloud.githubusercontent.com/assets/19142770/14959552/3eb949f6-1066-11e6-93b1-edaa1362cd72.png)

**Comment by kalcaddle** [comment]
Last version 3.34 , support pt_BR，
you can help us check it
