### ISSUE TITLE
下载文件夹或者压缩下载会出现文件名乱码

### ISSUE THREAD

**Issue by oralpst** [kalcaddle/KODExplorer#67]
软件部署在centos7上，单独下载一个文件不会出现文件名乱码，但是选择一个以上文件或者一个文件夹，软件会压缩下载，下载的包解压后会出现文件名乱码，文件内容是正常的。

**Comment by kalcaddle** [comment]
zip压缩，中文文件名会以当前系统编码进行压缩，解压到linux系统没问题，下载解压到windows乱码是必然现象。目前无解（操作系统都无解）

**Comment by kalcaddle** [comment]
新版本3.34已经优化，可以升级体验

**Comment by RockNHawk** [comment]
最新版还是有乱码呢
