### ISSUE TITLE
How to make kodexplorer open a specific path?

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KODExplorer#69]
Hi,

When I access this URL in my browser https://www.xxx.com/kodexplorer/index.php it shows the kodexplorer web file manager. It defaults to a specific folder in my system. But I would like to be able to pass a parameter to this URL and make kodexplorer open this directory when it loads. Something like this:

https://www.xxx.com/kodexplorer/index.php?open_path=/my/directory

How can I do this? And also, how can I make KOdexplorer open a file already in edition mode (with the nice rich editor)?

**Comment by kalcaddle** [comment]
1. Open a path, Like this:   index.php?explorer/index&path=/test/
2. Open a file,   Like this:  index.php?editor/edit&filename=/test/readme.txt


-----
   You can share a file or folder to other people.

**Comment by batata004** [comment]
@kalcaddle amazing, this was exactly what I was looking for. You have a really really really nice piece of work here, this library is amazing. It works great and you should publish more bug fixes and also gather people to help you develop this library. Your job is really great but it lacks documentation and fast bug fix releases. I wish I could help you in anything you want, I have long history PHP and web development and if you need any help I would be glad to give you back all the nice job you gave us.
