### ISSUE TITLE
3.1 自动更新失败

### ISSUE THREAD

**Issue by inhere** [kalcaddle/KODExplorer#7]
3.1 提示自动下载更新，但一直报下载失败。-- 我到data目录看了，又下载了有3.12 的zip文件。
对了，编辑器无法高亮。 请求的js 路径出错了

**Comment by kalcaddle** [comment]
你好，先检查一下kod安装目录，所有子目录需要写权限才能覆盖成功。
实在不行，手动覆盖解压覆盖一下吧。3.1自动更新有个bug
