### ISSUE TITLE
加载脚本走非http路线给网站带来安全隐患，有时无法正常使用

### ISSUE THREAD

**Issue by cxgreat2014** [kalcaddle/KODExplorer#70]
运营商http劫持投放广告遮盖使用区，同时给站点安全性带来很大问题，请解决，致谢。
Mixed Content: The page at 'https://xxxx/index.php' was loaded over HTTPS, but requested an insecure script 'http://static.kalcaddle.com/update/main.js?a=uuid_1465210131472_4009?ver=3.21'. This content should also be served over HTTPS.
index.php:1 Mixed Content: The page at 'https://xxxxx/index.php' was loaded over HTTPS, but requested an insecure script 'http://cache.gclick.cn/?d=8a6cd32cf507963871034a72f567860e&i=110.207.120.13…p://static.kalcaddle.com/update/main.js?a=uuid_1465210131472_4009?ver=3.21'. This content should also be served over HTTPS.
sea.js?ver=3.21:14Mixed Content: The page at 'https://xxxxx/index.php' was loaded over HTTPS, but requested an insecure script 'http://kalcaddle.com/tools/state/index.php?is_root=1&host=https%3A%2F%2Fxxxx%2F&version=3.21&sid=uuid_1465210131835_8438'. This content should also be served over HTTPS.

**Comment by kalcaddle** [comment]
感谢支持，新版本会解决这个问题，大概6月底发布。

**Comment by cxgreat2014** [comment]
额。。大概几月份发布？

**Comment by jiabing520a** [comment]
现在最新版也未解决

**Comment by cxgreat2014** [comment]
希望未来解决
