### ISSUE TITLE
Serious bug with kodexplorer

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KODExplorer#76]
Hi,
I have kodexplorer installed in 8 differenct server and in all of them it stopped working this week. Today I took sometime to install again it (downloading code from github) and the problem still remains. When I try to login with admin/admin I get this errors in my F12:

sea.js?ver=3.21:1 Uncaught SyntaxError: Invalid regular expression: missing /

index.php?user/login:42 Uncaught ReferenceError: seajs is not defined(anonymous function) @ index.php?user/login:42

What I really think strange is that this problem started happening in my server even without I update make any change to the KODEXPLORER itself.

**Comment by kalcaddle** [comment]
I didn't found any question about this.
maybe the file sea.js has been changed; or server configure problem.


you can give me your website url,let me have a check. email: kalcaddle@qq.com


our demo didn't have any question.
http://demo.kalcaddle.com/index.php?user/login

**Comment by batata004** [comment]
My friend, I just sent you a link of my server by mail, could you please take a look? The email subject is "Hi here is the link you asked".

Thank you so much!

**Comment by kalcaddle** [comment]
I have try your website,I found the file incomplete, sea.js miss part of source code.

==================
maybe you use some tools to compress the js file 
(it looks like delete the source comments with error.)

**Comment by batata004** [comment]
Hi!

I use CloudFlare (the largest CDN in the world) to minimize my server traffic cause it compress JS/CSS files. So as you say, it's probably a bug with CloudFlare, correct?

Thanks for your support and I will open a bug report at CloudFlare so they can look at it!

JUST TO MAKE IT CLEAR TO WHO HAVE THIS PROBLEM:

When CloudFlare compresses the file "http://static.kalcaddle.com/static3.3/js/lib/seajs/sea.js" it generates the file "http://quemfazsite.com.br/temp/administrar_arquivos/static/js/lib/seajs/sea.js" which is corrupted.

**Comment by batata004** [comment]
Just to keep you updated, I talked to cloudflare and they confirmed there was a difference in the files provided directed and inside their system! \o/ They said they are looking into this problem and will solve it in the next days.
