### ISSUE TITLE
中文文件名乱码hug

### ISSUE THREAD

**Issue by yovisun** [kalcaddle/KODExplorer#79]
在阿里云的弹性web托管中使用，php是5.2.17，中文文件名，文件夹都出现乱码，希望可以修复。

**Comment by kalcaddle** [comment]
linux 的话系统编码默认为utf-8；
如果不是的话自己修改代码config/config.php 
$config['system_charset']  ="你的系统编码"   即可

**Comment by yovisun** [comment]
用你这方案可以解决，但是无法访问了。。。

**Comment by kalcaddle** [comment]
url带中文需要urlencode的。自己处理下；具体解决方法自行百度。

**Comment by yovisun** [comment]
这个我清楚，请问，如果在您的代码中修改呢？

**Comment by kalcaddle** [comment]
代码里按url_decode 处理成utf8 然后根据系统编码查找文档路径的。只要系统路编码和config.php配置一致就自动处理的。
