### ISSUE TITLE
文件夹目录结构排序是乱的

### ISSUE THREAD

**Issue by Wizzercn** [kalcaddle/KODExplorer#80]
![qq 20160804115605](https://cloud.githubusercontent.com/assets/2408114/17389949/fe49a108-5a3a-11e6-83db-7a139eb08a36.png)

不是按时间、也不是按文件夹名称？也没配置选项？

**Comment by kalcaddle** [comment]
标题明显自己选中了【按修改时间降序】啊！

**Comment by Wizzercn** [comment]
@kalcaddle 就是因为选了没有用，左侧树顺序也不变啊，你试一下看？

**Comment by kalcaddle** [comment]
左侧目录树是按默认操作系统遍历排序的。
目前排序只针对文件列表，后续会考虑优化排序

**Comment by lsqswl** [comment]
手机端看排序还是乱的。电脑端可以排序。
