### ISSUE TITLE
Error Verification Code not displaying

### ISSUE THREAD

**Issue by jarisgv** [kalcaddle/KODExplorer#81]
Hello folks,
Verification code is not displaying. So how can I log in when the system ask me for the code since no code image seems to be stored in KODExplorer? I cannot login anymore... :o
Somebody help me, please.
Greetings from Brazil

**Comment by jarisgv** [comment]
![image](https://cloud.githubusercontent.com/assets/19142770/17533361/b349b94e-5e5a-11e6-8ed4-0d3d9e3f67e1.png)

**Comment by kalcaddle** [comment]
we has areadly fix this bug；

**Comment by jarisgv** [comment]
Great! Where is  the files to solve it or will it be available just in the next release?

**Comment by kalcaddle** [comment]
https://github.com/kalcaddle/KODExplorer/archive/3.22.zip

**Comment by jarisgv** [comment]
Thanks a lot!!!!
Greetings from Brazil!
