### ISSUE TITLE
Bug dragging dropping directory

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KODExplorer#82]
Hi, I have a folder in my personal computer which has 3 subdiretories in it and 2 of those subdirectories have files inside but one of those subdirectories has no files inside. When I drag and drop the folder (which has 3 subdirectories) to KODEXPLORER it does a really good job making the upload of all the files but it does not create the folder that is empty. It creates the 2 directories that has files but the other directory that has no files is not created in the server.

This bug is easy to reproduce, just upload a folder which has an empty folder inside and you will see kodexplorer will not create that empty folder in the server which is not good!

**Comment by kalcaddle** [comment]
it will be fixed on version 3.3
