### ISSUE TITLE
Bug importing entire directory tree

### ISSUE THREAD

**Issue by batata004** [kalcaddle/KODExplorer#83]
Hi, I have a directory XXX with 10 files inside it (regular .txt files) and I also have another 8 directories inside this XXX directory. I have also another 50 files inside those 8 directories. When I drag and drop the XXX directory to KODEXPLORER and if I dont do anything else (just wait) everything works fine, great!

BUT if I click the MINIZE button of the dialog where it shows the files being uploaded and start browsing other directories in the KODEXPLORER it will generate a copy of the XXX direcoty in almost all directories that I visit while the upload is being done!

This is a serious bug cause I was uploading a directory with 200 files yesterday and now I looked inside my server and that directory got replicated ove many other directories that I opened while the upload was being done! This is a very easy bug to reproduce and I really hope a fix will be made availabe cause this editor is AMAZING but unfortunatelly some bugs keep happening.

**Comment by kalcaddle** [comment]
When has many small files uoload，I suggest achieve the folder and upload it；
It will be more fast.

---
we will fixed it next version.
this project  not bring  income,you can donate us and support our project
thanks (paypal:kalcaddle@qq.com)

**Comment by batata004** [comment]
I agree, zipping the file would be much faster! But thank you for fixing thi I will look forward a donation for your great work!

**Comment by kalcaddle** [comment]
Last version 3.34 , fix it
You can have a try.
