### ISSUE TITLE
阿里云 lnmpa 下 kodExplorer 无权限 访问其他文件夹

### ISSUE THREAD

**Issue by puregardenia** [kalcaddle/KODExplorer#84]
之前在wnmp下是可以访问C://下除系统启动目录外的目录，但是最近换到 lnmpa下 只能访问 wwwroot下的文件了，连其他站点的文件都不能访问了，是KODExplorer升级了，把权限改了吗？
![image](https://cloud.githubusercontent.com/assets/14371054/17646684/343135c8-6207-11e6-83ca-b2f709d8453d.png)

**Comment by kalcaddle** [comment]
linux系统的权限限制（具体自行百度）。权限机制和window完全不一样。
想要访问可以登陆系统，用chmod修改。
