### ISSUE TITLE
运行环境监测: error:  data/thumb/	不可写

### ISSUE THREAD

**Issue by cxgreat2014** [kalcaddle/KODExplorer#88]
首次运行时环境检测提示：
运行环境监测:
error:

data/thumb/	不可写

我是windows用户用phpstudy建的站，按理来说不会有权限问题，于是我到data目录底下一看，既没有thumb目录，程序也没自动创建，这算是个BUG吧？

修复一下，加入自动创建或者直接在data下建立这个目录就行了

**Comment by kalcaddle** [comment]
github clone会忽略空文件夹。通过官网给的链接下载吧。
