### ISSUE TITLE
本地上传文件，上传失败时却显示上传成功的问题

### ISSUE THREAD

**Issue by CoolSpring8** [kalcaddle/KODExplorer#9]
你好，图中文件上传失败了，但上面却显示“上传成功：1/1”，是不是应该加个判断呢？
![image](https://cloud.githubusercontent.com/assets/8985327/6935926/ea5cafee-d87e-11e4-8d9f-5f425c3ebbd2.jpg)
虽然不是很大的问题，但还是祝愿KODExplorer能变得更加完美！

**Comment by kalcaddle** [comment]
谢谢关注  后面 优化一下。

**Comment by kalcaddle** [comment]
还有，什么原因导致的失败呢？

**Comment by CoolSpring8** [comment]
不好意思，因为这个网站的配置不是很典型（HHVM 3.6.0+nginx 1.7.8，用了CloudFlare的CDN），所以不太清楚失败的原因。初步推测可能是CloudFlare的Max Upload Size（ 100M ）或者上传时间太长超时所致吧。

**Comment by kalcaddle** [comment]
上传时客户端做了分片处理，基本上不再受限于php.ini限制了。
