### ISSUE TITLE
编辑器在win10 chrome下中文输入会出现各种奇怪的错误

### ISSUE THREAD

**Issue by Pancts** [kalcaddle/KODExplorer#91]
还有切换中文输入法后 无法ctrl+s，会弹出保存页面再次ctrl+s才会保存

**Comment by kalcaddle** [comment]
chrome 53之后的问题。ace editor中文输入的bug；
等待ace或者chrome修复

**Comment by kalcaddle** [comment]
Last version 3.34 , fix it
You can have a try.
