### ISSUE TITLE
1.Chrom浏览器在访问有安全配置的服务器端后出现的问题

### ISSUE THREAD

**Issue by ming42** [kalcaddle/KODExplorer#95]
1. 在服务器端启用两项安全配置后无法正常使用
Web Server NginX
相关服务器配置：
``` 
add_header X-Frame-Options DENY;
add_header X-Content-Type-Options nosniff;
```
当服务器启用 `add_header X-Content-Type-Options nosniff;` 后common_js无法正常载入
相关链接：
<http://stackoverflow.com/questions/24528211/refused-to-execute-script-from-because-its-mime-type-application-json-is>
<https://segmentfault.com/q/1010000000651666>
当服务器启用 `add_header X-Frame-Options DENY;` 后 系统设置/用户管理 等无法正常弹出

2.还有一个问题就是之前有人反映过的 `http://static.kalcaddle.com/update/main.js?a=uuid_...` 如果启用 SSL 后因为该地址不是 HTTPS 会被 Chrome 认为不安全而 Block

**Comment by kalcaddle** [comment]
感谢反馈

**Comment by kalcaddle** [comment]
感谢反馈，下个版本会解决

**Comment by kalcaddle** [comment]
Last version 3.34 , fix it
