### ISSUE TITLE
远程下载提示操作失败，已经给了安装路径777权限

### ISSUE THREAD

**Issue by qinchan** [kalcaddle/KODExplorer#97]
如题

**Comment by kalcaddle** [comment]
检查一下：
1. 下载保存的目录必须可读写；chmod -Rf 777 ./你的目录
2. 输入的地址是真实，且当前服务器可访问，保证网络链路是通的。
3. 如果下载到一半失败则有可能是php运行超时，则检查php设置的超时时间。改的大一些。
