### ISSUE TITLE
How can I hide/disable the root path in the directory?

### ISSUE THREAD

**Issue by rochellecanale** [kalcaddle/KODExplorer#98]
Hi,
I have a multiple user in my system and I want to restrict the access of every user group. And I am passing the default path like this:

`http://localhost/mysystem/kodexplorer/index.php?explorer/index&path=C:/xampp/htdocs/mysystem/file_uploads`

But in the directory path I can manually click and go back to its parent root or any folder I want to access.
How can I restrict the directory by a specific user group? Is there a function like that?

**Comment by kalcaddle** [comment]
New version 3.3 supports user groups, and custom user directory and group directory; 
stay tuned

**Comment by rochellecanale** [comment]
Ok thanks. Im hoping that you can release it. It has a really nice UI and very simple to use. :) By the way what's the use of position in the  member setting? Can I make or set a default directory in this setting?

**Comment by kalcaddle** [comment]
Last version 3.34 , fix it
You can have a try.
